/**
 * TaskExecutionChat Component
 * Chat interface for executing tasks with Claude AI
 */

'use client';

import { useState, useEffect, useRef } from 'react';
import { chatSessionsApi, tasksApi, commitsApi } from '@/lib/api';
import { ChatSession, Task } from '@/lib/types';
import { Button, Badge } from '@/components/ui';

interface Props {
  sessionId: string;
  taskId: string;
  onClose?: () => void;
}

export function TaskExecutionChat({ sessionId, taskId, onClose }: Props) {
  const [session, setSession] = useState<ChatSession | null>(null);
  const [task, setTask] = useState<Task | null>(null);
  const [message, setMessage] = useState('');
  const [loading, setLoading] = useState(false);
  const [executing, setExecuting] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  useEffect(() => {
    loadData();
  }, [sessionId, taskId]);

  useEffect(() => {
    scrollToBottom();
  }, [session?.messages]);

  const loadData = async () => {
    setLoading(true);
    try {
      const [sessionRes, taskRes] = await Promise.all([
        chatSessionsApi.get(sessionId),
        tasksApi.get(taskId),
      ]);
      setSession(sessionRes.data);
      setTask(taskRes.data);
    } catch (error) {
      console.error('Failed to load data:', error);
      alert('Failed to load chat session or task');
    } finally {
      setLoading(false);
    }
  };

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  const handleSendMessage = async () => {
    if (!message.trim() || executing) return;

    setExecuting(true);
    const userMessage = message;
    setMessage('');

    try {
      await chatSessionsApi.sendMessage(sessionId, userMessage);
      await loadData(); // Reload to get AI response
    } catch (error: any) {
      console.error('Failed to send message:', error);
      const errorMessage = error.response?.data?.detail || 'Failed to send message';
      alert(`Error: ${errorMessage}`);
      setMessage(userMessage); // Restore message
    } finally {
      setExecuting(false);
      textareaRef.current?.focus();
    }
  };

  const handleExecuteDirect = async () => {
    if (!confirm('Execute this task with AI? The AI will analyze the task and prompt to provide a solution.')) {
      return;
    }

    setExecuting(true);
    try {
      await chatSessionsApi.execute(sessionId);
      await loadData(); // Reload to get AI response
    } catch (error: any) {
      console.error('Failed to execute task:', error);
      const errorMessage = error.response?.data?.detail || 'Failed to execute task';
      alert(`Error: ${errorMessage}`);
    } finally {
      setExecuting(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleApprove = async () => {
    if (!confirm('Approve this task execution, generate commit, and mark as completed?')) return;

    setExecuting(true);
    try {
      // 1. Generate commit automatically using AI (Gemini)
      const commitResponse = await commitsApi.autoGenerate(sessionId);

      console.log('Commit generated:', commitResponse.data);

      // 2. Mark task as completed
      await tasksApi.update(taskId, { status: 'done' });

      // 3. Show success message with commit
      alert(`✅ Task completed!\n\nCommit: ${commitResponse.data.message}\nGenerated by: ${commitResponse.data.created_by_ai_model}`);

      onClose?.();
    } catch (error: any) {
      console.error('Failed to complete task:', error);
      const errorMessage = error.response?.data?.detail || 'Failed to complete task';
      alert(`Error: ${errorMessage}`);
    } finally {
      setExecuting(false);
    }
  };

  if (loading && !session) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="flex flex-col items-center gap-3">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-blue-600"></div>
          <p className="text-gray-600">Loading task execution...</p>
        </div>
      </div>
    );
  }

  if (!session || !task) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-gray-500">Failed to load task execution session</div>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-[700px] bg-white rounded-lg shadow-lg">
      {/* Header */}
      <div className="border-b p-4 bg-gray-50 rounded-t-lg">
        <div className="flex justify-between items-start mb-3">
          <div className="flex-1">
            <h2 className="text-xl font-bold text-gray-900">{task.title}</h2>
            <p className="text-sm text-gray-600 mt-1">{task.description || 'No description'}</p>
          </div>
          <button
            onClick={onClose}
            className="text-gray-400 hover:text-gray-600 ml-4"
          >
            <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        <div className="flex flex-wrap gap-2">
          <Badge variant={session.status === 'active' ? 'success' : session.status === 'completed' ? 'default' : 'danger'}>
            {session.status.toUpperCase()}
          </Badge>
          <Badge variant="default">
            {task.status.toUpperCase()}
          </Badge>
        </div>

        <div className="mt-4 flex flex-wrap gap-2">
          <Button
            onClick={handleExecuteDirect}
            disabled={executing || session.status !== 'active'}
            variant="primary"
            size="sm"
          >
            {executing ? (
              <>
                <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white mr-1"></div>
                Executing...
              </>
            ) : (
              <>
                <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M14.752 11.168l-3.197-2.132A1 1 0 0010 9.87v4.263a1 1 0 001.555.832l3.197-2.132a1 1 0 000-1.664z" />
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                </svg>
                Execute Task
              </>
            )}
          </Button>

          <Button
            onClick={handleApprove}
            variant="outline"
            size="sm"
            disabled={session.messages?.length === 0}
          >
            <svg className="w-4 h-4 mr-1" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
            </svg>
            Approve & Complete
          </Button>
        </div>
      </div>

      {/* Messages Area */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 bg-gradient-to-b from-gray-50 to-white">
        {!session.messages || session.messages.length === 0 ? (
          <div className="text-center text-gray-400 py-12">
            <svg
              className="w-16 h-16 mx-auto mb-4 text-gray-300"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M8 10h.01M12 10h.01M16 10h.01M9 16H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-5l-5 5v-5z"
              />
            </svg>
            <p className="text-lg mb-2 font-medium">No messages yet</p>
            <p className="text-sm">Click "Execute Task" to start AI execution or send a message</p>
          </div>
        ) : (
          <>
            {session.messages.map((msg, index) => {
              const isUser = msg.role === 'user';
              const isSystem = msg.role === 'system';

              if (isSystem) {
                return (
                  <div key={index} className="text-center py-2">
                    <Badge variant="default" className="bg-gray-100 text-gray-600">
                      {msg.content}
                    </Badge>
                  </div>
                );
              }

              return (
                <div
                  key={index}
                  className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}
                >
                  <div className={`max-w-[80%] ${isUser ? 'order-2' : 'order-1'}`}>
                    <div className={`text-xs font-semibold mb-1 ${isUser ? 'text-right' : 'text-left'}`}>
                      <Badge variant={isUser ? 'info' : 'default'} size="sm">
                        {isUser ? 'You' : 'AI Assistant'}
                      </Badge>
                    </div>
                    <div
                      className={`rounded-lg p-4 ${
                        isUser
                          ? 'bg-blue-600 text-white'
                          : 'bg-white text-gray-900 border border-gray-200'
                      }`}
                    >
                      <pre className="whitespace-pre-wrap font-sans text-sm leading-relaxed">
                        {msg.content}
                      </pre>
                      {!isUser && (msg.provider || msg.model) && (
                        <div className="mt-3 pt-3 border-t border-gray-200 text-xs text-gray-500">
                          Powered by: <span className="font-semibold text-gray-700">
                            {msg.provider || 'AI'} {msg.model ? `(${msg.model})` : ''}
                          </span>
                        </div>
                      )}
                    </div>
                  </div>
                </div>
              );
            })}
            <div ref={messagesEndRef} />
          </>
        )}

        {/* Loading indicator */}
        {executing && (
          <div className="flex justify-start">
            <div className="bg-gray-200 rounded-lg px-4 py-3">
              <div className="flex gap-1">
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce"></div>
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.1s' }}></div>
                <div className="w-2 h-2 bg-gray-400 rounded-full animate-bounce" style={{ animationDelay: '0.2s' }}></div>
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Input Area */}
      <div className="border-t p-4 bg-gray-50 rounded-b-lg">
        {session.status === 'active' ? (
          <div className="space-y-2">
            <textarea
              ref={textareaRef}
              value={message}
              onChange={(e) => setMessage(e.target.value)}
              onKeyDown={handleKeyDown}
              placeholder="Send additional instructions or ask questions... (Shift+Enter for new line, Enter to send)"
              disabled={executing}
              className="w-full border border-gray-300 rounded-lg px-4 py-3 resize-none focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent disabled:bg-gray-100"
              rows={3}
            />

            <div className="flex justify-between items-center">
              <span className="text-xs text-gray-500">
                Shift+Enter for new line, Enter to send
              </span>

              <Button
                onClick={handleSendMessage}
                disabled={!message.trim() || executing}
                variant="primary"
                size="sm"
              >
                {executing ? 'Sending...' : 'Send Message'}
              </Button>
            </div>
          </div>
        ) : (
          <div className="text-center text-gray-400 py-4 bg-gray-100 rounded-lg">
            <p className="text-sm font-medium">
              This session is {session.status}. Cannot send messages.
            </p>
          </div>
        )}
      </div>
    </div>
  );
}
