'use client';
import { FormEvent, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { CalendarClock, Link2, Plus, Unlink } from 'lucide-react';
import { api, Board, getToken, send, User } from '@/lib/api';
import { AppHeader } from '@/components/ui';
type Card={id:string;title:string;due_date:string;completed:boolean;board_id:string;board_title:string;list_title:string};type Event={id:string;title:string;starts_at:string;ends_at:string;cards:Card[]};
export default function Planner(){const router=useRouter();const [boards,setBoards]=useState<Board[]>([]),[user,setUser]=useState<User|null>(null),[cards,setCards]=useState<Card[]>([]),[events,setEvents]=useState<Event[]>([]),[board,setBoard]=useState(''),[start,setStart]=useState(''),[end,setEnd]=useState(''),[title,setTitle]=useState('Focus time'),[target,setTarget]=useState(''),[error,setError]=useState('');
 const load=async(id=board)=>{try{const [data,all,u]=await Promise.all([api<{cards:Card[];events:Event[]}>(`/planner${id?`?board_id=${id}`:''}`),api<Board[]>('/boards'),api<User>('/auth/me')]);setCards(data.cards);setEvents(data.events);setBoards(all);setUser(u);setTarget(data.cards[0]?.id||'')}catch(e){setError((e as Error).message)}};
 // eslint-disable-next-line react-hooks/exhaustive-deps
 useEffect(()=>{const timer=window.setTimeout(()=>{if(!getToken()){router.push('/');return}void load()},0);return()=>window.clearTimeout(timer)},[router]);
 async function create(e:FormEvent){e.preventDefault();try{await send('/planner/focus-events','POST',{title,starts_at:new Date(start).toISOString(),ends_at:new Date(end).toISOString()});await load()}catch(e){setError((e as Error).message)}}
 async function link(event:string){if(!target)return;await send(`/planner/focus-events/${event}/cards/${target}`,'POST');await load()};async function unlink(event:string,card:string){await send(`/planner/focus-events/${event}/cards/${card}`,'DELETE');await load()}
 return <div className="min-h-screen bg-[#f7f8fa]"><AppHeader user={user} boards={boards}/><main className="mx-auto grid max-w-7xl gap-6 p-4 sm:p-6 lg:grid-cols-[360px_1fr]"><aside className="rounded-xl border bg-white p-4 shadow-sm"><h1 className="flex items-center gap-2 text-xl font-bold"><CalendarClock className="text-[#0c66e4]"/> Planner</h1><p className="mt-1 text-sm text-[#626f86]">Planeje o tempo de execução sem mudar o prazo do cartão.</p><select value={board} onChange={e=>{setBoard(e.target.value);void load(e.target.value)}} className="mt-4 w-full rounded border p-2 text-sm"><option value="">Todos os quadros e Inbox</option>{boards.map(b=><option key={b.id} value={b.id}>{b.title}</option>)}</select><form onSubmit={create} className="mt-5 space-y-2 border-t pt-4"><h2 className="font-bold">Novo Focus Time</h2><input value={title} onChange={e=>setTitle(e.target.value)} className="w-full rounded border p-2 text-sm"/><input required type="datetime-local" value={start} onChange={e=>setStart(e.target.value)} className="w-full rounded border p-2 text-sm"/><input required type="datetime-local" value={end} onChange={e=>setEnd(e.target.value)} className="w-full rounded border p-2 text-sm"/><button className="flex w-full items-center justify-center gap-1 rounded bg-[#0c66e4] p-2 text-sm font-semibold text-white"><Plus size={16}/> Reservar tempo</button></form>{error&&<p className="mt-3 text-xs text-[#ae2a19]">{error}</p>}</aside><section><h2 className="mb-3 text-lg font-bold">Cartões com vencimento</h2><div className="grid gap-2 sm:grid-cols-2">{cards.map(c=><div key={c.id} className="rounded-xl border bg-white p-3 shadow-sm"><p className="font-semibold">{c.title}</p><p className="text-xs text-[#626f86]">{c.board_title} · {new Date(c.due_date).toLocaleString('pt-BR')}</p></div>)}</div><h2 className="mb-3 mt-7 text-lg font-bold">Blocos de foco</h2><div className="space-y-3">{events.map(e=><div key={e.id} className="rounded-xl border-l-4 border-[#0c66e4] bg-white p-4 shadow-sm"><div className="flex flex-wrap justify-between gap-2"><div><b>{e.title}</b><p className="text-xs text-[#626f86]">{new Date(e.starts_at).toLocaleString('pt-BR')} — {new Date(e.ends_at).toLocaleString('pt-BR')}</p></div><div className="flex gap-2"><select value={target} onChange={x=>setTarget(x.target.value)} className="max-w-48 rounded border p-1 text-xs">{cards.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select><button onClick={()=>void link(e.id)} title="Vincular cartão" className="rounded bg-[#e9f2ff] p-2 text-[#0c66e4]"><Link2 size={15}/></button></div></div><div className="mt-3 flex flex-wrap gap-2">{e.cards.map(c=><span key={c.id} className="flex items-center gap-1 rounded bg-[#f1f2f4] px-2 py-1 text-xs">{c.title}<button onClick={()=>void unlink(e.id,c.id)} title="Desvincular"><Unlink size={13}/></button></span>)}{!e.cards.length&&<span className="text-xs text-[#626f86]">Nenhum cartão vinculado.</span>}</div></div>)}</div></section></main></div>}
