'use client';

import {useCallback,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowLeft,DatabaseBackup,HardDrive,History,LoaderCircle,LockKeyhole,RotateCcw} from 'lucide-react';
import {api,getToken,send,User,Board} from '@/lib/api';
import {AppHeader,useConfirmModal,WorkspaceSidebar} from '@/components/ui';

type CloudCopy={id:string;provider:string;connectionId:string;status:string;error:string|null;archiveFileId:string|null;folderId?:string|null;folderPath?:string|null};
type Backup={archive:string;created_at?:string;reason?:string;archive_bytes?:number;invalid_manifest?:boolean;remoteOnly?:boolean;cloudCopies?:CloudCopy[];cloud?:CloudCopy|null;vaultBackup?:VaultBackup|null;vaultError?:string|null;configBackup?:{archive:string;cloud?:CloudCopy|null}|null;attachments?:{processed:number;failed:number}};
type VaultBackup={archive:string;created_at?:string;item_count?:number;remoteOnly?:boolean;cloudCopies?:CloudCopy[];cloud?:CloudCopy|null};
type ConfigBackup={archive:string;created_at?:string;file_count?:number;remoteOnly?:boolean;cloudCopies?:CloudCopy[]};
type AttachmentBackup={archive:string;created_at?:string;source_kind?:'card'|'comment';file_bytes?:number;remoteOnly?:boolean;cloudCopies?:CloudCopy[]};
type BackupOptions={destinations:Array<{id:string;name:string}>;googleConfigured:boolean;googleConnections:Array<{id:string;name:string}>;automatic:{connectionId:string|null;enabled:boolean;needsSelection:boolean}};
type RestoreResult={counts?:{users:number;boards:number;cards:number;attachments:number}};

export default function BackupsPage(){
  const router=useRouter(),{confirm,confirmationModal}=useConfirmModal();
  const [user,setUser]=useState<User|null>(null),[boards,setBoards]=useState<Board[]>([]),[backups,setBackups]=useState<Backup[]>([]),[vaultBackups,setVaultBackups]=useState<VaultBackup[]>([]),[configBackups,setConfigBackups]=useState<ConfigBackup[]>([]),[attachmentBackups,setAttachmentBackups]=useState<AttachmentBackup[]>([]),[options,setOptions]=useState<BackupOptions|null>(null);
  const [connectionId,setConnectionId]=useState(''),[automaticEnabled,setAutomaticEnabled]=useState(true);
  const [busy,setBusy]=useState(false),[restoring,setRestoring]=useState(''),[message,setMessage]=useState(''),[error,setError]=useState('');
  const load=useCallback(async()=>{try{const [account,all,rows,vaultRows,configRows,attachmentRows,choices]=await Promise.all([api<User>('/auth/me'),api<Board[]>('/boards'),api<Backup[]>('/backups'),api<VaultBackup[]>('/backups/vault'),api<ConfigBackup[]>('/backups/config'),api<AttachmentBackup[]>('/backups/attachments'),api<BackupOptions>('/backups/options')]);setUser(account);setBoards(all);setBackups(rows);setVaultBackups(vaultRows);setConfigBackups(configRows);setAttachmentBackups(attachmentRows);setOptions(choices);setConnectionId(current=>current||choices.automatic.connectionId||choices.googleConnections[0]?.id||'');setAutomaticEnabled(choices.automatic.enabled)}catch(reason){setError((reason as Error).message)}},[]);
  useEffect(()=>{if(!getToken()){router.replace('/');return}const timer=window.setTimeout(()=>{const params=new URLSearchParams(window.location.search);if(params.get('error'))setError(params.get('error')||'Falha na conexão Google.');else if(params.get('connected'))setMessage('Conta Google conectada. Selecione-a para salvar no Drive.');void load()},0);return()=>window.clearTimeout(timer)},[load,router]);
  async function create(){setBusy(true);setError('');setMessage('');try{const backup=await send<Backup>('/backups','POST',{});const messages=[`Backup do banco criado: ${backup.archive}.`,backup.cloud?.status==='failed'?`Envio ao Drive falhou: ${backup.cloud.error}`:backup.cloud?.status==='success'?'Banco salvo no Drive.':'',backup.vaultError?`Backup do cofre falhou: ${backup.vaultError}`:backup.vaultBackup?`Cofre salvo separadamente: ${backup.vaultBackup.archive}.`:'' ,backup.vaultBackup?.cloud?.status==='failed'?`Envio do cofre ao Drive falhou: ${backup.vaultBackup.cloud.error}`:backup.vaultBackup?.cloud?.status==='success'?'Cofre salvo no Drive.':'',backup.configBackup?.cloud?.status==='failed'?`Envio das configurações ao Drive falhou: ${backup.configBackup.cloud.error}`:backup.configBackup?.cloud?.status==='success'?'Configurações salvas no Drive.':'',backup.attachments?.failed?`${backup.attachments.failed} anexos falharam no envio; tente novamente na seção de anexos.`:''];setMessage(messages.filter(Boolean).join(' '));await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function createVaultOnly(){setBusy(true);setError('');setMessage('');try{const backup=await send<VaultBackup>('/backups/vault','POST');setMessage(backup.cloud?.status==='failed'?`Backup do cofre criado localmente, mas o envio ao Drive falhou: ${backup.cloud.error}`:backup.cloud?.status==='success'?`Backup do cofre criado e salvo no Drive: ${backup.archive}`:`Backup do cofre criado localmente: ${backup.archive}`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function saveAutomatic(){setBusy(true);setError('');try{await send('/backups/automatic','PATCH',{connectionId,enabled:automaticEnabled});setMessage(automaticEnabled?'Envio automático do banco, cofre, configurações e anexos ativado.':'Envio automático desativado.');await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function syncAttachments(){setBusy(true);setError('');setMessage('');try{const result=await send<{processed:number;failed:number}>('/backups/attachments/sync','POST');setMessage(`${result.processed} anexos verificados nesta rodada${result.failed?`; ${result.failed} falharam e serão tentados novamente`:''}.`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function uploadAttachment(backup:AttachmentBackup){setBusy(true);setError('');setMessage('');try{const copy=await send<CloudCopy>(`/backups/attachments/${encodeURIComponent(backup.archive)}/upload`,'POST',{connectionId});setMessage(copy.status==='success'?'Anexo salvo no Google Drive.':`Envio do anexo falhou: ${copy.error}`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function downloadAttachment(copy:CloudCopy){setBusy(true);setError('');setMessage('');try{await send(`/backups/attachments/cloud/${copy.id}/download`,'POST');setMessage('Anexo baixado e verificado. Use a CLI para extrair o arquivo original.');await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function createConfig(){setBusy(true);setError('');setMessage('');try{const result=await send<{archive:string|null;deliveries:CloudCopy[]}>('/backups/config','POST');setMessage(result.deliveries.some(copy=>copy.status==='failed')?`Backup local atualizado, mas o envio ao Drive falhou: ${result.deliveries.find(copy=>copy.status==='failed')?.error}`:result.archive?`Configurações verificadas: ${result.archive}.`:'Nenhum arquivo de configuração encontrado.');await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function uploadConfig(backup:ConfigBackup){setBusy(true);setError('');setMessage('');try{const copy=await send<CloudCopy>(`/backups/config/${encodeURIComponent(backup.archive)}/upload`,'POST',{connectionId});setMessage(copy.status==='success'?`Configurações ${backup.archive} salvas no Google Drive.`:`Envio das configurações falhou: ${copy.error}`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function downloadConfig(copy:CloudCopy){setBusy(true);setError('');setMessage('');try{const backup=await send<ConfigBackup>(`/backups/config/cloud/${copy.id}/download`,'POST');setMessage(`Configurações ${backup.archive} baixadas e verificadas. Use a CLI para restaurá-las em uma pasta vazia.`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function upload(backup:Backup){setBusy(true);setError('');setMessage('');try{const copy=await send<CloudCopy>(`/backups/${encodeURIComponent(backup.archive)}/upload`,'POST',{connectionId});setMessage(copy.status==='success'?`Backup ${backup.archive} salvo no Google Drive.`:`Envio ao Drive falhou: ${copy.error}`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function download(copy:CloudCopy){setBusy(true);setError('');setMessage('');try{const backup=await send<Backup>(`/backups/cloud/${copy.id}/download`,'POST');setMessage(`Backup ${backup.archive} baixado e verificado. Agora pode ser restaurado.`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function uploadVault(backup:VaultBackup){setBusy(true);setError('');setMessage('');try{const copy=await send<CloudCopy>(`/backups/vault/${encodeURIComponent(backup.archive)}/upload`,'POST',{connectionId});setMessage(copy.status==='success'?`Cofre ${backup.archive} salvo no Google Drive.`:`Envio do cofre falhou: ${copy.error}`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function downloadVault(copy:CloudCopy){setBusy(true);setError('');setMessage('');try{const backup=await send<VaultBackup>(`/backups/vault/cloud/${copy.id}/download`,'POST');setMessage(`Backup do cofre ${backup.archive} baixado e verificado.`);await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  function restoreVault(backup:VaultBackup){confirm({title:'Restaurar cofre',description:`Importar os itens de ${backup.archive} para o cofre atual? Os itens existentes serão preservados.`,confirmLabel:'Importar itens',destructive:false},async()=>{setRestoring(backup.archive);setError('');setMessage('');try{const result=await send<{restoredItems:number;restoredCategories:number}>(`/backups/vault/${encodeURIComponent(backup.archive)}/restore`,'POST');setMessage(`${result.restoredItems} itens e ${result.restoredCategories} categorias importados para o cofre.`)}catch(reason){setError((reason as Error).message)}finally{setRestoring('')}})}
  async function connectGoogle(){setBusy(true);setError('');try{const result=await api<{url:string}>('/google/drive/oauth/start');window.location.assign(result.url)}catch(reason){setError((reason as Error).message);setBusy(false)}}
  function restore(backup:Backup){if(backup.invalid_manifest)return;confirm({title:'Restaurar backup',description:`Restaurar ${backup.archive} em um banco novo e vazio configurado para recuperação?`,confirmLabel:'Restaurar',destructive:false},async()=>{setRestoring(backup.archive);setError('');setMessage('');try{const result=await send<RestoreResult>(`/backups/${encodeURIComponent(backup.archive)}/restore`,'POST');const counts=result.counts;setMessage(counts?`Backup restaurado em banco separado. ${counts.users} usuários, ${counts.boards} quadros e ${counts.cards} cartões restaurados. Valide o destino e altere a conexão da aplicação quando estiver pronto.`:'Backup restaurado em banco separado. Valide o destino antes de alterar a conexão da aplicação.')}catch(reason){setError((reason as Error).message)}finally{setRestoring('')}})}
  return <div className="flex min-h-screen flex-col bg-[#f7f8fa]"><AppHeader user={user} boards={boards}/><div className="flex min-h-0 flex-1"><WorkspaceSidebar boards={boards} onCreate={()=>router.push('/boards?create=1')} onChoose={id=>router.push(id?`/board/${id}`:'/boards')}/><main className="mx-auto w-full max-w-[1000px] flex-1 p-5 sm:p-8">
    <button onClick={()=>router.push('/')} className="mb-5 inline-flex items-center gap-2 text-sm font-semibold text-[#44546f] hover:text-[#0c66e4]"><ArrowLeft size={16}/> Início</button>
    <div className="mb-6 flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#eeedfd] text-[#403294]"><DatabaseBackup size={22}/></span><div><h1 className="text-2xl font-bold">Backups</h1><p className="text-sm text-[#626f86]">Banco, cofre, configurações e anexos têm cópias criptografadas separadas.</p></div></div>
    <section className="mb-5 rounded-xl border border-[#dfe1e6] bg-white p-5">
      <h2 className="font-semibold">Envio automático ao Google Drive</h2>
      <p className="mt-1 text-sm text-[#626f86]">A conta escolhida recebe backups do banco, cofre, configurações e anexos dos cartões. Configurações e anexos novos são enviados quando mudam.</p>
      <div className="mt-3 flex flex-wrap items-end gap-3"><label className="min-w-[240px] flex-1 text-sm">Conta Google<select className="mt-1 w-full rounded border border-[#8590a2] bg-white px-3 py-2" value={connectionId} onChange={event=>setConnectionId(event.target.value)}><option value="">Selecione uma conta</option>{options?.googleConnections.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="flex items-center gap-2 pb-2 text-sm"><input type="checkbox" checked={automaticEnabled} onChange={event=>setAutomaticEnabled(event.target.checked)}/> Enviar automaticamente</label><button disabled={busy||!connectionId} onClick={()=>void saveAutomatic()} className="rounded bg-[#403294] px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">Salvar</button></div>
      {options?.automatic.needsSelection&&<p className="mt-2 text-sm text-[#ae2a19]">Há mais de uma conta Drive. Escolha uma e salve para ativar o envio automático.</p>}
      {options?.googleConfigured&&options.destinations.some(item=>item.id==='google_drive')&&<button onClick={()=>void connectGoogle()} disabled={busy} className="mt-3 text-sm font-semibold text-[#0c66e4]">Conectar outra conta Google</button>}
      {!options?.googleConfigured&&<p className="mt-2 text-sm text-[#626f86]">Configure as credenciais Google compartilhadas para conectar o Drive.</p>}
    </section>
    <section className="mb-5 rounded-xl border border-[#dfe1e6] bg-white p-5"><h2 className="font-semibold">Criar backup agora</h2><p className="mt-1 text-sm text-[#626f86]">O backup completo salva banco, cofre e configurações em arquivos distintos. Você também pode salvar só o cofre.</p><div className="mt-3 flex flex-wrap gap-3"><button disabled={busy} onClick={()=>void create()} className="inline-flex items-center gap-2 rounded bg-[#403294] px-3 py-2 text-sm font-semibold text-white disabled:opacity-60">{busy?<LoaderCircle size={16} className="animate-spin"/>:<DatabaseBackup size={16}/>} Backup completo</button><button disabled={busy} onClick={()=>void createVaultOnly()} className="inline-flex items-center gap-2 rounded border border-[#403294] px-3 py-2 text-sm font-semibold text-[#403294] disabled:opacity-60"><LockKeyhole size={16}/> Só cofre</button></div></section>
    <div className="mb-5 flex gap-3 rounded-lg border border-[#b3d4ff] bg-[#e9f2ff] p-4 text-sm text-[#344563]"><HardDrive size={18} className="mt-0.5 shrink-0 text-[#0c66e4]"/><p>A restauração usa um banco novo e vazio definido por <code>ORBIT_RESTORE_DATABASE_URL</code>. Depois de conferir os dados, atualize a conexão da aplicação para esse destino.</p></div>
    {error&&<p role="alert" className="mb-4 rounded bg-[#ffebe6] p-3 text-sm text-[#ae2a19]">{error}</p>}{message&&<p role="status" className="mb-4 rounded bg-[#dffcf0] p-3 text-sm text-[#216e4e]">{message}</p>}
    <section className="overflow-hidden rounded-xl border border-[#dfe1e6] bg-white shadow-sm"><div className="border-b border-[#dfe1e6] px-5 py-4"><h2 className="flex items-center gap-2 font-bold"><History size={18}/> Backups disponíveis</h2></div>{backups.length?backups.map(backup=><article key={backup.archive} className="flex flex-wrap items-center gap-3 border-b border-[#f1f2f4] px-5 py-4 last:border-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#f1f2f4] text-[#626f86]"><DatabaseBackup size={17}/></span><div className="min-w-0 flex-1"><strong className="block break-all text-sm">{backup.archive}</strong><span className="mt-1 block text-xs text-[#626f86]">{backup.created_at?new Date(backup.created_at).toLocaleString('pt-BR'):'Manifesto indisponível'}{backup.archive_bytes?` · ${(backup.archive_bytes/1024/1024).toFixed(1)} MB`:''}{backup.reason?` · ${backup.reason}`:''}</span>{backup.cloudCopies?.map(copy=><span key={copy.id} className="mt-1 block text-xs text-[#626f86]">Google Drive · {options?.googleConnections.find(item=>item.id===copy.connectionId)?.name||'Conta Google'} · {copy.status==='success'?'salvo':copy.status==='failed'?`falhou: ${copy.error}`:'enviando'}</span>)}</div>{backup.remoteOnly&&backup.cloudCopies?.filter(copy=>copy.status==='success').map(copy=><button key={copy.id} disabled={busy} onClick={()=>void download(copy)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Baixar do Drive</button>)}{!backup.remoteOnly&&connectionId&&options?.destinations.some(item=>item.id==='google_drive')&&<button disabled={busy||backup.invalid_manifest} onClick={()=>void upload(backup)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Enviar ao Drive</button>}<button disabled={backup.remoteOnly||backup.invalid_manifest||Boolean(restoring)} onClick={()=>void restore(backup)} className="inline-flex items-center gap-1.5 rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">{restoring===backup.archive?<LoaderCircle size={14} className="animate-spin"/>:<RotateCcw size={14}/>} Restaurar</button></article>):<p className="p-10 text-center text-sm text-[#626f86]">Ainda não há backups locais. Use “Criar backup manual” para criar o primeiro.</p>}</section>
    <section className="mt-5 overflow-hidden rounded-xl border border-[#dfe1e6] bg-white shadow-sm">
      <div className="border-b border-[#dfe1e6] px-5 py-4"><h2 className="flex items-center gap-2 font-bold"><LockKeyhole size={18}/> Backups separados do cofre</h2><p className="mt-1 text-sm text-[#626f86]">O arquivo é criptografado antes do envio e pode ser importado sem restaurar o banco inteiro.</p></div>
      {vaultBackups.length?vaultBackups.map(backup=><article key={backup.archive} className="flex flex-wrap items-center gap-3 border-b border-[#f1f2f4] px-5 py-4 last:border-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eeedfd] text-[#403294]"><LockKeyhole size={17}/></span><div className="min-w-0 flex-1"><strong className="block break-all text-sm">{backup.archive}</strong><span className="mt-1 block text-xs text-[#626f86]">{backup.created_at?new Date(backup.created_at).toLocaleString('pt-BR'):'Cópia remota'}{backup.item_count!==undefined?` · ${backup.item_count} itens`:''}</span>{backup.cloudCopies?.map(copy=><span key={copy.id} className="mt-1 block text-xs text-[#626f86]">Google Drive · {copy.status==='success'?'salvo':copy.status==='failed'?`falhou: ${copy.error}`:'enviando'}</span>)}</div>{backup.remoteOnly&&backup.cloudCopies?.filter(copy=>copy.status==='success').map(copy=><button key={copy.id} disabled={busy} onClick={()=>void downloadVault(copy)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Baixar do Drive</button>)}{!backup.remoteOnly&&connectionId&&<button disabled={busy} onClick={()=>void uploadVault(backup)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Enviar ao Drive</button>}<button disabled={backup.remoteOnly||Boolean(restoring)} onClick={()=>restoreVault(backup)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">{restoring===backup.archive?'Importando…':'Importar itens'}</button></article>):<p className="p-10 text-center text-sm text-[#626f86]">O próximo backup criará a primeira cópia separada do cofre.</p>}
    </section>
    <section className="mt-5 overflow-hidden rounded-xl border border-[#dfe1e6] bg-white shadow-sm">
      <div className="border-b border-[#dfe1e6] px-5 py-4"><h2 className="flex items-center gap-2 font-bold"><LockKeyhole size={18}/> Configurações protegidas</h2><p className="mt-1 text-sm text-[#626f86]">Arquivos .env ignorados pelo Git são criptografados e salvos na pasta Orbit Config Backups do Drive. Guarde ORBIT_BACKUP_KEY fora do servidor para recuperá-los.</p><button disabled={busy} onClick={()=>void createConfig()} className="mt-3 rounded border border-[#403294] px-3 py-2 text-xs font-semibold text-[#403294] disabled:opacity-40">Verificar e enviar agora</button></div>
      {configBackups.length?configBackups.map(backup=><article key={backup.archive} className="flex flex-wrap items-center gap-3 border-b border-[#f1f2f4] px-5 py-4 last:border-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eeedfd] text-[#403294]"><LockKeyhole size={17}/></span><div className="min-w-0 flex-1"><strong className="block break-all text-sm">{backup.archive}</strong><span className="mt-1 block text-xs text-[#626f86]">{backup.created_at?new Date(backup.created_at).toLocaleString('pt-BR'):'Cópia remota'}{backup.file_count!==undefined?` · ${backup.file_count} arquivos`:''}</span>{backup.cloudCopies?.map(copy=><span key={copy.id} className="mt-1 block text-xs text-[#626f86]">Google Drive · {copy.status==='success'?'salvo':copy.status==='failed'?`falhou: ${copy.error}`:'enviando'}</span>)}</div>{backup.remoteOnly&&backup.cloudCopies?.filter(copy=>copy.status==='success').map(copy=><button key={copy.id} disabled={busy} onClick={()=>void downloadConfig(copy)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Baixar do Drive</button>)}{!backup.remoteOnly&&connectionId&&<button disabled={busy} onClick={()=>void uploadConfig(backup)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Enviar ao Drive</button>}</article>):<p className="p-10 text-center text-sm text-[#626f86]">Ainda não há cópias das configurações.</p>}
    </section>
    <section className="mt-5 overflow-hidden rounded-xl border border-[#dfe1e6] bg-white shadow-sm">
      <div className="border-b border-[#dfe1e6] px-5 py-4"><h2 className="flex items-center gap-2 font-bold"><HardDrive size={18}/> Anexos dos cartões</h2><p className="mt-1 text-sm text-[#626f86]">No Drive, cada arquivo criptografado fica em Orbit DEV Card Attachments → quadro → cartão → arquivos ou comentários.</p><button disabled={busy} onClick={()=>void syncAttachments()} className="mt-3 rounded border border-[#403294] px-3 py-2 text-xs font-semibold text-[#403294] disabled:opacity-40">Verificar anexos agora</button></div>
      {attachmentBackups.length?attachmentBackups.map(backup=><article key={backup.archive} className="flex flex-wrap items-center gap-3 border-b border-[#f1f2f4] px-5 py-4 last:border-0"><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#eeedfd] text-[#403294]"><HardDrive size={17}/></span><div className="min-w-0 flex-1"><strong className="block break-all text-sm">{backup.archive}</strong><span className="mt-1 block text-xs text-[#626f86]">{backup.source_kind==='comment'?'Comentário':'Cartão'} · {backup.file_bytes!==undefined?`${(backup.file_bytes/1024).toFixed(0)} KB · `:''}{backup.created_at?new Date(backup.created_at).toLocaleString('pt-BR'):'Cópia remota'}</span>{backup.cloudCopies?.map(copy=><span key={copy.id} className="mt-1 block text-xs text-[#626f86]">Google Drive · {copy.status==='success'?'salvo':copy.status==='failed'?`falhou: ${copy.error}`:'enviando'}{copy.folderPath&&copy.folderId&&<> · <a className="text-[#0c66e4] hover:underline" href={`https://drive.google.com/drive/folders/${encodeURIComponent(copy.folderId)}`} target="_blank" rel="noopener noreferrer">{copy.folderPath}</a></>}</span>)}</div>{backup.remoteOnly&&backup.cloudCopies?.filter(copy=>copy.status==='success').map(copy=><button key={copy.id} disabled={busy} onClick={()=>void downloadAttachment(copy)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Baixar do Drive</button>)}{!backup.remoteOnly&&connectionId&&<button disabled={busy} onClick={()=>void uploadAttachment(backup)} className="rounded bg-[#e9f2ff] px-3 py-2 text-xs font-semibold text-[#0c66e4] disabled:opacity-40">Enviar ao Drive</button>}</article>):<p className="p-10 text-center text-sm text-[#626f86]">Ainda não há anexos de cartão para copiar.</p>}
    </section>
  </main></div>{confirmationModal}</div>;
}
