#!/bin/bash
# Next.js + Tailwind CSS Frontend Provisioning Script
# Creates frontend/ folder structure with configuration files
# PROMPT #51 - New Architecture Implementation (Simplified)

set -e  # Exit on error

PROJECT_NAME="$1"

if [ -z "$PROJECT_NAME" ]; then
    echo "Error: Project name required"
    echo "Usage: $0 <project-name>"
    exit 1
fi

PROJECT_PATH="/projects/$PROJECT_NAME"
FRONTEND_PATH="$PROJECT_PATH/frontend"

echo "=========================================="
echo "Next.js + Tailwind Frontend Provisioning"
echo "=========================================="
echo "Project: $PROJECT_NAME"
echo "Frontend Path: $FRONTEND_PATH"
echo ""

# Ensure project root exists
if [ ! -d "$PROJECT_PATH" ]; then
    echo "Error: Project directory not found: $PROJECT_PATH"
    exit 1
fi

# Create frontend directory structure
echo "Creating frontend directory structure..."
mkdir -p "$FRONTEND_PATH/src/app"
mkdir -p "$FRONTEND_PATH/src/components"
mkdir -p "$FRONTEND_PATH/src/lib"
mkdir -p "$FRONTEND_PATH/public"

# Create package.json
echo "Creating package.json..."
cat > "$FRONTEND_PATH/package.json" << EOF
{
  "name": "${PROJECT_NAME}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18",
    "react-dom": "^18",
    "next": "14.2.0",
    "axios": "^1.6.0",
    "swr": "^2.2.0"
  },
  "devDependencies": {
    "typescript": "^5",
    "@types/node": "^20",
    "@types/react": "^18",
    "@types/react-dom": "^18",
    "autoprefixer": "^10.0.1",
    "postcss": "^8",
    "tailwindcss": "^3.4.0",
    "eslint": "^8",
    "eslint-config-next": "14.2.0"
  }
}
EOF

# Create next.config.js
cat > "$FRONTEND_PATH/next.config.js" << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
}

module.exports = nextConfig
EOF

# Create tsconfig.json
cat > "$FRONTEND_PATH/tsconfig.json" << 'EOF'
{
  "compilerOptions": {
    "target": "es5",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

# Create Tailwind config
cat > "$FRONTEND_PATH/tailwind.config.ts" << 'EOF'
import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
    },
  },
  plugins: [],
};

export default config;
EOF

# Create PostCSS config
cat > "$FRONTEND_PATH/postcss.config.js" << 'EOF'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
EOF

# Create globals.css with Tailwind directives
mkdir -p "$FRONTEND_PATH/src/app"
cat > "$FRONTEND_PATH/src/app/globals.css" << 'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-rgb: 255, 255, 255;
}

body {
  color: rgb(var(--foreground-rgb));
  background: rgb(var(--background-rgb));
}
EOF

# Create main layout
cat > "$FRONTEND_PATH/src/app/layout.tsx" << 'EOF'
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "ORBIT Project",
  description: "Generated by ORBIT",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
EOF

# Create homepage
cat > "$FRONTEND_PATH/src/app/page.tsx" << 'EOF'
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-primary-600 mb-4">
          Welcome to ORBIT
        </h1>
        <p className="text-gray-600">
          Your project has been provisioned successfully!
        </p>
      </div>
    </main>
  );
}
EOF

# Create API client
mkdir -p "$FRONTEND_PATH/src/lib"
cat > "$FRONTEND_PATH/src/lib/api.ts" << 'EOF'
/**
 * API Client Configuration
 * Connects to Laravel backend
 */

import axios from 'axios';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

export const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request interceptor for adding auth token
apiClient.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('auth_token');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => Promise.reject(error)
);

// Response interceptor for handling errors
apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      localStorage.removeItem('auth_token');
      window.location.href = '/login';
    }
    return Promise.reject(error);
  }
);

export default apiClient;
EOF

# Create environment variables
cat > "$FRONTEND_PATH/.env.local" << 'EOF'
# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:8000/api

# App Configuration
NEXT_PUBLIC_APP_NAME=ORBIT
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

# Create .gitignore
cat > "$FRONTEND_PATH/.gitignore" << 'EOF'
# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
EOF

# Create README
cat > "$FRONTEND_PATH/README.md" << EOF
# Next.js Frontend - $PROJECT_NAME

## Tech Stack

- **Framework:** Next.js 14+ (App Router)
- **Language:** TypeScript
- **Styling:** Tailwind CSS
- **API Client:** Axios + SWR

## Setup

Dependencies will be installed automatically by Docker.

### Manual Setup (if needed)

\`\`\`bash
npm install
npm run dev
\`\`\`

## Environment

- **API URL:** http://localhost:8000/api
- **Frontend URL:** http://localhost:3000

## Features

- ✅ TypeScript
- ✅ Tailwind CSS
- ✅ API Client configured
- ✅ App Router
- ✅ ESLint

EOF

echo ""
echo "✅ Next.js + Tailwind frontend structure created successfully!"
echo ""
echo "Frontend Configuration:"
echo "  Framework: Next.js 14+ (App Router)"
echo "  Language: TypeScript"
echo "  Styling: Tailwind CSS"
echo "  API Client: Axios + SWR"
echo ""
echo "Environment:"
echo "  API URL: http://localhost:8000/api"
echo "  Frontend URL: http://localhost:3000"
echo ""
