#!/bin/bash
# Next.js + Tailwind CSS Frontend Provisioning Script
# Creates complete Next.js structure WITHOUT Docker
# PROMPT #60 - Approach 2: Manual Structure Generation

set -e  # Exit on error

PROJECT_NAME="$1"

if [ -z "$PROJECT_NAME" ]; then
    echo "Error: Project name required"
    echo "Usage: $0 <project-name>"
    exit 1
fi

PROJECT_PATH="/projects/$PROJECT_NAME"
FRONTEND_PATH="$PROJECT_PATH/frontend"

echo "=========================================="
echo "Next.js + Tailwind Frontend Provisioning"
echo "=========================================="
echo "Project: $PROJECT_NAME"
echo "Frontend Path: $FRONTEND_PATH"
echo ""

# Ensure project root exists
if [ ! -d "$PROJECT_PATH" ]; then
    echo "Error: Project directory not found: $PROJECT_PATH"
    exit 1
fi

echo "Creating Next.js directory structure..."

# Create Next.js 14 App Router structure
mkdir -p "$FRONTEND_PATH"/src/app/{api,components}
mkdir -p "$FRONTEND_PATH"/src/components/ui
mkdir -p "$FRONTEND_PATH"/src/lib
mkdir -p "$FRONTEND_PATH"/public
mkdir -p "$FRONTEND_PATH"/styles

echo "Creating Next.js configuration files..."

# Create package.json
cat > "$FRONTEND_PATH/package.json" << EOF
{
  "name": "${PROJECT_NAME}-frontend",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "next": "14.0.4",
    "axios": "^1.6.2",
    "swr": "^2.2.4"
  },
  "devDependencies": {
    "typescript": "^5.3.3",
    "@types/node": "^20.10.6",
    "@types/react": "^18.2.46",
    "@types/react-dom": "^18.2.18",
    "autoprefixer": "^10.4.16",
    "postcss": "^8.4.32",
    "tailwindcss": "^3.4.0",
    "eslint": "^8.56.0",
    "eslint-config-next": "14.0.4"
  }
}
EOF

# Create tsconfig.json
cat > "$FRONTEND_PATH/tsconfig.json" << 'EOF'
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": true,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "preserve",
    "incremental": true,
    "plugins": [
      {
        "name": "next"
      }
    ],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts"],
  "exclude": ["node_modules"]
}
EOF

# Create next.config.js
cat > "$FRONTEND_PATH/next.config.js" << 'EOF'
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  swcMinify: true,
}

module.exports = nextConfig
EOF

# Create tailwind.config.ts
cat > "$FRONTEND_PATH/tailwind.config.ts" << 'EOF'
import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
        },
      },
    },
  },
  plugins: [],
}
export default config
EOF

# Create postcss.config.js
cat > "$FRONTEND_PATH/postcss.config.js" << 'EOF'
module.exports = {
  plugins: {
    tailwindcss: {},
    autoprefixer: {},
  },
}
EOF

# Create .eslintrc.json
cat > "$FRONTEND_PATH/.eslintrc.json" << 'EOF'
{
  "extends": "next/core-web-vitals"
}
EOF

# Create src/app/layout.tsx
cat > "$FRONTEND_PATH/src/app/layout.tsx" << 'EOF'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'ORBIT Project',
  description: 'Generated by ORBIT',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
EOF

# Create src/app/page.tsx
cat > "$FRONTEND_PATH/src/app/page.tsx" << 'EOF'
export default function Home() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-center p-24">
      <div className="text-center">
        <h1 className="text-4xl font-bold text-primary-600 mb-4">
          Welcome to ORBIT
        </h1>
        <p className="text-gray-600">
          Your project has been provisioned successfully!
        </p>
        <div className="mt-8">
          <p className="text-sm text-gray-500">
            Powered by Next.js + TypeScript + Tailwind CSS
          </p>
        </div>
      </div>
    </main>
  )
}
EOF

# Create src/app/globals.css
cat > "$FRONTEND_PATH/src/app/globals.css" << 'EOF'
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
  --foreground-rgb: 0, 0, 0;
  --background-start-rgb: 214, 219, 220;
  --background-end-rgb: 255, 255, 255;
}

@media (prefers-color-scheme: dark) {
  :root {
    --foreground-rgb: 255, 255, 255;
    --background-start-rgb: 0, 0, 0;
    --background-end-rgb: 0, 0, 0;
  }
}

body {
  color: rgb(var(--foreground-rgb));
  background: linear-gradient(
      to bottom,
      transparent,
      rgb(var(--background-end-rgb))
    )
    rgb(var(--background-start-rgb));
}
EOF

# Create src/lib/api.ts
cat > "$FRONTEND_PATH/src/lib/api.ts" << 'EOF'
/**
 * API Client Configuration
 * Connects to Laravel backend
 */

import axios from 'axios';

const API_BASE_URL = process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000/api';

export const apiClient = axios.create({
  baseURL: API_BASE_URL,
  headers: {
    'Content-Type': 'application/json',
  },
});

// Request interceptor for adding auth token
apiClient.interceptors.request.use(
  (config) => {
    const token = localStorage.getItem('auth_token');
    if (token) {
      config.headers.Authorization = `Bearer ${token}`;
    }
    return config;
  },
  (error) => Promise.reject(error)
);

// Response interceptor for handling errors
apiClient.interceptors.response.use(
  (response) => response,
  (error) => {
    if (error.response?.status === 401) {
      localStorage.removeItem('auth_token');
      window.location.href = '/login';
    }
    return Promise.reject(error);
  }
);

export default apiClient;
EOF

# Create .env.local
cat > "$FRONTEND_PATH/.env.local" << 'EOF'
# API Configuration
NEXT_PUBLIC_API_URL=http://localhost:8000/api

# App Configuration
NEXT_PUBLIC_APP_NAME=ORBIT
NEXT_PUBLIC_APP_URL=http://localhost:3000
EOF

# Create .gitignore
cat > "$FRONTEND_PATH/.gitignore" << 'EOF'
# dependencies
/node_modules
/.pnp
.pnp.js

# testing
/coverage

# next.js
/.next/
/out/

# production
/build

# misc
.DS_Store
*.pem

# debug
npm-debug.log*
yarn-debug.log*
yarn-error.log*

# local env files
.env*.local

# vercel
.vercel

# typescript
*.tsbuildinfo
next-env.d.ts
EOF

# Create next-env.d.ts
cat > "$FRONTEND_PATH/next-env.d.ts" << 'EOF'
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
EOF

echo ""
echo "Installing Next.js dependencies with npm..."
echo "This may take 2-3 minutes..."
cd "$FRONTEND_PATH"
npm install --legacy-peer-deps

# Create README.md
cat > "$FRONTEND_PATH/README.md" << 'EOF'
# Next.js Frontend

This is a [Next.js](https://nextjs.org/) project bootstrapped by ORBIT.

## Getting Started

First, install dependencies (happens automatically on first `docker-compose up`):

```bash
npm install
```

Then, run the development server:

```bash
npm run dev
```

Open [http://localhost:3000](http://localhost:3000) with your browser to see the result.

## Tech Stack

- **Framework:** Next.js 14 (App Router)
- **Language:** TypeScript
- **Styling:** Tailwind CSS
- **API Client:** Axios + SWR
- **Backend:** Laravel API at http://localhost:8000/api

## Project Structure

```
frontend/
├── src/
│   ├── app/           # Next.js App Router pages
│   │   ├── layout.tsx # Root layout
│   │   ├── page.tsx   # Homepage
│   │   └── globals.css
│   ├── components/    # React components
│   └── lib/          # API client, utilities
├── public/           # Static assets
├── package.json      # Dependencies
├── tsconfig.json     # TypeScript config
├── tailwind.config.ts # Tailwind config
└── next.config.js    # Next.js config
```

## Available Scripts

- `npm run dev` - Start development server
- `npm run build` - Build for production
- `npm start` - Start production server
- `npm run lint` - Run ESLint

## Learn More

- [Next.js Documentation](https://nextjs.org/docs)
- [Tailwind CSS Documentation](https://tailwindcss.com/docs)
- [TypeScript Documentation](https://www.typescriptlang.org/docs)
EOF

echo ""
echo "✅ Next.js + Tailwind frontend provisioned successfully!"
echo ""
echo "Installation Summary:"
echo "  - Full Next.js 14 structure created"
echo "  - All npm dependencies installed (node_modules/)"
echo "  - TypeScript configuration complete"
echo "  - Tailwind CSS pre-configured"
echo "  - API client configured for Laravel backend"
echo "  - Ready to use!"
echo ""
echo "Frontend Configuration:"
echo "  Framework: Next.js 14 (App Router)"
echo "  Language: TypeScript"
echo "  Styling: Tailwind CSS"
echo "  API Client: Axios + SWR"
echo ""
echo "Environment:"
echo "  API URL: http://localhost:8000/api"
echo "  Frontend URL: http://localhost:3000"
echo ""
echo "Frontend is fully provisioned and ready!"
echo ""
