import {Body,Controller,Delete,Get,HttpException,Inject,Injectable,Param,Patch,Post,Req} from '@nestjs/common';
import {Request} from 'express';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {lstat,realpath} from 'node:fs/promises';
import {isAbsolute,relative,resolve,sep} from 'node:path';
import {Db} from '../db';
import {FeaturesService} from '../features';
import {SecretVault} from '../secrets';
import {redact} from '../execution/security';
import {PluginDefinition} from '../plugins/contract';
import {allowedBranch,branchName,branches,conventionalMessage,gitPaths} from './rules';
import {dispatchPipeline,pipelineBase,pollPipeline,PipelineTarget,Provider} from './pipeline';

const runFile=promisify(execFile);
const id=(value:unknown)=>{if(typeof value!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value))throw new HttpException('ID inválido.',400);return value};
const text=(input:unknown,name:string,max=300)=>{if(typeof input!=='string'||!input.trim()||input.length>max)throw new HttpException(`${name} inválido.`,400);return input.trim()};
const bad=(message:string,status=400):never=>{throw new HttpException(message,status)};
const safeLog=(input:string)=>redact(input).replace(/(https?:\/\/)[^/@\s]+@/gi,'$1[REDACTED]@');
const asRule=<T>(callback:()=>T):T=>{try{return callback()}catch(error){return bad((error as Error).message)}};
const stageName=(input:unknown)=>{const name=text(input,'Etapa',120);if(!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(name))bad('Etapa inválida.');return name};
const relativeRepo=(input:unknown)=>{const path=input===undefined?'.':text(input,'Pasta',500);if(isAbsolute(path)||path.includes('\\')||path.includes('\0')||path.split('/').some(part=>part==='..'||part==='.git'))bad('Pasta do repositório inválida.');return path};
const remoteName=(input:unknown)=>{const name=input===undefined?'origin':text(input,'Remote',80);if(!/^[a-zA-Z0-9][a-zA-Z0-9._-]*$/.test(name))bad('Remote inválido.');return name};
type Repo={id:string;owner_id:string;project_id:string;name:string;relative_path:string;remote_name:string;branches:string[];local_path:string};
type Target=PipelineTarget&{id:string;owner_id:string;repository_id:string;name:string;branches:string[];stages:string[];credentials_encrypted:string;active:boolean;deployment_method:string;git_flow:string};
type CardContext={project_id:string;board_id:string;list_id:string;title:string};

@Injectable()
export class GitPlugin {
  constructor(@Inject(Db) private db:Db,@Inject(FeaturesService) private features:FeaturesService,@Inject(SecretVault) private vault:SecretVault){}
  private async project(projectId:string,userId:string){const project=await this.db.one<{id:string;local_path:string}>('SELECT id,local_path FROM ai_projects WHERE id=$1 AND owner_id=$2',[id(projectId),userId]);if(!project)bad('Projeto não encontrado.',404);return project!}
  private async repository(repoId:string,userId:string){const repo=await this.db.one<Repo>('SELECT r.*,p.local_path FROM git_repositories r JOIN ai_projects p ON p.id=r.project_id WHERE r.id=$1 AND r.owner_id=$2 AND p.owner_id=$2',[id(repoId),userId]);if(!repo)bad('Repositório não encontrado.',404);return repo!}
  private async target(targetId:string,userId:string){const target=await this.db.one<Target>('SELECT t.* FROM git_pipeline_targets t JOIN git_repositories r ON r.id=t.repository_id JOIN ai_projects p ON p.id=r.project_id WHERE t.id=$1 AND t.owner_id=$2 AND p.owner_id=$2',[id(targetId),userId]);if(!target)bad('Pipeline não encontrado.',404);return target!}
  private async card(cardId:string,userId:string):Promise<CardContext>{const boardId=await this.features.cardBoard(id(cardId),userId);const card=await this.db.one<CardContext>('SELECT COALESCE(c.ai_project_id,b.ai_default_project_id) AS project_id,l.board_id,c.list_id,c.title FROM cards c JOIN lists l ON l.id=c.list_id JOIN boards b ON b.id=l.board_id WHERE c.id=$1',[cardId]);if(!card?.project_id)bad('Defina um projeto no cartão ou quadro.',409);return {...card!,board_id:boardId}}
  private async writableCard(cardId:string,userId:string){const card=await this.card(cardId,userId);await this.project(card.project_id,userId);return card}
  private async repoDir(repo:Repo){const root=await realpath(repo.local_path),dir=await realpath(resolve(root,repo.relative_path));const rel=relative(root,dir);if(rel==='..'||rel.startsWith('..'+sep)||isAbsolute(rel))bad('Repositório fora do projeto.',400);const top=(await this.git(dir,['rev-parse','--show-toplevel'])).trim();if(await realpath(top)!==dir)bad('A pasta não é a raiz do repositório Git.',400);return dir}
  private async git(dir:string,args:string[]):Promise<string>{try{const output=await runFile('git',args,{cwd:dir,timeout:60000,maxBuffer:1024*1024,env:{...process.env,GIT_TERMINAL_PROMPT:'0'}});return output.stdout}catch(error){const output=error as Error&{stderr?:string};return bad(safeLog(output.stderr||output.message).slice(0,1000),409)}}
  private async allowedRepositoryBranch(repo:Repo,branch:string){asRule(()=>allowedBranch(branch,repo.branches));const targets=await this.db.query<{branches:string[]}>('SELECT branches FROM git_pipeline_targets WHERE repository_id=$1 AND active',[repo.id]);if(targets.length&&!targets.some(target=>target.branches.includes(branch)))bad('A branch não consta em nenhum pipeline configurado.',409);return branch}
  private async currentBranch(repo:Repo,dir:string){const branch=(await this.git(dir,['branch','--show-current'])).trim();if(!branch)bad('Checkout em detached HEAD não é permitido.',409);return this.allowedRepositoryBranch(repo,branch)}
  private async explicitFiles(dir:string,paths:string[]){for(const path of paths){try{const full=resolve(dir,path),info=await lstat(full);if(info.isDirectory())bad('Selecione arquivos, não pastas.',400);const real=await realpath(full),rel=relative(dir,real);if(rel==='..'||rel.startsWith('..'+sep)||isAbsolute(rel))bad('Arquivo fora do repositório.',400)}catch(error){if((error as NodeJS.ErrnoException).code!=='ENOENT')throw error}}}
  async projectConfig(projectId:string,userId:string){await this.project(projectId,userId);const repositories=await this.db.query('SELECT id,project_id,name,relative_path,remote_name,branches,created_at FROM git_repositories WHERE project_id=$1 AND owner_id=$2 ORDER BY name',[projectId,userId]);const targets=await this.db.query('SELECT t.id,t.repository_id,t.name,t.provider,t.base_url,t.external_project,t.pipeline_ref,t.branches,t.stages,t.deployment_method,t.git_flow,t.active,t.created_at FROM git_pipeline_targets t JOIN git_repositories r ON r.id=t.repository_id WHERE r.project_id=$1 AND t.owner_id=$2 ORDER BY t.name',[projectId,userId]);const columns=await this.db.query('SELECT l.id,l.title,b.id AS board_id,b.title AS board_title FROM lists l JOIN boards b ON b.id=l.board_id WHERE b.ai_default_project_id=$1 AND b.owner_id=$2 AND l.archived_at IS NULL AND b.closed_at IS NULL ORDER BY b.title,l.position',[projectId,userId]);const mappings=await this.db.query('SELECT cs.list_id,cs.target_id,cs.stage_key FROM git_column_stages cs JOIN git_pipeline_targets t ON t.id=cs.target_id JOIN git_repositories r ON r.id=t.repository_id WHERE r.project_id=$1 AND cs.owner_id=$2',[projectId,userId]);return {repositories,targets,columns,mappings}}
  async addRepository(projectId:string,userId:string,body:Record<string,unknown>){const project=await this.project(projectId,userId),path=relativeRepo(body.relative_path),name=text(body.name,'Nome',120),remote=remoteName(body.remote_name),allowed=asRule(()=>branches(body.branches));const root=await realpath(project.local_path),dir=await realpath(resolve(root,path));const rel=relative(root,dir);if(rel==='..'||rel.startsWith('..'+sep)||isAbsolute(rel))bad('Repositório fora do projeto.');const top=(await this.git(dir,['rev-parse','--show-toplevel'])).trim();if(await realpath(top)!==dir)bad('Selecione a raiz de um repositório Git.');return this.db.one('INSERT INTO git_repositories(owner_id,project_id,name,relative_path,remote_name,branches) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,name,project_id,relative_path,remote_name,branches',[userId,projectId,name,path,remote,allowed])}
  async removeRepository(repoId:string,userId:string){await this.repository(repoId,userId);await this.db.query('DELETE FROM git_repositories WHERE id=$1 AND owner_id=$2',[repoId,userId]);return {ok:true}}
  async addTarget(repoId:string,userId:string,body:Record<string,unknown>){const repo=await this.repository(repoId,userId),name=text(body.name,'Nome',120),provider=body.provider as Provider;if(!['github_actions','gitlab_ci','bamboo'].includes(provider))bad('Provedor inválido.');const base=asRule(()=>pipelineBase(body.base_url)),project=text(body.external_project,'Projeto externo',300),ref=text(body.pipeline_ref,'Pipeline',300),allowed=asRule(()=>branches(body.branches));if(allowed.some(branch=>!repo.branches.includes(branch)))bad('O pipeline usa branch fora da configuração do repositório.');if(provider==='bamboo'&&allowed.length!==1)bad('Configure um destino Bamboo por branch do plano.');const stages=body.stages===undefined?[]:Array.isArray(body.stages)&&body.stages.length<=30?body.stages.map(stageName):bad('Etapas inválidas.');if(new Set(stages).size!==stages.length)bad('Etapas repetidas.');const token=text(body.token,'Token',5000),method=body.deployment_method??'provider',flow=body.git_flow??'pipeline_only';if(!['provider','ssh','git'].includes(String(method)))bad('Método de deploy inválido.');if(!['pipeline_only','commit_push','pull_push'].includes(String(flow)))bad('Fluxo Git inválido.');return this.db.one('INSERT INTO git_pipeline_targets(owner_id,repository_id,name,provider,base_url,external_project,pipeline_ref,branches,stages,credentials_encrypted,deployment_method,git_flow) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,repository_id,name,provider,base_url,external_project,pipeline_ref,branches,stages,deployment_method,git_flow,active',[userId,repoId,name,provider,base,project,ref,allowed,stages,this.vault.seal({token}),method,flow])}
  async removeTarget(targetId:string,userId:string){await this.target(targetId,userId);await this.db.query('DELETE FROM git_pipeline_targets WHERE id=$1 AND owner_id=$2',[targetId,userId]);return {ok:true}}
  async mapColumn(listId:string,targetId:string,userId:string,body:Record<string,unknown>){const target=await this.target(targetId,userId),repo=await this.repository(target.repository_id,userId),list=await this.db.one<{board_id:string;ai_default_project_id:string|null}>('SELECT l.board_id,b.ai_default_project_id FROM lists l JOIN boards b ON b.id=l.board_id WHERE l.id=$1 AND b.owner_id=$2 AND l.archived_at IS NULL AND b.closed_at IS NULL',[id(listId),userId]);if(!list||list.ai_default_project_id!==repo.project_id)bad('A coluna não pertence ao quadro desse projeto.',409);const stage=stageName(body.stage_key);if(!target.stages.includes(stage))bad('Etapa não configurada no pipeline.');return this.db.one('INSERT INTO git_column_stages(list_id,target_id,stage_key,owner_id) VALUES($1,$2,$3,$4) ON CONFLICT(list_id,target_id) DO UPDATE SET stage_key=$3 RETURNING list_id,target_id,stage_key',[listId,targetId,stage,userId])}
  async unmapColumn(listId:string,targetId:string,userId:string){await this.target(targetId,userId);await this.db.query('DELETE FROM git_column_stages WHERE list_id=$1 AND target_id=$2 AND owner_id=$3',[id(listId),targetId,userId]);return {ok:true}}
  async cardHistory(cardId:string,userId:string){const card=await this.card(cardId,userId);const commits=await this.db.query('SELECT gc.id,gc.sha,gc.branch,gc.title,gc.comments,gc.files,gc.merge,gc.url,gc.created_at,r.name AS repository FROM git_card_commits gc JOIN git_repositories r ON r.id=gc.repository_id WHERE gc.card_id=$1 ORDER BY gc.created_at DESC LIMIT 100',[cardId]);const repositories=await this.db.query('SELECT id,name,branches FROM git_repositories WHERE project_id=$1 ORDER BY name',[card.project_id]);const targets=await this.db.query('SELECT t.id,t.repository_id,t.name,t.provider,t.branches,t.stages,t.deployment_method,t.git_flow FROM git_pipeline_targets t JOIN git_repositories r ON r.id=t.repository_id WHERE r.project_id=$1 AND t.active ORDER BY t.name',[card.project_id]);const mappings=await this.db.query('SELECT target_id,stage_key FROM git_column_stages WHERE list_id=$1',[card.list_id]);const runs=await this.db.query('SELECT r.id,r.target_id,r.stage_key,r.branch,r.status,r.logs,r.error,r.created_at,r.updated_at,t.name AS target_name FROM git_pipeline_runs r JOIN git_pipeline_targets t ON t.id=r.target_id WHERE r.card_id=$1 ORDER BY r.created_at DESC LIMIT 30',[cardId]);const can_write=Boolean(await this.db.one('SELECT id FROM ai_projects WHERE id=$1 AND owner_id=$2',[card.project_id,userId]));return {commits,repositories,targets,mappings,runs,can_write}}
  private async commitMetadata(repo:Repo,dir:string,sha:string,branch:string){if(!/^[a-f0-9]{7,40}$/i.test(sha))bad('SHA inválido.');const parents=(await this.git(dir,['show','-s','--format=%P',sha])).trim().split(/\s+/).filter(Boolean);const subject=(await this.git(dir,['show','-s','--format=%s',sha])).trim();const comments=(await this.git(dir,['show','-s','--format=%b',sha])).trim();const files=(await this.git(dir,parents.length>1?['diff','--name-only',`${sha}^1`,sha]:['diff-tree','--no-commit-id','--name-only','-r',sha])).trim().split('\n').filter(Boolean);const remote=(await this.git(dir,['remote','get-url',repo.remote_name])).trim();let url:string|null=null;try{const parsed=new URL(remote);if(parsed.protocol==='https:'&&!parsed.username&&!parsed.password&&/^\/[\w.-]+\/[\w.-]+(?:\.git)?$/.test(parsed.pathname))url=`${parsed.origin}${parsed.pathname.replace(/\.git$/,'')}/commit/${sha}`}catch{url=null}return {subject,comments,files,merge:parents.length>1,url,branch}}
  async linkCommit(cardId:string,userId:string,body:Record<string,unknown>){const card=await this.writableCard(cardId,userId),repo=await this.repository(id(body.repository_id),userId);if(repo.project_id!==card.project_id)bad('Repositório não pertence ao projeto do cartão.',409);const dir=await this.repoDir(repo),branch=asRule(()=>branchName(body.branch));await this.allowedRepositoryBranch(repo,branch);const sha=text(body.sha,'SHA',40);await this.git(dir,['merge-base','--is-ancestor',sha,branch]);const metadata=await this.commitMetadata(repo,dir,sha,branch);return this.db.one('INSERT INTO git_card_commits(card_id,repository_id,sha,branch,title,comments,files,merge,url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT(card_id,repository_id,sha) DO UPDATE SET title=$5,comments=$6,files=$7,merge=$8,url=$9 RETURNING *',[cardId,repo.id,sha,branch,metadata.subject,metadata.comments,JSON.stringify(metadata.files),metadata.merge,metadata.url])}
  async commit(cardId:string,userId:string,body:Record<string,unknown>){const card=await this.writableCard(cardId,userId),repo=await this.repository(id(body.repository_id),userId);if(repo.project_id!==card.project_id)bad('Repositório não pertence ao projeto do cartão.',409);const dir=await this.repoDir(repo),branch=await this.currentBranch(repo,dir),paths=asRule(()=>gitPaths(body.paths));await this.explicitFiles(dir,paths);const before=(await this.git(dir,['diff','--cached','--name-only'])).trim().split('\n').filter(Boolean);if(before.some(file=>!paths.some(path=>file===path||file.startsWith(path+'/'))))bad('Há arquivos preparados fora dos caminhos selecionados.',409);await this.git(dir,['add','--',...paths]);const files=(await this.git(dir,['diff','--cached','--name-only'])).trim().split('\n').filter(Boolean);if(!files.length)bad('Nenhuma alteração para commitar.',409);const stat=await this.git(dir,['diff','--cached','--shortstat']);const message=asRule(()=>conventionalMessage(body.type,body.subject||card.title,files,stat));await this.git(dir,['commit','-m',message.subject,'-m',message.body]);const sha=(await this.git(dir,['rev-parse','HEAD'])).trim();const metadata=await this.commitMetadata(repo,dir,sha,branch);return this.db.one('INSERT INTO git_card_commits(card_id,repository_id,sha,branch,title,comments,files,merge,url) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *',[cardId,repo.id,sha,branch,metadata.subject,metadata.comments,JSON.stringify(metadata.files),metadata.merge,metadata.url])}
  async gitOperation(cardId:string,userId:string,body:Record<string,unknown>){const card=await this.writableCard(cardId,userId),repo=await this.repository(id(body.repository_id),userId);if(repo.project_id!==card.project_id)bad('Repositório não pertence ao projeto do cartão.',409);const dir=await this.repoDir(repo),branch=await this.currentBranch(repo,dir),operation=body.operation;if(operation==='add'){const paths=asRule(()=>gitPaths(body.paths));await this.explicitFiles(dir,paths);await this.git(dir,['add','--',...paths]);return {operation,branch,files:(await this.git(dir,['diff','--cached','--name-only'])).trim().split('\n').filter(Boolean)}}if(operation==='push'){const output=await this.git(dir,['push',repo.remote_name,branch]);return {operation,branch,output:safeLog(output).slice(0,4000)}}if(operation==='pull'){const dirty=(await this.git(dir,['status','--porcelain'])).trim();if(dirty)bad('A árvore de trabalho deve estar limpa para executar pull.',409);const output=await this.git(dir,['pull','--ff-only',repo.remote_name,branch]);return {operation,branch,output:safeLog(output).slice(0,4000)}}return bad('Operação Git inválida.')}
  async deploy(cardId:string,userId:string,body:Record<string,unknown>){const card=await this.writableCard(cardId,userId),target=await this.target(id(body.target_id),userId),repo=await this.repository(target.repository_id,userId);if(repo.project_id!==card.project_id)bad('Pipeline não pertence ao projeto do cartão.',409);if(!target.active)bad('Pipeline desativado.',409);const branch=asRule(()=>branchName(body.branch));asRule(()=>allowedBranch(branch,repo.branches,target.branches));const mapping=await this.db.one<{stage_key:string}>('SELECT stage_key FROM git_column_stages WHERE list_id=$1 AND target_id=$2',[card.list_id,target.id]);const stage=body.stage_key===undefined?mapping?.stage_key:stageName(body.stage_key);if(stage&&!target.stages.includes(stage))bad('Etapa não configurada no pipeline.');const row=await this.db.one<{id:string}>('INSERT INTO git_pipeline_runs(target_id,card_id,stage_key,branch,status) VALUES($1,$2,$3,$4,$5) RETURNING id',[target.id,cardId,stage||null,branch,'queued']);try{let localLog='';if(target.git_flow!=='pipeline_only'){const dir=await this.repoDir(repo),actual=await this.currentBranch(repo,dir);if(actual!==branch)bad('A branch local deve corresponder à branch do pipeline.',409);if(target.git_flow==='commit_push'){const created=await this.commit(cardId,userId,{repository_id:repo.id,type:body.type??'chore',subject:body.subject??card.title,paths:body.paths});localLog=`Commit ${String((created as {sha:string}|null)?.sha||'')} criado e enviado.\n`;await this.gitOperation(cardId,userId,{repository_id:repo.id,operation:'push'})}else if(target.git_flow==='pull_push'){await this.gitOperation(cardId,userId,{repository_id:repo.id,operation:'pull'});await this.gitOperation(cardId,userId,{repository_id:repo.id,operation:'push'});localLog='Pull e push concluídos.\n'}}const token=this.vault.open<{token:string}>(target.credentials_encrypted).token;const result=await dispatchPipeline(target,branch,token,stage);await this.db.query('UPDATE git_pipeline_runs SET external_run_id=$2,status=$3,logs=$4,updated_at=now() WHERE id=$1',[row!.id,result.externalId,result.status,redact(localLog+result.logs).split(token).join('[REDACTED]')]);return this.runDetail(row!.id,userId)}catch(error){await this.db.query('UPDATE git_pipeline_runs SET status=$2,error=$3,updated_at=now() WHERE id=$1',[row!.id,'failed',redact((error as Error).message).slice(0,2000)]);throw error}}
  async runDetail(runId:string,userId:string){const row=await this.db.one<{id:string;target_id:string;external_run_id:string|null;branch:string;status:string;stage_key:string|null;logs:string;error:string|null;provider:Provider;base_url:string;external_project:string;pipeline_ref:string;credentials_encrypted:string}>('SELECT r.*,t.provider,t.base_url,t.external_project,t.pipeline_ref,t.credentials_encrypted FROM git_pipeline_runs r JOIN git_pipeline_targets t ON t.id=r.target_id WHERE r.id=$1 AND t.owner_id=$2',[id(runId),userId]);if(!row)bad('Execução não encontrada.',404);return {id:row!.id,target_id:row!.target_id,branch:row!.branch,stage_key:row!.stage_key,status:row!.status,logs:row!.logs,error:row!.error}}
  async refreshRun(runId:string,userId:string){const run=await this.db.one<{id:string;target_id:string;external_run_id:string|null;branch:string;status:string}>('SELECT r.id,r.target_id,r.external_run_id,r.branch,r.status FROM git_pipeline_runs r JOIN git_pipeline_targets t ON t.id=r.target_id WHERE r.id=$1 AND t.owner_id=$2',[id(runId),userId]);if(!run)bad('Execução não encontrada.',404);if(run!.status==='success'||run!.status==='failed')return this.runDetail(runId,userId);const target=await this.target(run!.target_id,userId);try{const token=this.vault.open<{token:string}>(target.credentials_encrypted).token;const result=await pollPipeline(target,run!.external_run_id,run!.branch,token);await this.db.query('UPDATE git_pipeline_runs SET external_run_id=COALESCE($2,external_run_id),status=$3,logs=$4,updated_at=now() WHERE id=$1',[runId,result.externalId,result.status,redact(result.logs).split(token).join('[REDACTED]')]);return this.runDetail(runId,userId)}catch(error){await this.db.query('UPDATE git_pipeline_runs SET error=$2,updated_at=now() WHERE id=$1',[runId,redact((error as Error).message).slice(0,2000)]);return this.runDetail(runId,userId)}}
}

export const gitPluginDefinition=(git:GitPlugin):PluginDefinition=>({
  id:'git',name:'Git',version:'1.0.0',scope:'account',
  capabilities:[
    {id:'history.read',name:'Ler histórico Git',permissions:['repository.read']},
    {id:'commit.write',name:'Criar commits',permissions:['repository.write']},
    {id:'pipeline.run',name:'Executar pipelines',permissions:['process.execute']},
  ],
  actions:[
    {id:'history',name:'Consultar commits do card',requiredCapabilities:['history.read'],inputSchema:{type:'object',properties:{},additionalProperties:false},async execute(_input,context){if(!context.userId||!context.cardId)throw new Error('Card e usuário obrigatórios.');return {type:'git',label:'Histórico Git',value:await git.cardHistory(context.cardId,context.userId)}}},
    {id:'commit',name:'Criar commit Conventional Commits',requiredCapabilities:['commit.write'],inputSchema:{type:'object',required:['repository_id','type','paths'],properties:{repository_id:{type:'string'},type:{enum:['feat','fix','chore']},subject:{type:'string'},paths:{type:'array',items:{type:'string'},minItems:1}},additionalProperties:false},async execute(input,context){if(!context.userId||!context.cardId)throw new Error('Card e usuário obrigatórios.');return {type:'git',label:'Commit criado',value:await git.commit(context.cardId,context.userId,input)}}},
    {id:'operation',name:'Executar add, push ou pull',requiredCapabilities:['commit.write'],inputSchema:{type:'object',required:['repository_id','operation'],properties:{repository_id:{type:'string'},operation:{enum:['add','push','pull']},paths:{type:'array',items:{type:'string'}}},additionalProperties:false},async execute(input,context){if(!context.userId||!context.cardId)throw new Error('Card e usuário obrigatórios.');return {type:'git',label:'Operação Git',value:await git.gitOperation(context.cardId,context.userId,input)}}},
    {id:'deploy',name:'Executar pipeline do projeto',requiredCapabilities:['pipeline.run'],inputSchema:{type:'object',required:['target_id','branch'],properties:{target_id:{type:'string'},branch:{type:'string'},paths:{type:'array',items:{type:'string'}},type:{enum:['feat','fix','chore']},subject:{type:'string'}},additionalProperties:false},async execute(input,context){if(!context.userId||!context.cardId)throw new Error('Card e usuário obrigatórios.');return {type:'git',label:'Pipeline disparado',value:await git.deploy(context.cardId,context.userId,input)}}},
  ],
  contributions:{settings:[{id:'git',label:'Git e deploy',href:'/profile?tab=projects'}],resourceRenderers:[{resourceTypes:['commit','pipeline_run'],component:'git-resource'}]},
});

@Controller('git')
export class GitController {
  constructor(@Inject(GitPlugin) private gitPlugin:GitPlugin,@Inject(FeaturesService) private features:FeaturesService){}
  private user(req:Request){return this.features.user(req)}
  @Get('projects/:id') project(@Req() req:Request,@Param('id') projectId:string){return this.gitPlugin.projectConfig(projectId,this.user(req))}
  @Post('projects/:id/repositories') addRepository(@Req() req:Request,@Param('id') projectId:string,@Body() body:Record<string,unknown>){return this.gitPlugin.addRepository(projectId,this.user(req),body)}
  @Delete('repositories/:id') removeRepository(@Req() req:Request,@Param('id') repoId:string){return this.gitPlugin.removeRepository(repoId,this.user(req))}
  @Post('repositories/:id/targets') addTarget(@Req() req:Request,@Param('id') repoId:string,@Body() body:Record<string,unknown>){return this.gitPlugin.addTarget(repoId,this.user(req),body)}
  @Delete('targets/:id') removeTarget(@Req() req:Request,@Param('id') targetId:string){return this.gitPlugin.removeTarget(targetId,this.user(req))}
  @Patch('columns/:listId/stages/:targetId') mapColumn(@Req() req:Request,@Param('listId') listId:string,@Param('targetId') targetId:string,@Body() body:Record<string,unknown>){return this.gitPlugin.mapColumn(listId,targetId,this.user(req),body)}
  @Delete('columns/:listId/stages/:targetId') unmapColumn(@Req() req:Request,@Param('listId') listId:string,@Param('targetId') targetId:string){return this.gitPlugin.unmapColumn(listId,targetId,this.user(req))}
  @Get('cards/:id') card(@Req() req:Request,@Param('id') cardId:string){return this.gitPlugin.cardHistory(cardId,this.user(req))}
  @Post('cards/:id/commits') commit(@Req() req:Request,@Param('id') cardId:string,@Body() body:Record<string,unknown>){return this.gitPlugin.commit(cardId,this.user(req),body)}
  @Post('cards/:id/link-commit') linkCommit(@Req() req:Request,@Param('id') cardId:string,@Body() body:Record<string,unknown>){return this.gitPlugin.linkCommit(cardId,this.user(req),body)}
  @Post('cards/:id/operations') operation(@Req() req:Request,@Param('id') cardId:string,@Body() body:Record<string,unknown>){return this.gitPlugin.gitOperation(cardId,this.user(req),body)}
  @Post('cards/:id/deploys') deploy(@Req() req:Request,@Param('id') cardId:string,@Body() body:Record<string,unknown>){return this.gitPlugin.deploy(cardId,this.user(req),body)}
  @Get('runs/:id') run(@Req() req:Request,@Param('id') runId:string){return this.gitPlugin.runDetail(runId,this.user(req))}
  @Post('runs/:id/refresh') refresh(@Req() req:Request,@Param('id') runId:string){return this.gitPlugin.refreshRun(runId,this.user(req))}
}
