/**
 * TaskCard Component for Kanban
 * PROMPT #82 - Display item type (Epic, Story, Task, etc.)
 * Simpler version for Kanban board display
 */

'use client';

import React from 'react';
import { Task, ItemType } from '@/lib/types';
import { Badge, AIModelBadge } from '@/components/ui';
import { IconTarget, IconBook, IconCheck, IconCircle, IconBug, IconDot, IconArrowLeft, IconArrowRight } from '@/components/icons'; // PROMPT #188

interface Props {
  task: Task;
  onDeleted: () => void;
  onUpdated: () => void;
  canMoveLeft?: boolean;
  canMoveRight?: boolean;
  onMoveLeft?: () => void;
  onMoveRight?: () => void;
}

// Helper function to get item type icon and label - PROMPT #188
const getItemTypeDisplay = (type: ItemType | undefined) => {
  switch (type) {
    case ItemType.EPIC:
      return { icon: <IconTarget className="w-5 h-5" />, label: 'Epic', color: 'bg-purple-100 text-purple-800 border-purple-200' };
    case ItemType.STORY:
      return { icon: <IconBook className="w-5 h-5" />, label: 'Story', color: 'bg-blue-100 text-blue-800 border-blue-200' };
    case ItemType.TASK:
      return { icon: <IconCheck className="w-5 h-5" />, label: 'Task', color: 'bg-gray-100 text-gray-800 border-gray-200' };
    case ItemType.SUBTASK:
      return { icon: <IconCircle className="w-5 h-5" />, label: 'Subtask', color: 'bg-gray-50 text-gray-700 border-gray-200' };
    case ItemType.BUG:
      return { icon: <IconBug className="w-5 h-5" />, label: 'Bug', color: 'bg-red-100 text-red-800 border-red-200' };
    default:
      return { icon: <IconDot className="w-3 h-3" />, label: 'Task', color: 'bg-gray-100 text-gray-800 border-gray-200' };
  }
};

export function TaskCard({ 
  task, 
  canMoveLeft, 
  canMoveRight, 
  onMoveLeft, 
  onMoveRight 
}: Props) {
  const itemTypeDisplay = getItemTypeDisplay(task.item_type);

  return (
    <div className="bg-white rounded-lg shadow-sm p-4 hover:shadow-md transition-shadow border border-gray-200">
      {/* Header with Item Type Badge */}
      <div className="flex items-start justify-between gap-2 mb-2">
        <div className="flex items-center gap-2">
          <span className="text-gray-600">{itemTypeDisplay.icon}</span>
          <Badge className={`${itemTypeDisplay.color} text-xs font-semibold border`}>
            {itemTypeDisplay.label}
          </Badge>
        </div>

        {/* Navigation buttons */}
        <div className="flex gap-1">
          {canMoveLeft && onMoveLeft && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onMoveLeft();
              }}
              className="text-gray-400 hover:text-gray-600 p-1"
              title="Move left"
            >
              <IconArrowLeft className="w-4 h-4" />
            </button>
          )}
          {canMoveRight && onMoveRight && (
            <button
              onClick={(e) => {
                e.stopPropagation();
                onMoveRight();
              }}
              className="text-gray-400 hover:text-gray-600 p-1"
              title="Move right"
            >
              <IconArrowRight className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      {/* Title */}
      <h4 className="font-semibold text-gray-900 text-sm line-clamp-2 mb-2">
        {task.title}
      </h4>

      {/* Description */}
      {task.description && (
        <p className="text-xs text-gray-600 line-clamp-3">
          {task.description}
        </p>
      )}

      {/* PROMPT #127 - Show AI model icon if content was generated by AI */}
      {task.created_by_ai_model && (
        <div className="mt-2 flex justify-end">
          <AIModelBadge model={task.created_by_ai_model} usage_type="prompt_generation" />
        </div>
      )}
    </div>
  );
}
