'use client';

import { FormEvent, useCallback, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Bookmark, Search, SlidersHorizontal, Star, Trash2 } from 'lucide-react';
import { AdvancedSearchCard, api, Board, getToken, SavedSearch, send } from '@/lib/api';
import { AppHeader } from '@/components/ui';

type Filters = Record<'q'|'board_id'|'list_id'|'label_id'|'status'|'archived'|'due'|'comments'|'checklist'|'sort',string>;
const blank:Filters={q:'',board_id:'',list_id:'',label_id:'',status:'',archived:'',due:'',comments:'',checklist:'',sort:'updated'};

export default function SearchPage(){
  const router=useRouter();
  const [boards,setBoards]=useState<Board[]>([]),[cards,setCards]=useState<AdvancedSearchCard[]>([]),[saved,setSaved]=useState<SavedSearch[]>([]),[filters,setFilters]=useState<Filters>(blank);
  const [loading,setLoading]=useState(false),[error,setError]=useState(''),[saveName,setSaveName]=useState('');
  const load=useCallback(async(current:Filters)=>{setLoading(true);try{const query=new URLSearchParams(Object.entries(current).filter(([,value])=>value));const data=await api<{cards:AdvancedSearchCard[]}>(`/search/advanced?${query}`);setCards(data.cards);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
  // The initial URL query is intentionally loaded once; later searches run from the form.
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{const timer=window.setTimeout(()=>{if(!getToken()){router.push('/');return;}const initial={...filters,q:new URLSearchParams(window.location.search).get('q')||filters.q};setFilters(initial);Promise.all([api<Board[]>('/boards'),api<SavedSearch[]>('/saved-searches')]).then(([b,s])=>{setBoards(b);setSaved(s);}).catch(e=>setError((e as Error).message));void load(initial);},0);return()=>window.clearTimeout(timer);},[load,router]);
  const update=(key:keyof Filters,value:string)=>setFilters(old=>({...old,[key]:value}));
  async function submit(e:FormEvent){e.preventDefault();await load(filters);router.replace(`/search?${new URLSearchParams(Object.entries(filters).filter(([,v])=>v))}`)}
  async function save(){if(!saveName.trim())return;try{const item=await send<SavedSearch>('/saved-searches','POST',{name:saveName,query:filters});setSaved(old=>[item,...old]);setSaveName('')}catch(e){setError((e as Error).message)}}
  const lists=boards.find(board=>board.id===filters.board_id)?.lists||[];
  const labels=boards.find(board=>board.id===filters.board_id)?.labels||[];
  return <div className="min-h-screen bg-[#f7f8fa]"><AppHeader user={null} boards={boards}/><main className="mx-auto grid max-w-7xl gap-6 p-4 sm:p-6 lg:grid-cols-[280px_1fr]"><aside className="rounded-xl border border-[#dfe1e6] bg-white p-4 shadow-sm"><h1 className="flex items-center gap-2 text-lg font-bold"><SlidersHorizontal size={19}/> Busca avançada</h1><form onSubmit={submit} className="mt-4 space-y-3"><input autoFocus value={filters.q} onChange={e=>update('q',e.target.value)} placeholder="Título, descrição, comentário ou checklist" className="w-full rounded border border-[#8590a2] px-3 py-2 text-sm"/>
    <select value={filters.board_id} onChange={e=>{update('board_id',e.target.value);update('list_id','');update('label_id','')}} className="w-full rounded border p-2 text-sm"><option value="">Todos os quadros</option>{boards.map(b=><option key={b.id} value={b.id}>{b.title}{b.starred?' ★':''}</option>)}</select>
    <select value={filters.list_id} onChange={e=>update('list_id',e.target.value)} disabled={!filters.board_id} className="w-full rounded border p-2 text-sm"><option value="">Todas as listas</option>{lists.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select>
    <select value={filters.label_id} onChange={e=>update('label_id',e.target.value)} disabled={!filters.board_id} className="w-full rounded border p-2 text-sm"><option value="">Todas as etiquetas</option>{labels.map(l=><option key={l.id} value={l.id}>{l.name||'Sem nome'}</option>)}</select>
    <div className="grid grid-cols-2 gap-2"><select value={filters.status} onChange={e=>update('status',e.target.value)} className="rounded border p-2 text-sm"><option value="">Qualquer status</option><option value="open">Pendentes</option><option value="completed">Concluídos</option></select><select value={filters.due} onChange={e=>update('due',e.target.value)} className="rounded border p-2 text-sm"><option value="">Qualquer prazo</option><option value="overdue">Vencidos</option><option value="week">Próx. 7 dias</option><option value="none">Sem prazo</option></select></div>
    <div className="grid grid-cols-2 gap-2"><select value={filters.comments} onChange={e=>update('comments',e.target.value)} className="rounded border p-2 text-sm"><option value="">Comentários</option><option value="yes">Com comentários</option></select><select value={filters.checklist} onChange={e=>update('checklist',e.target.value)} className="rounded border p-2 text-sm"><option value="">Checklists</option><option value="yes">Com checklist</option></select></div>
    <select value={filters.archived} onChange={e=>update('archived',e.target.value)} className="w-full rounded border p-2 text-sm"><option value="">Ativos</option><option value="all">Ativos e arquivados</option><option value="only">Só arquivados</option></select><select value={filters.sort} onChange={e=>update('sort',e.target.value)} className="w-full rounded border p-2 text-sm"><option value="updated">Atualizados recentemente</option><option value="due">Prazo</option><option value="created">Criação</option></select>
    <button className="flex w-full items-center justify-center gap-2 rounded bg-[#0c66e4] px-3 py-2 text-sm font-semibold text-white"><Search size={16}/> Pesquisar</button></form>
    <div className="mt-6 border-t pt-4"><p className="mb-2 flex items-center gap-1 text-sm font-bold"><Bookmark size={16}/> Pesquisas salvas</p><div className="flex gap-2"><input value={saveName} onChange={e=>setSaveName(e.target.value)} placeholder="Nome da pesquisa" className="min-w-0 flex-1 rounded border px-2 py-1.5 text-xs"/><button onClick={save} className="rounded bg-[#dfe1e6] px-2 text-xs font-semibold">Salvar</button></div><div className="mt-2 space-y-1">{saved.map(item=><div key={item.id} className="flex items-center gap-1"><button onClick={()=>{const next={...blank,...item.query};setFilters(next);void load(next)}} className="min-w-0 flex-1 truncate rounded px-2 py-1 text-left text-xs hover:bg-[#f1f2f4]">{item.name}</button><button onClick={async()=>{await send(`/saved-searches/${item.id}`,'DELETE');setSaved(old=>old.filter(x=>x.id!==item.id))}} title="Excluir pesquisa"><Trash2 size={14}/></button></div>)}</div></div></aside>
  <section><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-bold">Resultados</h2><p className="text-sm text-[#626f86]">{loading?'Pesquisando...':`${cards.length} cartões encontrados`}</p></div><button onClick={()=>{const next={...blank};setFilters(next);void load(next)}} className="text-sm font-semibold text-[#0c66e4]">Limpar filtros</button></div>{error&&<p role="alert" className="mb-3 rounded bg-[#ffebe6] p-3 text-sm text-[#ae2a19]">{error}</p>}<div className="space-y-2">{!loading&&cards.length===0?<div className="rounded-xl border border-dashed border-[#c1c7d0] bg-white p-10 text-center text-sm text-[#626f86]">Nenhum cartão corresponde aos filtros.</div>:cards.map(card=><button key={card.id} onClick={()=>router.push(`/board/${card.board_id}?card=${card.id}`)} className="w-full rounded-xl border border-[#dfe1e6] bg-white p-4 text-left shadow-sm hover:border-[#388bff]"><div className="flex items-start gap-3"><span className="mt-1 h-8 w-2 rounded" style={{background:boards.find(b=>b.id===card.board_id)?.background||'#579dff'}}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><strong>{card.title}</strong>{card.completed&&<span className="rounded bg-[#baf3db] px-1.5 py-0.5 text-[10px] font-bold text-[#216e4e]">Concluído</span>}{boards.find(b=>b.id===card.board_id)?.starred&&<Star size={14} className="text-[#e2b203]" fill="currentColor"/>}</div><p className="mt-1 truncate text-sm text-[#626f86]">{card.board_title} · {card.list_title}</p>{card.description&&<p className="mt-2 line-clamp-2 text-sm text-[#44546f]">{card.description}</p>}<div className="mt-2 flex flex-wrap gap-1">{card.labels.map(label=><span key={label.id} className="rounded px-2 py-0.5 text-[10px] font-semibold" style={{background:label.color}}>{label.name}</span>)}</div></div>{card.due_date&&<span className="text-xs text-[#626f86]">{new Date(card.due_date).toLocaleDateString('pt-BR')}</span>}</div></button>)}</div></section></main></div>;
}
