"""add task execution fields and task_results table

Revision ID: 1838e26713b5
Revises: 73d44285fba8
Create Date: 2025-12-27 19:57:38.555864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1838e26713b5'
down_revision: Union[str, None] = '73d44285fba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ai_models_name_key'), 'ai_models', type_='unique')
    op.drop_constraint(op.f('system_settings_key_key'), 'system_settings', type_='unique')
    op.add_column('tasks', sa.Column('type', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('entity', sa.String(length=100), nullable=True))
    op.add_column('tasks', sa.Column('file_path', sa.String(length=500), nullable=True))
    op.add_column('tasks', sa.Column('complexity', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('tasks', sa.Column('depends_on', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'depends_on')
    op.drop_column('tasks', 'complexity')
    op.drop_column('tasks', 'file_path')
    op.drop_column('tasks', 'entity')
    op.drop_column('tasks', 'type')
    op.create_unique_constraint(op.f('system_settings_key_key'), 'system_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('ai_models_name_key'), 'ai_models', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
