"""add consistency_issues table

Revision ID: a59bd071c62f
Revises: 250541e1bafc
Create Date: 2025-12-27 23:58:18.482631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a59bd071c62f'
down_revision: Union[str, None] = '250541e1bafc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create consistency_issues table
    op.create_table('consistency_issues',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), nullable=False),
    sa.Column('status', sa.VARCHAR(length=30), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('task_ids', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('file_paths', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('line_numbers', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('auto_fixable', sa.BOOLEAN(), nullable=True),
    sa.Column('fix_applied', sa.TEXT(), nullable=True),
    sa.Column('fix_suggestion', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=True),
    sa.Column('fixed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_consistency_issues_id'), 'consistency_issues', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_consistency_issues_id'), table_name='consistency_issues')
    op.drop_table('consistency_issues')
    # ### end Alembic commands ###
