"""add project_analyses table

Revision ID: b3f8e4a21d9c
Revises: a59bd071c62f
Create Date: 2025-12-27 21:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3f8e4a21d9c'
down_revision: Union[str, None] = 'a59bd071c62f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create project_analyses table
    op.create_table('project_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_size_bytes', sa.INTEGER(), nullable=False),
    sa.Column('upload_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('extraction_path', sa.VARCHAR(length=500), nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.Column('detected_stack', sa.VARCHAR(length=100), nullable=True),
    sa.Column('confidence_score', sa.INTEGER(), nullable=True),
    sa.Column('file_structure', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('conventions', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('patterns', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('dependencies', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('orchestrator_generated', sa.BOOLEAN(), nullable=False),
    sa.Column('orchestrator_key', sa.VARCHAR(length=100), nullable=True),
    sa.Column('orchestrator_code', sa.TEXT(), nullable=True),
    sa.Column('error_message', sa.TEXT(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('orchestrator_key')
    )
    op.create_index(op.f('ix_project_analyses_id'), 'project_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_project_analyses_orchestrator_key'), 'project_analyses', ['orchestrator_key'], unique=True)
    op.create_index(op.f('ix_project_analyses_project_id'), 'project_analyses', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_analyses_status'), 'project_analyses', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_analyses_status'), table_name='project_analyses')
    op.drop_index(op.f('ix_project_analyses_project_id'), table_name='project_analyses')
    op.drop_index(op.f('ix_project_analyses_orchestrator_key'), table_name='project_analyses')
    op.drop_index(op.f('ix_project_analyses_id'), table_name='project_analyses')
    op.drop_table('project_analyses')
    # ### end Alembic commands ###
