import {Inject,Injectable} from '@nestjs/common';
import {PoolClient} from 'pg';
import {Db} from '../db';
import {branchName} from '../git/rules';
import {StepHandlerRegistry,Step} from './contracts';
import {DeliveryCredentialService,SshCommandExecutor} from './executors';

export const uid=(value:unknown)=>{if(typeof value!=='string'||!/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(value))throw new Error('ID inválido.');return value};
export const txt=(value:unknown,label:string,max=300)=>{if(typeof value!=='string'||!value.trim()||value.length>max)throw new Error(`${label} inválido.`);return value.trim()};
export const record=(value:unknown):Record<string,unknown>=>{if(!value||typeof value!=='object'||Array.isArray(value))throw new Error('Objeto inválido.');return value as Record<string,unknown>};
export function gitRemoteUrl(value:unknown){
  const url=txt(value,'URL',1000);
  if(/^[A-Za-z0-9._-]+@[A-Za-z0-9._-]+:[A-Za-z0-9._/~+-]+$/.test(url))return url;
  try{
    const parsed=new URL(url);
    if(!['https:','ssh:'].includes(parsed.protocol)||!parsed.hostname||!parsed.pathname||parsed.pathname==='/'||parsed.password||parsed.search||parsed.hash||parsed.protocol==='https:'&&parsed.username)throw new Error('invalid');
    return url;
  }catch{throw new Error('URL Git deve ser HTTPS ou SSH sem segredo embutido.')}
}
export function noInlineSecrets(value:unknown){
  if(typeof value==='string'){if(/-----BEGIN .*PRIVATE KEY-----|\b(?:ghp_|sk-)[A-Za-z0-9_-]{15,}|\bBearer\s+[A-Za-z0-9._-]{10,}/.test(value))throw new Error('Segredo literal não permitido.');return}
  if(!value||typeof value!=='object')return;
  for(const [key,item] of Object.entries(value)){if(/(?:password|secret|token|privateKey|authorization)/i.test(key)&&!key.endsWith('Id'))throw new Error('Use credentialId em vez de segredo literal.');noInlineSecrets(item)}
}

@Injectable()
export class DeliveryManagement {
  constructor(@Inject(Db) private db:Db,@Inject(StepHandlerRegistry) private handlers:StepHandlerRegistry,@Inject(DeliveryCredentialService) private credentials:DeliveryCredentialService,@Inject(SshCommandExecutor) private ssh:SshCommandExecutor){}
  async project(projectId:string,userId:string){const row=await this.db.one<{id:string;local_path:string}>('SELECT id,local_path FROM ai_projects WHERE id=$1 AND owner_id=$2',[uid(projectId),userId]);if(!row)throw new Error('Projeto não autorizado.');return row}
  async pipeline(pipelineId:string,userId:string){const row=await this.db.one<{id:string;project_id:string;enabled:boolean;trigger_type:string;execution_policy:Record<string,unknown>;owner_id:string}>('SELECT d.* FROM delivery_pipelines d JOIN ai_projects p ON p.id=d.project_id WHERE d.id=$1 AND d.owner_id=$2 AND p.owner_id=$2',[uid(pipelineId),userId]);if(!row)throw new Error('Pipeline não autorizado.');return row}
  async canBypass(userId:string){return Boolean(await this.db.one('SELECT 1 FROM delivery_permissions WHERE owner_id=$1 AND user_id=$1 AND permission=$2',[userId,'pipeline.bypass']))}
  async setBypass(userId:string,enabled:boolean){if(enabled)await this.db.query('INSERT INTO delivery_permissions(owner_id,user_id,permission) VALUES($1,$1,$2) ON CONFLICT DO NOTHING',[userId,'pipeline.bypass']);else await this.db.query('DELETE FROM delivery_permissions WHERE owner_id=$1 AND user_id=$1 AND permission=$2',[userId,'pipeline.bypass']);await this.db.query('INSERT INTO delivery_audit(actor_id,event,details) VALUES($1,$2,$3::jsonb)',[userId,enabled?'permission.granted':'permission.revoked',JSON.stringify({permission:'pipeline.bypass'})]);return {enabled}}
  async catalog(userId:string){return {stepTypes:this.handlers.catalog(),executors:['local','ssh'],bypassEnabled:await this.canBypass(userId)}}
  async config(projectId:string,userId:string){await this.project(projectId,userId);const [credentials,servers,remotes,environments,targets,pipelines]=await Promise.all([
    this.credentials.list(userId),
    this.db.query('SELECT id,workspace_id,name,host,port,username,credential_id,host_fingerprint FROM delivery_servers WHERE owner_id=$1 ORDER BY name',[userId]),
    this.db.query('SELECT r.id,r.repository_id,r.name,r.url,r.provider,r.credential_id,r.default_branch FROM delivery_git_remotes r JOIN git_repositories g ON g.id=r.repository_id WHERE g.project_id=$1 AND g.owner_id=$2 ORDER BY r.name',[projectId,userId]),
    this.db.query('SELECT * FROM delivery_environments WHERE project_id=$1 ORDER BY name',[projectId]),
    this.db.query('SELECT * FROM delivery_targets WHERE project_id=$1 ORDER BY name',[projectId]),
    this.db.query('SELECT id,project_id,name,description,trigger_type,enabled,execution_policy,created_at FROM delivery_pipelines WHERE project_id=$1 AND owner_id=$2 ORDER BY created_at DESC',[projectId,userId])
  ]);return {credentials,servers,remotes,environments,targets,pipelines}}
  async credential(userId:string,body:Record<string,unknown>){return this.credentials.create(userId,{name:txt(body.name,'Nome',120),kind:txt(body.kind,'Tipo',24),value:txt(body.value,'Segredo',20000)})}
  async server(userId:string,body:Record<string,unknown>){const credentialId=uid(body.credentialId);await this.credentials.secret(credentialId,userId,['SSH_PRIVATE_KEY','SSH_PASSWORD']);const host=txt(body.host,'Host',255);if(!/^[A-Za-z0-9][A-Za-z0-9.:-]*$/.test(host))throw new Error('Host inválido.');const port=body.port===undefined?22:Number(body.port);if(!Number.isInteger(port)||port<1||port>65535)throw new Error('Porta inválida.');const fingerprint=txt(body.fingerprint,'Fingerprint',64);if(!/^[a-f0-9]{64}$/i.test(fingerprint))throw new Error('Fingerprint SHA-256 inválido.');const workspaceId=body.workspaceId?uid(body.workspaceId):null;if(workspaceId&&!await this.db.one('SELECT id FROM workspaces WHERE id=$1 AND owner_id=$2',[workspaceId,userId]))throw new Error('Workspace não autorizado.');return this.db.one('INSERT INTO delivery_servers(owner_id,workspace_id,name,host,port,username,credential_id,host_fingerprint) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING id,workspace_id,name,host,port,username,credential_id,host_fingerprint',[userId,workspaceId,txt(body.name,'Nome',120),host,port,txt(body.username,'Usuário',120),credentialId,fingerprint])}
  async testServer(userId:string,serverId:string){return this.ssh.test(uid(serverId),userId)}
  async remote(userId:string,repositoryId:string,body:Record<string,unknown>){const repo=await this.db.one<{project_id:string;branches:string[]}>('SELECT r.project_id,r.branches FROM git_repositories r JOIN ai_projects p ON p.id=r.project_id WHERE r.id=$1 AND r.owner_id=$2 AND p.owner_id=$2',[uid(repositoryId),userId]);if(!repo)throw new Error('Repositório não autorizado.');const name=txt(body.name,'Remote',80);if(!/^[A-Za-z0-9][A-Za-z0-9._-]*$/.test(name))throw new Error('Remote inválido.');const url=gitRemoteUrl(body.url);const credentialId=body.credentialId?uid(body.credentialId):null;if(credentialId)await this.credentials.secret(credentialId,userId,['GIT_TOKEN','GIT_SSH_KEY']);const defaultBranch=body.defaultBranch?branchName(body.defaultBranch):null;if(defaultBranch&&!repo.branches.includes(defaultBranch))throw new Error('Branch fora da configuração do repositório.');return this.db.one('INSERT INTO delivery_git_remotes(repository_id,name,url,provider,credential_id,default_branch) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,repository_id,name,url,provider,credential_id,default_branch',[repositoryId,name,url,body.provider?txt(body.provider,'Provedor',40):null,credentialId,defaultBranch])}
  async environment(userId:string,projectId:string,body:Record<string,unknown>){await this.project(projectId,userId);const slug=txt(body.slug,'Slug',80);if(!/^[a-z][a-z0-9-]*$/.test(slug))throw new Error('Slug inválido.');return this.db.one('INSERT INTO delivery_environments(project_id,name,slug,description) VALUES($1,$2,$3,$4) RETURNING *',[projectId,txt(body.name,'Nome',120),slug,typeof body.description==='string'?body.description.slice(0,2000):''])}
  async target(userId:string,projectId:string,body:Record<string,unknown>){await this.project(projectId,userId);const environmentId=uid(body.environmentId),repoId=body.repositoryId?uid(body.repositoryId):null,remoteId=body.remoteId?uid(body.remoteId):null,serverId=body.serverId?uid(body.serverId):null;const env=await this.db.one('SELECT 1 FROM delivery_environments WHERE id=$1 AND project_id=$2',[environmentId,projectId]);if(!env)throw new Error('Environment não pertence ao projeto.');const executor=txt(body.executor,'Executor',40);if(!['local','ssh'].includes(executor)||executor==='ssh'&&!serverId)throw new Error('Executor inválido.');if(serverId)await this.ssh.server(serverId,userId);if(repoId&&!await this.db.one('SELECT 1 FROM git_repositories WHERE id=$1 AND project_id=$2 AND owner_id=$3',[repoId,projectId,userId]))throw new Error('Repositório não autorizado.');if(remoteId&&!await this.db.one('SELECT 1 FROM delivery_git_remotes WHERE id=$1 AND repository_id=$2',[remoteId,repoId]))throw new Error('Remote inválido.');const branch=body.branch?branchName(body.branch):null;if(branch&&repoId&&!await this.db.one('SELECT 1 FROM git_repositories WHERE id=$1 AND $2=ANY(branches)',[repoId,branch]))throw new Error('Branch fora da configuração.');const commands=body.buildCommands===undefined?[]:body.buildCommands;if(!Array.isArray(commands)||commands.length>20||commands.some(item=>typeof item!=='string'||!item.trim()||item.length>2000))throw new Error('Comandos de build inválidos.');const restart=body.restartCommand===undefined?null:txt(body.restartCommand,'Restart',2000);return this.db.one('INSERT INTO delivery_targets(project_id,environment_id,name,executor_type,server_id,repository_id,working_directory,git_remote_id,git_branch,build_commands,restart_command) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10::jsonb,$11) RETURNING *',[projectId,environmentId,txt(body.name,'Nome',120),executor,serverId,repoId,txt(body.workingDirectory,'Pasta',1000),remoteId,branch,JSON.stringify(commands),restart])}
  async createPipeline(userId:string,projectId:string,body:Record<string,unknown>){await this.project(projectId,userId);const trigger=body.triggerType??'manual';if(!['manual','card.completed'].includes(String(trigger)))throw new Error('Trigger inválido.');const policy=body.executionPolicy===undefined?{}:record(body.executionPolicy);noInlineSecrets(policy);return this.db.one('INSERT INTO delivery_pipelines(owner_id,project_id,name,description,trigger_type,enabled,execution_policy) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb) RETURNING *',[userId,projectId,txt(body.name,'Nome',120),typeof body.description==='string'?body.description.slice(0,2000):'',trigger,body.enabled===true,JSON.stringify(policy)])}
  async updatePipeline(userId:string,pipelineId:string,body:Record<string,unknown>){await this.pipeline(pipelineId,userId);const trigger=body.triggerType;if(trigger!==undefined&&!['manual','card.completed'].includes(String(trigger)))throw new Error('Trigger inválido.');const policy=body.executionPolicy===undefined?null:record(body.executionPolicy);if(policy)noInlineSecrets(policy);return this.db.one('UPDATE delivery_pipelines SET name=COALESCE($3,name),description=COALESCE($4,description),trigger_type=COALESCE($5,trigger_type),enabled=COALESCE($6,enabled),execution_policy=COALESCE($7::jsonb,execution_policy),updated_at=now() WHERE id=$1 AND owner_id=$2 RETURNING *',[pipelineId,userId,body.name===undefined?null:txt(body.name,'Nome',120),body.description===undefined?null:String(body.description).slice(0,2000),trigger??null,body.enabled===undefined?null:body.enabled===true,policy?JSON.stringify(policy):null])}
  async steps(userId:string,pipelineId:string){await this.pipeline(pipelineId,userId);return this.db.query<Step>('SELECT * FROM delivery_steps WHERE pipeline_id=$1 ORDER BY position',[pipelineId])}
  async replaceSteps(userId:string,pipelineId:string,input:unknown){await this.pipeline(pipelineId,userId);if(!Array.isArray(input)||input.length>100)throw new Error('Lista de steps inválida.');const client=await this.db.pool.connect();try{await client.query('BEGIN');await client.query('SELECT id FROM delivery_pipelines WHERE id=$1 FOR UPDATE',[pipelineId]);if((await client.query("SELECT 1 FROM delivery_runs WHERE pipeline_id=$1 AND status IN ('queued','running','waiting_approval') LIMIT 1",[pipelineId])).rowCount)throw new Error('Não edite pipeline com execução ativa.');await client.query('DELETE FROM delivery_steps WHERE pipeline_id=$1',[pipelineId]);for(let index=0;index<input.length;index++)await this.insertStep(client,pipelineId,index,record(input[index]));await client.query('COMMIT')}catch(error){await client.query('ROLLBACK');throw error}finally{client.release()}return this.steps(userId,pipelineId)}
  private async insertStep(client:PoolClient,pipelineId:string,position:number,body:Record<string,unknown>){
    const type=txt(body.type,'Tipo',60),config=record(body.config??{}),stepId=body.id?uid(body.id):undefined;
    noInlineSecrets(config);
    const timeout=body.timeoutMs===undefined?60000:Number(body.timeoutMs),maxAttempts=body.maxAttempts===undefined?1:Number(body.maxAttempts),delay=body.retryDelayMs===undefined?0:Number(body.retryDelayMs);
    const failure=body.failurePolicy??'stop',bypass=body.bypassPolicy??'deny',requires=body.requires??[];
    if(!Number.isInteger(timeout)||timeout<1000||timeout>1800000||!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>5||!Number.isInteger(delay)||delay<0||delay>60000||!['stop','continue','retry'].includes(String(failure))||!['deny','allow','allow_with_permission'].includes(String(bypass))||!Array.isArray(requires)||requires.some(item=>typeof item!=='string'||!/^context\.[A-Za-z0-9_]+$|^steps\.[0-9a-f-]{36}\.[A-Za-z0-9_]+$/i.test(item)))throw new Error('Política do step inválida.');
    this.handlers.validate({id:stepId||'',pipeline_id:pipelineId,type,name:String(body.name||type),config,position,timeout_ms:timeout,failure_policy:failure as Step['failure_policy'],max_attempts:maxAttempts,retry_delay_ms:delay,bypass_policy:bypass as Step['bypass_policy'],requires});
    await client.query('INSERT INTO delivery_steps(id,pipeline_id,type,name,config,position,timeout_ms,failure_policy,max_attempts,retry_delay_ms,bypass_policy,requires) VALUES(COALESCE($1::uuid,gen_random_uuid()),$2,$3,$4,$5::jsonb,$6,$7,$8,$9,$10,$11,$12)',[stepId||null,pipelineId,type,txt(body.name??type,'Nome',120),JSON.stringify(config),position,timeout,failure,maxAttempts,delay,bypass,requires]);
  }
}
