'use client';

import {useCallback,useEffect,useState} from 'react';
import {api,send,Board} from '@/lib/api';
import {Modal} from './ui';
import {ArrowDown,ArrowUp,Copy,Play,Plus,Trash2,Zap} from 'lucide-react';

type Condition={field:string;op:string;value?:string};
type Action={type:string;value?:string;field?:string;target?:string;listId?:string;report?:string;recipients?:string;subject?:string;template?:string};
type Trigger={type:string;event?:string;listId?:string;offsetMinutes?:number;frequency?:string;time?:string;timezone?:string;weekday?:number;intervalMinutes?:number};
type Definition={trigger:Trigger;conditions:Condition[];actions:Action[]};
type Rule={id:string;name:string;enabled:boolean;tags:string[];definition:Definition;next_run_at?:string|null};
type Suggestion={name:string;reason:string;definition:Definition};
type Logs={mailConfigured:boolean;runs:{id:string;status:string;created_at:string;details:{error?:string;reason?:string;actions?:number;affected?:number}}[];mail:{id:string;recipient:string;subject:string;error?:string;sent_at:string|null;attempts:number}[]};
const input='w-full min-w-0 rounded border border-[#8590a2] bg-white p-2 text-sm text-[#172b4d] dark:bg-[#22272b] dark:text-[#b6c2cf]';
const button='rounded border border-[#8590a2] px-3 py-2 text-sm hover:bg-[#091e4214] disabled:opacity-50';
const primary='rounded bg-[#0c66e4] px-3 py-2 text-sm font-semibold text-white disabled:opacity-50';
const types:Record<string,string>={event:'Regra por evento',card_button:'Botão do cartão',board_button:'Botão do quadro',scheduled:'Agendamento',due:'Vencimento'};
const eventNames:Record<string,string>={card_created:'Cartão criado',card_moved:'Cartão entra em uma lista',card_updated:'Cartão alterado',card_completed:'Status de conclusão alterado',due_changed:'Vencimento alterado',label_changed:'Etiqueta adicionada ou removida',member_changed:'Membros alterados',comment_added:'Comentário publicado',field_changed:'Campo personalizado alterado',checklist_changed:'Checklist alterado'};
const actions:Record<string,string>={move:'Mover para lista',label_add:'Adicionar etiqueta',label_remove:'Remover etiqueta',assign:'Atribuir membro',unassign:'Remover membro',complete:'Definir conclusão',archive:'Arquivar cartão',rename:'Alterar título',description:'Alterar descrição',comment:'Comentar',due:'Definir vencimento',start:'Definir início',field:'Preencher campo',checklist_add:'Criar checklist',checklist_complete:'Concluir itens de checklist',sort:'Ordenar cartões',report:'Enviar relatório por e-mail'};
const conditions:Record<string,string>={title:'Título',description:'Descrição',list_id:'Lista',completed:'Concluído',due_date:'Vencimento',labels:'Etiquetas',members:'Membros',archived:'Arquivado'};
const operators:Record<string,string>={eq:'É igual a',neq:'É diferente de',contains:'Contém',not_contains:'Não contém',gt:'Maior / depois de',lt:'Menor / antes de',empty:'Está vazio',not_empty:'Não está vazio'};
Object.assign(eventNames,{'execution.queued':'Execução enfileirada','execution.started':'Execução iniciada','execution.completed':'Execução concluída','execution.failed':'Execução falhou','execution.cancelled':'Execução cancelada'});
Object.assign(actions,{run_agent:'Executar agente do cartão',run_skill:'Executar skill do cartão',execute_plugin_action:'Executar integrações do cartão',create_card:'Criar cartão na mesma lista'});
function Select({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:Record<string,string>}){return <label className="block min-w-0 space-y-1 text-xs font-semibold"><span>{label}</span><select aria-label={label} className={input} value={value} onChange={e=>onChange(e.target.value)}>{Object.entries(options).map(([key,text])=><option key={key} value={key}>{text}</option>)}</select></label>}
function Text({label,value,onChange,placeholder='',multiline=false}:{label:string;value:string;onChange:(v:string)=>void;placeholder?:string;multiline?:boolean}){return <label className="block min-w-0 space-y-1 text-xs font-semibold"><span>{label}</span>{multiline?<textarea className={input} value={value} onChange={e=>onChange(e.target.value)} rows={3} placeholder={placeholder}/>:<input className={input} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder}/>}</label>}
const entries=(items:{id:string;title?:string;name?:string}[]|undefined)=>Object.fromEntries((items||[]).map(x=>[x.id,x.title||x.name||x.id]));
function ValueEditor({field,value,onChange,board}:{field:string;value:string;onChange:(v:string)=>void;board:Board}){
  const options=field==='list_id'?entries(board.lists):field==='labels'?entries(board.labels):field==='members'?entries(board.members):['completed','archived'].includes(field)?{true:'Sim',false:'Não'}:null;
  return options?<Select label="Valor" value={value} onChange={onChange} options={{'':'Selecione',...options}}/>:<Text label="Valor" value={value} onChange={onChange} placeholder={field==='due_date'?'{{now + 2 days}}':'Texto ou variável'}/>;
}
function fresh(listId?:string):Rule{return {id:'',name:'',enabled:true,tags:[],definition:{trigger:{type:'event',event:'card_moved',...(listId?{listId}:{})},conditions:[],actions:[{type:'due',target:'card',value:'now + 2 business_days'}]}}}

export function AutomationControls({boardId,cardId,listId,onChanged}:{boardId:string;cardId?:string;listId?:string;onChanged?:()=>Promise<void>}){
  const [open,setOpen]=useState(false),[rules,setRules]=useState<Rule[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[result,setResult]=useState('');
  const refresh=useCallback(()=>api<Rule[]>(`/boards/${boardId}/automations`).then(setRules).catch(e=>setError(e.message)),[boardId]);
  useEffect(()=>{if(listId)return;void refresh();const listener=()=>void refresh();window.addEventListener('automations:changed',listener);return()=>window.removeEventListener('automations:changed',listener)},[refresh,listId]);
  useEffect(()=>{
    if(cardId||listId||!onChanged)return;
    let active=true,last:string|null|undefined,inFlight=false;
    async function poll(){if(inFlight||document.hidden)return;inFlight=true;try{const status=await api<{last:string|null}>(`/boards/${boardId}/automation-status`);if(active){const changed=last!==undefined&&last!==status.last;last=status.last;if(changed)await onChanged?.()}}catch(error){if(active)setError((error as Error).message)}finally{inFlight=false}}
    void poll();const timer=setInterval(()=>void poll(),5000);return()=>{active=false;clearInterval(timer)};
  },[boardId,cardId,listId,onChanged]);
  async function run(rule:Rule){setBusy(true);setError('');setResult('');try{const r=await send<{status:string;error?:string;affected?:number}>(`/automations/${rule.id}/run`,'POST',{cardId,requestId:crypto.randomUUID()});if(r.status==='error')throw new Error(r.error);setResult(r.status==='skipped'?'As condições não foram atendidas.':`Executado: ${r.affected||0} alterações.`);await onChanged?.()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <div className="flex max-w-full flex-wrap items-center gap-1 text-sm">
    {!listId&&rules.filter(r=>r.enabled&&r.definition.trigger.type===(cardId?'card_button':'board_button')).map(r=><button key={r.id} className={button} disabled={busy} onClick={()=>void run(r)} title={r.name}><Play size={12} className="mr-1 inline"/>{r.name}</button>)}
    <button className={button} onClick={()=>setOpen(true)}><Zap size={14} className="mr-1 inline"/>{listId?'Automatizar lista':cardId?'Botões e regras':'Automação'}</button>
    {error&&<p role="alert" className="w-full rounded bg-red-50 p-2 text-xs text-red-800">{error}</p>}{result&&<p role="status" className="w-full rounded bg-green-50 p-2 text-xs text-green-800">{result}</p>}
    {open&&<AutomationManager boardId={boardId} listId={listId} onClose={()=>{setOpen(false);void refresh()}}/>}
  </div>;
}

function AutomationManager({boardId,listId,onClose}:{boardId:string;listId?:string;onClose:()=>void}){
  const [board,setBoard]=useState<Board|null>(null),[rules,setRules]=useState<Rule[]>([]),[suggestions,setSuggestions]=useState<Suggestion[]>([]),[editing,setEditing]=useState<Rule|null>(listId?fresh(listId):null),[filter,setFilter]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[logs,setLogs]=useState<Logs|null>(null),[copyRule,setCopyRule]=useState<Rule|null>(null),[copyBoard,setCopyBoard]=useState<Board|null>(null),[boards,setBoards]=useState<Board[]>([]),[mapping,setMapping]=useState<Record<string,string>>({});
  const load=useCallback(async()=>{const [b,r,s]=await Promise.all([api<Board>(`/boards/${boardId}`),api<Rule[]>(`/boards/${boardId}/automations`),api<Suggestion[]>(`/boards/${boardId}/automation-suggestions`)]);setBoard(b);setRules(r);setSuggestions(s)},[boardId]);
  useEffect(()=>{let active=true;Promise.all([api<Board>(`/boards/${boardId}`),api<Rule[]>(`/boards/${boardId}/automations`),api<Suggestion[]>(`/boards/${boardId}/automation-suggestions`)]).then(([b,r,s])=>{if(active){setBoard(b);setRules(r);setSuggestions(s)}}).catch(e=>{if(active)setError(e.message)});return()=>{active=false}},[boardId]);
  async function act(fn:()=>Promise<unknown>){setError('');setBusy(true);try{await fn();await load();window.dispatchEvent(new Event('automations:changed'));return true}catch(e){setError((e as Error).message);return false}finally{setBusy(false)}}
  const edit=(patch:Partial<Rule>)=>setEditing(current=>current?{...current,...patch}:null);
  const definition=(patch:Partial<Definition>)=>editing&&edit({definition:{...editing.definition,...patch}});
  const trigger=(patch:Partial<Trigger>)=>editing&&definition({trigger:{...editing.definition.trigger,...patch}});
  const changeAction=(index:number,patch:Partial<Action>)=>editing&&definition({actions:editing.definition.actions.map((a,i)=>i===index?{...a,...patch}:a)});
  const changeCondition=(index:number,patch:Partial<Condition>)=>editing&&definition({conditions:editing.definition.conditions.map((c,i)=>i===index?{...c,...patch}:c)});
  const refs=copyRule?Array.from(new Set(JSON.stringify(copyRule.definition).match(/[\da-f]{8}-[\da-f]{4}-[\da-f]{4}-[\da-f]{4}-[\da-f]{12}/gi)||[])):[];
  const refOptions=(id:string,b:Board)=>board?.lists?.some(x=>x.id===id)?entries(b.lists):board?.labels?.some(x=>x.id===id)?entries(b.labels):board?.members?.some(x=>x.id===id)?entries(b.members):entries(b.custom_fields);
  const refName=(id:string)=>[...(board?.lists||[]),...(board?.labels||[]),...(board?.members||[]),...(board?.custom_fields||[])].find(x=>x.id===id);
  return <Modal onClose={onClose} wide><div className="max-h-[85vh] w-full overflow-y-auto p-4 text-[#172b4d] dark:text-[#b6c2cf] sm:p-6">
    <div className="mb-4 pr-10"><h2 className="text-lg font-bold">Automação · {board?.title||'Carregando'}</h2></div>
    {error&&<p role="alert" className="mb-3 rounded bg-red-50 p-3 text-red-800">{error}</p>}
    {!board&&<p>Carregando configurações…</p>}
    {board&&!editing&&!logs&&!copyRule&&<>
      <div className="mb-4 flex flex-wrap gap-2"><button className={primary} onClick={()=>setEditing(fresh(listId))}><Plus className="mr-1 inline" size={15}/>Nova automação</button><input aria-label="Filtrar por nome ou tag" placeholder="Buscar por nome ou tag" className={input+' flex-1'} value={filter} onChange={e=>setFilter(e.target.value)}/></div>
      {rules.filter(r=>(r.name+' '+r.tags.join(' ')).toLowerCase().includes(filter.toLowerCase())).map(rule=><article key={rule.id} className="mb-3 space-y-2 rounded border border-[#8590a2] p-3">
        <div className="flex items-start justify-between gap-2"><div><h3 className="font-bold">{rule.name}</h3><p className="text-xs">{types[rule.definition.trigger.type]} · {rule.definition.actions.length} ações · {rule.tags.join(', ')}</p>{rule.next_run_at&&<p className="text-xs">Próxima: {new Date(rule.next_run_at).toLocaleString('pt-BR')}</p>}</div><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={rule.enabled} disabled={busy} onChange={()=>void act(()=>send(`/automations/${rule.id}`,'PATCH',{enabled:!rule.enabled}))}/>{rule.enabled?'Ativa':'Pausada'}</label></div>
        <div className="flex flex-wrap gap-2"><button className={button} onClick={()=>setEditing(structuredClone(rule))}>Editar</button><button className={button} disabled={busy} onClick={()=>void act(()=>send(`/automations/${rule.id}/copy`,'POST',{}))}><Copy size={13} className="mr-1 inline"/>Duplicar</button><button className={button} onClick={()=>void act(async()=>{setBoards(await api<Board[]>('/boards'));setCopyRule(rule);setCopyBoard(null);setMapping({})})}>Aplicar em outro quadro</button><button className={button} onClick={()=>void act(async()=>setLogs(await api<Logs>(`/automations/${rule.id}/logs`)))}>Histórico</button><button aria-label={`Excluir ${rule.name}`} className={button} disabled={busy} onClick={()=>{if(window.confirm('Excluir esta automação e seu histórico?'))void act(()=>send(`/automations/${rule.id}`,'DELETE'))}}><Trash2 size={14}/></button></div>
      </article>)}
      {!rules.length&&<p className="py-4 text-sm">Crie uma regra, botão ou relatório para automatizar este quadro.</p>}
      {suggestions.length>0&&<section className="mt-5"><h3 className="mb-2 font-bold">Sugestões a partir da atividade</h3>{suggestions.map((s,i)=><div key={i} className="mb-2 rounded bg-[#0c66e410] p-3"><p>{s.name}</p><p className="text-xs">{s.reason}</p><button className={button+' mt-2'} onClick={()=>setEditing({...fresh(),name:s.name,definition:s.definition})}>Revisar e personalizar</button></div>)}</section>}
    </>}
    {board&&editing&&<form className="space-y-5" onSubmit={async e=>{e.preventDefault();if(await act(()=>send(editing.id?`/automations/${editing.id}`:`/boards/${boardId}/automations`,editing.id?'PATCH':'POST',editing)))setEditing(null)}}>
      <Text label="Nome" value={editing.name} onChange={name=>edit({name})}/><Text label="Tags (separadas por vírgula)" value={editing.tags.join(',')} onChange={v=>edit({tags:v.split(',')})}/>
      <Select label="Gatilho" value={editing.definition.trigger.type} options={types} onChange={type=>{const actionTarget=['scheduled','board_button'].includes(type)?'board':'card';definition({trigger:{type,event:'card_moved',frequency:'daily',time:'09:00',timezone:'America/Recife',weekday:1,intervalMinutes:60,offsetMinutes:-1440,...(listId?{listId}:{})},actions:editing.definition.actions.map(a=>({...a,target:a.target==='card'||a.target==='board'?actionTarget:a.target}))})}}/>
      {editing.definition.trigger.type==='event'&&<Select label="Quando" value={editing.definition.trigger.event||''} options={eventNames} onChange={event=>trigger({event})}/>}
      {['event','due'].includes(editing.definition.trigger.type)&&<Select label="Lista do gatilho" value={editing.definition.trigger.listId||''} options={{'':'Qualquer lista',...entries(board.lists)}} onChange={listId=>trigger({listId:listId||undefined})}/>}
      {editing.definition.trigger.type==='due'&&<Text label="Minutos após o prazo (negativo = antes, zero = no vencimento)" value={String(editing.definition.trigger.offsetMinutes??-1440)} onChange={v=>trigger({offsetMinutes:Number(v)})}/>}
      {editing.definition.trigger.type==='scheduled'&&<div className="grid gap-3 sm:grid-cols-2"><Select label="Frequência" value={editing.definition.trigger.frequency||'daily'} options={{daily:'Diariamente',weekly:'Semanalmente',interval:'Intervalo de minutos'}} onChange={frequency=>trigger({frequency})}/>{editing.definition.trigger.frequency==='interval'?<Text label="Intervalo (mínimo 5 minutos)" value={String(editing.definition.trigger.intervalMinutes||60)} onChange={v=>trigger({intervalMinutes:Number(v)})}/>:<><Text label="Horário (HH:mm)" value={editing.definition.trigger.time||'09:00'} onChange={time=>trigger({time})}/><Text label="Fuso horário" value={editing.definition.trigger.timezone||'America/Recife'} onChange={timezone=>trigger({timezone})}/>{editing.definition.trigger.frequency==='weekly'&&<Select label="Dia da semana" value={String(editing.definition.trigger.weekday??1)} options={{0:'Domingo',1:'Segunda',2:'Terça',3:'Quarta',4:'Quinta',5:'Sexta',6:'Sábado'}} onChange={v=>trigger({weekday:Number(v)})}/>}</>}</div>}
      {listId&&<button type="button" className={button} onClick={()=>definition({trigger:{type:'scheduled',frequency:'daily',time:'09:00',timezone:'America/Recife'},actions:[{type:'sort',value:'due_date',target:'list',listId}]})}>Usar ordenação diária desta lista por vencimento</button>}
      <section className="space-y-3"><h3 className="font-bold">Condições · todas devem ser atendidas</h3>{editing.definition.conditions.map((c,index)=><div key={index} className="space-y-2 rounded border p-3"><div className="grid gap-2 sm:grid-cols-2"><Select label="Propriedade" value={c.field} options={{...conditions,...Object.fromEntries((board.custom_fields||[]).map(f=>['custom:'+f.id,'Campo: '+f.name]))}} onChange={field=>changeCondition(index,{field,value:''})}/><Select label="Comparação" value={c.op} options={operators} onChange={op=>changeCondition(index,{op})}/>{!['empty','not_empty'].includes(c.op)&&<ValueEditor board={board} field={c.field} value={c.value||''} onChange={value=>changeCondition(index,{value})}/>}</div><button type="button" className={button} onClick={()=>definition({conditions:editing.definition.conditions.filter((_,i)=>i!==index)})}>Remover condição</button></div>)}<button type="button" className={button} disabled={editing.definition.conditions.length>=30} onClick={()=>definition({conditions:[...editing.definition.conditions,{field:'title',op:'contains',value:''}]})}>+ Condição</button></section>
      <section className="space-y-3"><h3 className="font-bold">Ações sequenciais ({editing.definition.actions.length}/20)</h3>{editing.definition.actions.map((a,index)=><div key={index} className="space-y-3 rounded border p-3">
        <div className="flex items-center justify-between"><strong className="text-xs">Ação {index+1}</strong><div className="flex gap-1">{[-1,1].map(step=><button key={step} type="button" aria-label={step===-1?'Subir ação':'Descer ação'} disabled={index+step<0||index+step>=editing.definition.actions.length} className={button} onClick={()=>{const array=[...editing.definition.actions];[array[index],array[index+step]]=[array[index+step],array[index]];definition({actions:array})}}>{step===-1?<ArrowUp size={13}/>:<ArrowDown size={13}/>}</button>)}<button type="button" className={button} aria-label="Remover ação" onClick={()=>definition({actions:editing.definition.actions.filter((_,i)=>i!==index)})}><Trash2 size={13}/></button></div></div>
        <div className="grid gap-3 sm:grid-cols-2"><Select label="Ação" value={a.type} options={actions} onChange={type=>changeAction(index,{type,value:type==='complete'?'true':type==='sort'?'due_date':'',report:'snapshot',...(type==='report'?{target:'board'}:{})})}/><Select label="Aplicar a" value={a.target||'card'} options={{...(!['scheduled','board_button'].includes(editing.definition.trigger.type)?{card:'Cartão do gatilho'}:{}),list:'Cartões de uma lista',board:'Cartões de todo o quadro'}} onChange={target=>changeAction(index,{target})}/>
        {a.target==='list'&&<Select label="Lista alvo" value={a.listId||''} options={{'':'Selecione',...entries(board.lists)}} onChange={listId=>changeAction(index,{listId})}/>}
        {a.type==='move'?<Select label="Lista de destino" value={a.value||''} options={{'':'Selecione',...entries(board.lists)}} onChange={value=>changeAction(index,{value})}/>:a.type.startsWith('label_')?<Select label="Etiqueta" value={a.value||''} options={{'':'Selecione',...entries(board.labels)}} onChange={value=>changeAction(index,{value})}/>:['assign','unassign'].includes(a.type)?<Select label="Membro" value={a.value||''} options={{'':'Selecione',...entries(board.members)}} onChange={value=>changeAction(index,{value})}/>:a.type==='complete'?<Select label="Status" value={a.value||'true'} options={{true:'Concluído',false:'Pendente'}} onChange={value=>changeAction(index,{value})}/>:a.type==='sort'?<Select label="Ordenar por" value={a.value||'due_date'} options={{due_date:'Vencimento',title:'Título',created_at:'Criação'}} onChange={value=>changeAction(index,{value})}/>:!['archive','report'].includes(a.type)&&<Text label={['due','start'].includes(a.type)?'Data ou cálculo (vazio remove a data)':a.type==='checklist_complete'?'Texto dos itens (vazio = todos)':'Conteúdo'} value={a.value||''} onChange={value=>changeAction(index,{value})} multiline={['comment','description','checklist_add'].includes(a.type)} placeholder={['due','start'].includes(a.type)?'now + 2 business_days':a.type==='checklist_add'?'Um item por linha':'Texto e {{variáveis}}'}/>}
        {a.type==='field'&&<Select label="Campo personalizado" value={a.field||''} options={{'':'Selecione',...entries(board.custom_fields)}} onChange={field=>changeAction(index,{field})}/>}</div>
        {a.type==='report'&&<div className="space-y-3"><Select label="Modelo de relatório" value={a.report||'snapshot'} options={{snapshot:'Board Snapshot',due_soon:'Due Soon (próximos 7 dias)',overdue:'Overdue Cards',my_cards:'My Cards',custom:'Personalizado'}} onChange={report=>changeAction(index,{report})}/><Text label="Destinatários (separados por vírgula)" value={a.recipients||''} onChange={recipients=>changeAction(index,{recipients})}/><Text label="Assunto" value={a.subject||''} onChange={subject=>changeAction(index,{subject})} placeholder="Relatório de {{board}}"/><Text label="Mensagem por cartão (Markdown e variáveis)" value={a.template||''} onChange={template=>changeAction(index,{template})} multiline placeholder="- {{title}} | {{list}} | {{due_date}}"/><p className="text-xs">O relatório usa as condições acima. Configure o envio SMTP do servidor para entregar e-mails; consulte a fila no histórico.</p></div>}
      </div>)}<button type="button" className={button} disabled={editing.definition.actions.length>=20} onClick={()=>definition({actions:[...editing.definition.actions,{type:'complete',value:'true',target:['scheduled','board_button'].includes(editing.definition.trigger.type)?'board':'card'}]})}>+ Ação</button></section>
      <details className="rounded bg-[#0c66e410] p-3 text-xs"><summary className="cursor-pointer font-bold">Variáveis e cálculos disponíveis</summary><p className="mt-2 break-words">{'{{title}}, {{description}}, {{list}}, {{board}}, {{user}}, {{members}}, {{due_date}}, {{now}}, {{now + 2 days|date}}, {{due - 30 minutes|time}}, {{today + 3 business_days}}. Datas em UTC; agendamentos usam o fuso escolhido. Para campos personalizados: {{custom:ID_DO_CAMPO}}. Os membros são identificados por ID.'}</p>{board.custom_fields?.map(f=><p className="mt-1 break-all" key={f.id}>{f.name}: {'{{custom:'+f.id+'}}'}</p>)}<p className="mt-2">Dias úteis: segunda a sexta, sem calendário de feriados. Cascatas alcançam cartões vinculados no mesmo quadro. Uma execução atende até 500 cartões. Regras encadeadas têm limite de 5 níveis.</p></details>
      <div className="flex gap-2"><button className={primary} disabled={busy||!editing.name.trim()||!editing.definition.actions.length}>Salvar automação</button><button type="button" className={button} onClick={()=>setEditing(null)}>Cancelar</button></div>
    </form>}
    {logs&&<section className="space-y-3"><button className={button} onClick={()=>setLogs(null)}>Voltar</button><h3 className="font-bold">Histórico das últimas 100 execuções</h3>{!logs.runs.length&&<p>Nenhuma execução.</p>}{logs.runs.map(r=><div key={r.id} className="rounded border p-3 text-sm"><strong>{r.status==='success'?'Concluída':r.status==='error'?'Falhou':'Ignorada'}</strong> · {new Date(r.created_at).toLocaleString('pt-BR')}<p>{r.details.error||r.details.reason||`${r.details.actions||0} ações, ${r.details.affected||0} alterações`}</p></div>)}<h3 className="font-bold">Entrega de relatórios</h3>{!logs.mailConfigured&&<p className="text-sm">SMTP ainda não configurado. Relatórios ficam na fila até a configuração.</p>}{logs.mail.map(m=><div key={m.id} className="rounded border p-3 text-sm"><p>{m.subject} → {m.recipient}</p><p>{m.sent_at?'Enviado em '+new Date(m.sent_at).toLocaleString('pt-BR'):m.error||'Aguardando envio'} · {m.attempts} tentativas</p></div>)}</section>}
    {copyRule&&board&&<section className="space-y-3"><h3 className="font-bold">Aplicar {copyRule.name} em outro quadro</h3><Select label="Quadro de destino" value={copyBoard?.id||''} options={{'':'Selecione',...entries(boards.filter(b=>b.id!==boardId&&!b.closed_at))}} onChange={id=>{setMapping({});if(id)void act(async()=>setCopyBoard(await api<Board>(`/boards/${id}`)));else setCopyBoard(null)}}/>{copyBoard&&refs.map(id=>{const ref=refName(id);return <Select key={id} label={`Destino de ${ref?('title' in ref?ref.title:ref.name):id}`} value={mapping[id]||''} options={{'':'Selecione',...refOptions(id,copyBoard)}} onChange={v=>setMapping({...mapping,[id]:v})}/>})}<p className="text-sm">Será criada uma cópia independente, inicialmente pausada, com as referências escolhidas.</p><button className={primary} disabled={busy||!copyBoard||refs.some(id=>!mapping[id])} onClick={()=>void act(async()=>{await send(`/automations/${copyRule.id}/copy`,'POST',{boardId:copyBoard?.id,mapping});setCopyRule(null)})}>Criar cópia</button> <button className={button} onClick={()=>setCopyRule(null)}>Cancelar</button></section>}
  </div></Modal>;
}
