'use client';
import { useMemo, useState } from 'react';
import { BarChart3, MapPin, Timer } from 'lucide-react';
import { Board, Card, labelColors } from '@/lib/api';

type View='board'|'calendar'|'timeline'|'table'|'dashboard'|'map';
const labels:Record<View,string>={board:'Quadro',calendar:'Calendário',timeline:'Linha do tempo',table:'Tabela',dashboard:'Dashboard',map:'Mapa'};
export function BoardViews({board,onOpen}:{board:Board;onOpen:(card:Card)=>void}){
 const [view,setView]=useState<View>('board');const cards=useMemo(()=>board.lists?.flatMap(list=>list.cards.map(card=>({...card,list_title:list.title})))||[ ],[board]);
 if(view==='board')return <div className="flex items-center gap-1"><ViewMenu view={view} setView={setView}/></div>;
 return <div className="absolute inset-x-0 bottom-0 top-14 z-20 overflow-auto bg-[#f7f8fa] p-4 text-[#172b4d] sm:p-6"><div className="mx-auto max-w-6xl"><div className="mb-5 flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-bold">{labels[view]}</h2><p className="text-sm text-[#626f86]">{board.title}</p></div><ViewMenu view={view} setView={setView}/></div>{view==='calendar'&&<Calendar cards={cards} onOpen={onOpen}/>} {view==='timeline'&&<TimerView cards={cards} onOpen={onOpen}/>} {view==='table'&&<TableView cards={cards} onOpen={onOpen}/>} {view==='dashboard'&&<Dashboard cards={cards}/>} {view==='map'&&<MapView cards={cards} onOpen={onOpen}/>}</div></div>;
}
function ViewMenu({view,setView}:{view:View;setView:(v:View)=>void}){return <div className="flex flex-wrap rounded bg-white p-1 shadow-sm">{(['board','calendar','timeline','table','dashboard','map'] as View[]).map(item=><button key={item} onClick={()=>setView(item)} className={`rounded px-2 py-1.5 text-xs font-semibold ${view===item?'bg-[#0c66e4] text-white':'hover:bg-[#f1f2f4]'}`}>{labels[item]}</button>)}</div>}
function Calendar({cards,onOpen}:{cards:(Card&{list_title:string})[];onOpen:(c:Card)=>void}){const dated=cards.filter(c=>c.due_date||c.start_date);return <div className="grid grid-cols-1 gap-3 sm:grid-cols-2 lg:grid-cols-3">{dated.length?dated.sort((a,b)=>String(a.due_date||a.start_date).localeCompare(String(b.due_date||b.start_date))).map(card=><button key={card.id} onClick={()=>onOpen(card)} className="rounded-xl border bg-white p-4 text-left shadow-sm hover:border-[#388bff]"><p className="text-xs font-bold text-[#0c66e4]">{new Date(card.due_date||card.start_date||'').toLocaleDateString('pt-BR',{weekday:'short',day:'2-digit',month:'short'})}</p><p className="mt-2 font-semibold">{card.title}</p><p className="mt-1 text-xs text-[#626f86]">{card.list_title}</p></button>):<Empty text="Adicione datas aos cartões para vê-los no calendário."/>}</div>}
function TimerView({cards,onOpen}:{cards:(Card&{list_title:string})[];onOpen:(c:Card)=>void}){const dated=cards.filter(c=>c.start_date||c.due_date);return <div className="space-y-3">{dated.length?dated.map(card=>{const start=card.start_date?new Date(card.start_date):null,end=card.due_date?new Date(card.due_date):null;return <button key={card.id} onClick={()=>onOpen(card)} className="flex w-full items-center gap-4 rounded-xl border bg-white p-3 text-left hover:border-[#388bff]"><Timer className="text-[#0c66e4]"/><div className="min-w-0 flex-1"><p className="font-semibold">{card.title}</p><p className="text-xs text-[#626f86]">{start?.toLocaleDateString('pt-BR')||'Sem início'} → {end?.toLocaleDateString('pt-BR')||'Sem vencimento'}</p></div><span className="h-3 w-1/3 rounded bg-[#579dff]"/></button>}):<Empty text="Defina início ou vencimento para criar a linha do tempo."/>}</div>}
function TableView({cards,onOpen}:{cards:(Card&{list_title:string})[];onOpen:(c:Card)=>void}){return <div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-[#f1f2f4] text-xs text-[#44546f]"><tr><th className="p-3">Cartão</th><th>Lista</th><th>Vencimento</th><th>Etiquetas</th><th>Status</th></tr></thead><tbody>{cards.map(card=><tr key={card.id} className="border-t hover:bg-[#f7f8fa]"><td className="p-3"><button onClick={()=>onOpen(card)} className="font-semibold hover:text-[#0c66e4]">{card.title}</button></td><td>{card.list_title}</td><td>{card.due_date?new Date(card.due_date).toLocaleDateString('pt-BR'):'—'}</td><td><div className="flex gap-1">{card.labels.map(label=><span key={label.id} className="h-3 w-8 rounded" style={{background:labelColors[label.color]||label.color}}/>)}</div></td><td>{card.completed?'Concluído':'Pendente'}</td></tr>)}</tbody></table></div>}
function Dashboard({cards}:{cards:(Card&{list_title:string})[]}){const groups=Object.entries(cards.reduce<Record<string,number>>((all,c)=>{all[c.list_title]=(all[c.list_title]||0)+1;return all},{}));const overdue=cards.filter(c=>c.due_date&&new Date(c.due_date)<new Date()&&!c.completed).length;return <div className="grid gap-4 md:grid-cols-3"><Tile label="Cartões" value={cards.length}/><Tile label="Concluídos" value={cards.filter(c=>c.completed).length}/><Tile label="Vencidos" value={overdue}/><div className="rounded-xl border bg-white p-5 shadow-sm md:col-span-3"><h3 className="mb-4 flex items-center gap-2 font-bold"><BarChart3 size={18}/> Cartões por lista</h3>{groups.map(([name,count])=><div key={name} className="mb-3 flex items-center gap-3 text-sm"><span className="w-32 truncate">{name}</span><span className="h-5 rounded bg-[#579dff]" style={{width:`${Math.max(8,count/Math.max(1,cards.length)*100)}%`}}/><b>{count}</b></div>)}</div></div>}
function MapView({cards,onOpen}:{cards:(Card&{list_title:string})[];onOpen:(c:Card)=>void}){return <div className="relative min-h-[480px] overflow-hidden rounded-xl border bg-[#d9eef8]" style={{backgroundImage:'linear-gradient(30deg,#ffffff66 12%,transparent 12.5%,transparent 87%,#ffffff66 87.5%),linear-gradient(150deg,#ffffff66 12%,transparent 12.5%,transparent 87%,#ffffff66 87.5%)',backgroundSize:'48px 84px'}}><div className="absolute left-4 top-4 rounded bg-white/90 p-3 text-sm shadow"><MapPin className="mb-1 text-[#e5484d]" size={18}/>Mapa de cartões<br/><span className="text-xs text-[#626f86]">Pins usam a primeira etiqueta ou a capa.</span></div>{cards.slice(0,20).map((card,index)=><button key={card.id} onClick={()=>onOpen(card)} title={card.title} className="absolute grid h-9 w-9 place-items-center rounded-full border-2 border-white text-white shadow" style={{left:`${12+(index*37)%76}%`,top:`${25+(index*53)%62}%`,background:labelColors[card.labels[0]?.color||'']||card.cover_color||'#0c66e4'}}><MapPin size={18}/></button>)}</div>}
function Tile({label,value}:{label:string;value:number}){return <div className="rounded-xl border bg-white p-5 shadow-sm"><p className="text-sm text-[#626f86]">{label}</p><p className="mt-2 text-3xl font-bold">{value}</p></div>};function Empty({text}:{text:string}){return <div className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-[#626f86]">{text}</div>}
