'use client';
import {useCallback,useEffect,useState} from 'react';
import {api,send,Board,Card} from '@/lib/api';
import {Catalog,ExecutionConfig,ExecutionDetails,Output,Run,executionStatus} from '@/lib/execution';

const input='w-full min-w-0 rounded border border-[#8590a2] bg-white px-2 py-1.5 text-sm text-[#172b4d]';
const button='rounded bg-[#0c66e4] px-3 py-1.5 text-sm font-semibold text-white disabled:opacity-50';
function Select({label,value,options,onChange}:{label:string;value:string;options:{id:string;name:string}[];onChange:(v:string)=>void}){return <label className="block text-xs font-semibold">{label}<select aria-label={label} className={input+' mt-1'} value={value} onChange={e=>onChange(e.target.value)}><option value="">Selecione</option>{options.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>}
function Multi({label,value,options,onChange}:{label:string;value:string[];options:{id:string;name:string}[];onChange:(v:string[])=>void}){return <fieldset className="space-y-1 text-xs"><legend className="mb-1 font-semibold">{label}</legend>{!options.length&&<p className="text-[#626f86]">Nenhum recurso registrado.</p>}{options.map(o=><label key={o.id} className="mr-3 inline-flex items-center gap-1"><input type="checkbox" checked={value.includes(o.id)} onChange={e=>onChange(e.target.checked?[...value,o.id]:value.filter(x=>x!==o.id))}/>{o.name}</label>)}</fieldset>}
export function ExecutionOutput({output}:{output:Output}){
  const text=typeof output.value==='string'?output.value:JSON.stringify(output.value,null,2);
  const url=['url','pull_request'].includes(output.type)&&typeof output.value==='string'&&/^https?:\/\//.test(output.value);
  return <div className="min-w-0 rounded border border-[#dfe1e6] bg-white p-2"><h4 className="text-xs font-bold">{output.label||output.type}</h4>{url?<a href={text} target="_blank" rel="noopener noreferrer" className="break-all text-sm text-[#0c66e4] underline">{text}</a>:<pre className="max-h-64 overflow-auto whitespace-pre-wrap break-words text-xs">{text}</pre>}</div>;
}
export function CardExecutionBadge({card}:{card:Card}){
  const [busy,setBusy]=useState(false),[error,setError]=useState('');
  if(!card.execution?.enabled)return null;
  const active=busy||['queued','running'].includes(card.result?.status||'');
  return <div className="mt-2 flex flex-wrap items-center gap-2 text-[11px] text-[#626f86]"><span>◈ {card.execution.agent||card.execution.executor} · {executionStatus[card.result?.status||'idle']}</span><button disabled={active} onPointerDown={e=>e.stopPropagation()} onClick={async e=>{e.stopPropagation();setBusy(true);setError('');try{await send(`/cards/${card.source_card_id||card.id}/runs`,'POST',{request_key:crypto.randomUUID()});window.dispatchEvent(new Event('data:changed'))}catch(error){setError((error as Error).message)}finally{setBusy(false)}}} className="rounded bg-[#e9eaed] px-2 py-1 text-[#0c66e4] disabled:opacity-50">{active?'Executando…':'Executar'}</button>{error&&<span role="alert" className="text-red-700">{error}</span>}</div>;
}

export function CardExecutionPanel({card,board,onChanged}:{card:Card;board:Board;onChanged:()=>Promise<void>}){
  const [details,setDetails]=useState<ExecutionDetails|null>(null),[draft,setDraft]=useState<ExecutionConfig|null>(null),[catalog,setCatalog]=useState<Catalog|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[dirty,setDirty]=useState(false),[selected,setSelected]=useState<Run|null>(null);
  useEffect(()=>{let live=true;api<ExecutionDetails>(`/cards/${card.id}/execution`).then(data=>{if(live){setDetails(data);setDraft(data.execution)}}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[card.id]);
  const project=draft?.project_id;
  useEffect(()=>{let live=true;api<Catalog>('/execution/catalog'+(project?'?project_id='+project:'')).then(data=>{if(live)setCatalog(data)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[project]);
  const refresh=useCallback(async()=>{const data=await api<ExecutionDetails>(`/cards/${card.id}/execution`);setDetails(data);return data},[card.id]);
  const active=details?.runs.some(r=>['queued','running'].includes(r.status));
  useEffect(()=>{const timer=setInterval(()=>{if(!document.hidden)void api<ExecutionDetails>(`/cards/${card.id}/execution`).then(setDetails).catch(e=>setError(e.message))},active?1500:5000);return()=>clearInterval(timer)},[card.id,active]);
  function edit(patch:Partial<ExecutionConfig>){setDraft(current=>current?{...current,...patch}:null);setDirty(true)}
  async function work(fn:()=>Promise<unknown>){setBusy(true);setError('');try{await fn();await refresh();await onChanged()}catch(error){setError((error as Error).message)}finally{setBusy(false)}}
  if(!draft||!catalog)return error?<p role="alert" className="text-sm text-red-700">{error}</p>:null;
  const resources=(kind:string)=>catalog.project?.resources.filter(r=>r.kind===kind)||[];
  const actions=catalog.executors.find(e=>e.id===draft.executor)?.actions||[];
  const section='rounded border border-[#dfe1e6] bg-white/50 p-3';
  const textList=(text:string)=>text.split('\n').map(x=>x.trim()).filter(Boolean);
  const context=(patch:Partial<ExecutionConfig['context']>)=>edit({context:{...draft.context,...patch}});
  return <section className="space-y-2" aria-label="Capacidades do cartão">
    {error&&<p role="alert" className="rounded bg-red-50 p-2 text-sm text-red-700">{error}</p>}
    <details className={section}><summary className="cursor-pointer text-sm font-semibold">Execução opcional {draft.enabled&&<span className="ml-2 text-xs font-normal">{executionStatus[details?.result.status||'idle']}</span>}</summary><fieldset disabled={Boolean(active)} className="mt-3 space-y-3 disabled:opacity-60">
      <label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.enabled} onChange={e=>edit({enabled:e.target.checked})}/>Habilitar execução neste cartão</label>
      <Select label="Projeto" value={draft.project_id||''} options={catalog.projects} onChange={id=>edit({project_id:id||null,agent:null,skills:[],context:{},integrations:[]})}/>
      {!catalog.projects.length&&<p className="text-xs">Cadastre a pasta do projeto em <a href="/profile" className="text-[#0c66e4] underline">Perfil</a>.</p>}
      {catalog.project?.warnings.map((warning,i)=><p key={i} className="text-xs text-red-700">{warning}</p>)}
      <div className="grid gap-3 sm:grid-cols-2"><Select label="Agente" value={draft.agent||''} options={resources('agents')} onChange={agent=>edit({agent:agent||null})}/><Select label="Executor" value={draft.executor||''} options={catalog.executors} onChange={executor=>edit({executor:executor||null,action:null})}/><Select label="Ação de execução" value={draft.action||''} options={actions} onChange={action=>edit({action:action||null})}/><Select label="Modo" value={draft.mode} options={[{id:'manual',name:'Manual'},{id:'automatic',name:'Automático por regras'}]} onChange={mode=>edit({mode:mode==='automatic'?'automatic':'manual'})}/></div>
      <Multi label="Skills" options={resources('skills')} value={draft.skills} onChange={skills=>edit({skills})}/>
      <label className="block text-xs font-semibold">Pasta de trabalho (relativa ao projeto)<input className={input+' mt-1'} value={draft.working_directory} onChange={e=>edit({working_directory:e.target.value})}/></label>
      <Multi label="Permissões explícitas" value={draft.permissions} options={catalog.permissions.map(id=>({id,name:({'filesystem.read':'Ler arquivos','filesystem.write':'Alterar arquivos','process.execute':'Executar processos','execution.automatic':'Permitir execução automática'} as Record<string,string>)[id]||id}))} onChange={permissions=>edit({permissions})}/>
      <p className="text-xs text-[#626f86]">As permissões também precisam estar autorizadas no projeto e no agente. A execução de processos usa o sandbox do executor.</p>
    </fieldset></details>
    <details className={section}><summary className="cursor-pointer text-sm font-semibold">Contexto</summary><fieldset disabled={Boolean(active)} className="mt-3 space-y-3"><Multi label="Knowledge" value={draft.context.knowledge||[]} options={resources('knowledge')} onChange={knowledge=>context({knowledge})}/><Multi label="Rules" value={draft.context.rules||[]} options={resources('rules')} onChange={rules=>context({rules})}/><label className="block text-xs font-semibold">Arquivos (um caminho relativo por linha)<textarea className={input+' mt-1'} rows={2} value={draft.context.files?.join('\n')||''} onChange={e=>context({files:textList(e.target.value)})}/></label><Multi label="Cartões de contexto deste quadro" value={draft.context.cards||[]} options={(board.lists||[]).flatMap(l=>l.cards).filter(c=>c.id!==card.id).map(c=>({id:c.id,name:c.title}))} onChange={cards=>context({cards})}/><label className="block text-xs font-semibold">Instruções adicionais<textarea rows={3} className={input+' mt-1'} value={draft.context.instructions||''} onChange={e=>context({instructions:e.target.value})}/></label><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={Boolean(draft.context.include_agents_md)} onChange={e=>context({include_agents_md:e.target.checked})}/>Incluir orientação geral do AGENTS.md</label></fieldset></details>
    <details className={section}><summary className="cursor-pointer text-sm font-semibold">Integrações ({draft.integrations.length})</summary><fieldset disabled={Boolean(active)} className="mt-3 space-y-3">{draft.integrations.map((integration,index)=>{const plugin=catalog.plugins.find(p=>p.id===integration.plugin),action=plugin?.actions.find(a=>a.id===integration.action);const change=(patch:Partial<typeof integration>)=>edit({integrations:draft.integrations.map((x,i)=>i===index?{...x,...patch}:x)});return <div key={index} className="space-y-2 rounded border p-2"><Select label="Plugin" value={integration.plugin} options={catalog.plugins} onChange={plugin=>change({plugin,action:'',config:{}})}/><Select label="Capacidade" value={integration.action} options={plugin?.actions||[]} onChange={action=>change({action,config:{}})}/>{Object.entries(action?.inputSchema.properties||{}).map(([name,schema])=><label key={name} className="block text-xs font-semibold">{name}<input className={input} type={schema.type==='number'?'number':'text'} value={String(integration.config?.[name]||'')} onChange={e=>change({config:{...integration.config,[name]:schema.type==='number'?Number(e.target.value):e.target.value}})}/></label>)}<button type="button" className="text-xs text-red-700" onClick={()=>edit({integrations:draft.integrations.filter((_,i)=>i!==index)})}>Remover integração</button></div>})}<button disabled={draft.integrations.length>=10||!catalog.plugins.length} className="text-sm text-[#0c66e4]" onClick={()=>edit({integrations:[...draft.integrations,{plugin:catalog.plugins[0]?.id||'',action:catalog.plugins[0]?.actions[0]?.id||'',config:{}}]})}>Adicionar integração</button><p className="text-xs text-[#626f86]">Credenciais ficam no servidor. Somente capacidades registradas e habilitadas no projeto podem executar.</p></fieldset></details>
    <details className={section}><summary className="cursor-pointer text-sm font-semibold">Automações</summary><fieldset disabled={Boolean(active)} className="mt-3 space-y-3">{(['on_success_list_id','on_failure_list_id'] as const).map(key=><Select key={key} label={key==='on_success_list_id'?'Mover após sucesso':'Mover após falha'} value={draft.automation[key]||''} options={(board.lists||[]).map(l=>({id:l.id,name:l.title}))} onChange={id=>{const automation={...draft.automation};if(id)automation[key]=id;else delete automation[key];edit({automation})}}/>)}<p className="text-xs text-[#626f86]">Regras do quadro também podem reagir ao início, sucesso ou falha e executar o agente configurado, quando o modo automático estiver autorizado.</p>{resources('automations').map(resource=><button key={resource.id} className="block text-sm text-[#0c66e4]" disabled={busy} onClick={()=>void work(()=>send(`/execution/projects/${project}/automations/${resource.id}`,'POST',{board_id:board.id}))}>Importar regra pausada: {resource.name}</button>)}</fieldset></details>
    {dirty&&<button className={button} disabled={busy||Boolean(active)} onClick={()=>void work(async()=>{const saved=await send<ExecutionConfig>(`/cards/${card.id}/execution`,'PATCH',draft);setDraft(saved);setDirty(false)})}>Salvar capacidades</button>}
    {details?.execution.enabled&&<div className="flex flex-wrap items-center gap-2"><button className={button} disabled={busy||Boolean(active)||dirty} onClick={()=>void work(()=>send(`/cards/${card.id}/runs`,'POST',{request_key:crypto.randomUUID()}))}>{active?'Executando…':'Executar'}</button>{active&&<button className="text-sm text-red-700" disabled={busy} onClick={()=>void work(()=>send(`/execution/runs/${details.runs.find(r=>['queued','running'].includes(r.status))!.id}/cancel`,'POST'))}>Cancelar execução</button>}<span className="text-xs">{executionStatus[details.result.status]}</span></div>}
    <details className={section}><summary className="cursor-pointer text-sm font-semibold">Resultado · {executionStatus[details?.result.status||'idle']}</summary><div className="mt-3 space-y-2">{details?.result.summary&&<p className="whitespace-pre-wrap break-words text-sm">{details.result.summary}</p>}{details?.result.error&&<p className="text-sm text-red-700">{details.result.error}</p>}{details?.result.outputs?.map((output,i)=><ExecutionOutput key={i} output={output}/>)}</div></details>
    <details className={section}><summary className="cursor-pointer text-sm font-semibold">Histórico de execuções ({details?.runs.length||0})</summary><div className="mt-3 space-y-2">{details?.runs.map(run=><button key={run.id} className="block w-full rounded border bg-white p-2 text-left text-xs" onClick={()=>void work(async()=>setSelected(await api<Run>(`/execution/runs/${run.id}`)))}>{run.agent||run.executor} · {executionStatus[run.status]} · {new Date(run.created_at).toLocaleString('pt-BR')}</button>)}{selected&&<div className="space-y-2 rounded bg-[#e9eaed] p-3"><p className="break-all text-xs">Run {selected.id} · etapa: {selected.stage}</p>{selected.error&&<p className="text-sm text-red-700">{selected.error}</p>}{selected.logs?.map((log,index)=><p key={index} className="break-words text-xs">{new Date(log.created_at).toLocaleTimeString('pt-BR')} · {log.stage}: {log.message}</p>)}{selected.output?.outputs.map((output,i)=><ExecutionOutput key={i} output={output}/>)}</div>}</div></details>
  </section>;
}
