'use client';
import { useCallback, useEffect, useState } from 'react';
import { ArrowDown, ArrowUp, Download, ExternalLink, File, Image as ImageIcon, Link2, Paperclip, Trash2 } from 'lucide-react';
import { api, attachmentBlob, Attachment, Board, Card, labelColors, send, uploadCardFiles } from '@/lib/api';

type Mutate=(action:()=>Promise<unknown>)=>Promise<void>;
const isPreviewable=(item:Attachment)=>Boolean(item.mime_type?.startsWith('image/')||item.mime_type==='application/pdf'||item.mime_type==='text/plain');

function AttachmentRow({item,index,total,card,mutate}: {item:Attachment;index:number;total:number;card:Card;mutate:Mutate}){
  const [blobUrl,setBlobUrl]=useState('');const [preview,setPreview]=useState(false);const [editing,setEditing]=useState(false);const [name,setName]=useState(item.name);const [textPreview,setTextPreview]=useState('');
  const attachmentId=item.id,attachmentKind=item.kind,attachmentMime=item.mime_type;
  useEffect(()=>{if(attachmentKind!=='file'||!(attachmentMime?.startsWith('image/')||attachmentMime==='application/pdf'||attachmentMime==='text/plain'))return;let current=true;let url='';attachmentBlob(attachmentId).then(blob=>{url=URL.createObjectURL(blob);if(current)setBlobUrl(url);else URL.revokeObjectURL(url)}).catch(()=>{});return()=>{current=false;if(url)URL.revokeObjectURL(url)}},[attachmentId,attachmentKind,attachmentMime]);
  async function download(){const blob=await attachmentBlob(item.id);const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download=item.name;anchor.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  async function show(){if(item.kind!=='file')return;if(item.mime_type==='text/plain'){const blob=await attachmentBlob(item.id);setTextPreview((await blob.text()).slice(0,100000))}setPreview(true)}
  const internal=item.kind==='board'||item.kind==='card';
  const href=internal?item.url||'#':item.kind==='url'?item.url||'#':'';
  return <div className="rounded border border-[#dfe1e6] bg-white p-2 text-xs"><div className="flex items-start gap-2"><div className="flex h-12 w-16 shrink-0 items-center justify-center rounded bg-[#f1f2f4]" style={item.mime_type?.startsWith('image/')&&blobUrl?{backgroundImage:`url("${blobUrl}")`,backgroundPosition:'center',backgroundSize:'cover'}:undefined}>{!item.mime_type?.startsWith('image/')&&(item.kind==='file'?<File size={20}/>:<Link2 size={20}/>)}</div><div className="min-w-0 flex-1">{editing?<form onSubmit={async event=>{event.preventDefault();if(!name.trim())return;await mutate(()=>send('/attachments/'+item.id,'PATCH',{name}));setEditing(false)}}><input autoFocus value={name} onChange={event=>setName(event.target.value)} maxLength={255} className="w-full rounded border p-1"/><button className="mt-1 text-[#0c66e4]">Salvar</button></form>:<button type="button" onClick={()=>setEditing(true)} title="Renomear anexo" className="max-w-full truncate text-left font-semibold hover:underline">{item.name}</button>}<p className="truncate text-[#626f86]">{item.kind==='file'?`${item.mime_type||'Arquivo'} · ${Math.ceil((item.size_bytes||0)/1024)} KB`:item.kind==='board'?'Quadro Orbit':item.kind==='card'?'Cartão Orbit':item.url}</p><div className="mt-1 flex flex-wrap gap-2">{item.kind==='file'?<><button type="button" onClick={()=>void download()} className="inline-flex items-center gap-1 text-[#0c66e4]"><Download size={12}/> Baixar</button>{isPreviewable(item)&&<button type="button" onClick={()=>void show()} className="text-[#0c66e4]">Visualizar</button>}{item.mime_type?.startsWith('image/')&&<button type="button" onClick={()=>void mutate(()=>send('/cards/'+card.id+'/cover','PATCH',{attachment_id:item.id,color:null,size:card.cover_size||'normal'}))} className="text-[#0c66e4]">Usar como capa</button>}</>:<a href={href} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-[#0c66e4]"><ExternalLink size={12}/> Abrir</a>}</div></div><div className="flex shrink-0 flex-col gap-1"><button type="button" title="Mover anexo para cima" disabled={index===0} onClick={()=>void mutate(()=>send('/attachments/'+item.id,'PATCH',{position:index-1}))} className="disabled:opacity-30"><ArrowUp size={13}/></button><button type="button" title="Mover anexo para baixo" disabled={index===total-1} onClick={()=>void mutate(()=>send('/attachments/'+item.id,'PATCH',{position:index+1}))} className="disabled:opacity-30"><ArrowDown size={13}/></button><button type="button" title="Excluir anexo" onClick={()=>{if(confirm('Excluir este anexo?'))void mutate(()=>send('/attachments/'+item.id,'DELETE'))}} className="text-[#ae2a19]"><Trash2 size={13}/></button></div></div>
    {preview&&<div className="fixed inset-0 z-[80] flex items-center justify-center bg-black/75 p-3" onClick={()=>setPreview(false)}><div className="relative max-h-[92vh] w-full max-w-5xl overflow-auto rounded bg-white p-3" onClick={event=>event.stopPropagation()}><div className="mb-2 flex items-center justify-between gap-2"><strong className="truncate">{item.name}</strong><button onClick={()=>setPreview(false)} className="rounded bg-[#e9eaed] px-2 py-1">Fechar</button></div>{item.mime_type?.startsWith('image/')&&blobUrl?<div className="h-[75vh] bg-contain bg-center bg-no-repeat" style={{backgroundImage:`url("${blobUrl}")`}}/>:item.mime_type==='application/pdf'&&blobUrl?<iframe title={item.name} src={blobUrl} className="h-[75vh] w-full"/>:<pre className="max-h-[75vh] overflow-auto whitespace-pre-wrap text-xs">{textPreview}</pre>}</div></div>}
  </div>;
}

export function CardAttachments({card,board,attachments,mutate}: {card:Card;board:Board;attachments:Attachment[];mutate:Mutate}){
  const [url,setUrl]=useState('');const [name,setName]=useState('');const [kind,setKind]=useState<'url'|'board'|'card'>('url');const [boards,setBoards]=useState<Board[]>([]);const [targetBoard,setTargetBoard]=useState(board.id);const [targetCard,setTargetCard]=useState('');const [targetCards,setTargetCards]=useState<Card[]>([]);const [dragging,setDragging]=useState(false);const [uploadError,setUploadError]=useState('');
  useEffect(()=>{api<Board[]>('/boards').then(setBoards).catch(()=>{})},[]);
  useEffect(()=>{api<Board>('/boards/'+targetBoard).then(result=>setTargetCards(result.lists?.flatMap(list=>list.cards)||[])).catch(()=>setTargetCards([]))},[targetBoard]);
  const upload=useCallback(async(files:FileList|File[])=>{try{await mutate(()=>uploadCardFiles(card.id,files));setUploadError('')}catch(error){setUploadError((error as Error).message)}},[card.id,mutate]);
  useEffect(()=>{const handle=(event:ClipboardEvent)=>{const images=Array.from(event.clipboardData?.files||[]).filter(file=>file.type.startsWith('image/'));if(images.length){event.preventDefault();void upload(images)}};window.addEventListener('paste',handle);return()=>window.removeEventListener('paste',handle)},[upload]);
  const coverColors=Object.entries(labelColors).filter(([color])=>color!=='none'&&!color.includes('_'));
  async function addLink(event:React.FormEvent){event.preventDefault();if(kind==='url'){await mutate(()=>send('/cards/'+card.id+'/attachments','POST',{kind,name:name.trim()||url,url}));setUrl('');setName('')}else{const targetId=kind==='board'?targetBoard:targetCard;if(!targetId)return;const title=kind==='board'?boards.find(item=>item.id===targetId)?.title:targetCards.find(item=>item.id===targetId)?.title;await mutate(()=>send('/cards/'+card.id+'/attachments','POST',{kind,target_id:targetId,name:name.trim()||title||kind}));setName('')}}
  return <section id="card-attachments"><h3 className="mb-3 flex items-center gap-2 font-semibold"><Paperclip size={21}/> Anexos e capa</h3><div className="space-y-3 sm:pl-8"><div onDragEnter={event=>{event.preventDefault();setDragging(true)}} onDragOver={event=>event.preventDefault()} onDragLeave={event=>{event.preventDefault();setDragging(false)}} onDrop={event=>{event.preventDefault();setDragging(false);void upload(event.dataTransfer.files)}} className={`rounded-lg border-2 border-dashed p-3 text-sm ${dragging?'border-[#0c66e4] bg-[#e9f2ff]':'border-[#8590a2]'}`}><label className="flex cursor-pointer items-center gap-2 font-semibold text-[#0c66e4]"><ImageIcon size={17}/> Enviar arquivos<input type="file" multiple onChange={event=>{if(event.target.files)void upload(event.target.files);event.target.value=''}} className="sr-only"/></label><p className="mt-1 text-xs text-[#626f86]">Arraste arquivos aqui ou cole uma imagem. Imagens até 2 MB; outros arquivos até 10 MB.</p></div>
    {uploadError&&<p role="alert" className="rounded bg-[#ffebe6] p-2 text-xs text-[#ae2a19]">{uploadError}</p>}
    <form onSubmit={event=>void addLink(event)} className="space-y-2 rounded-lg bg-[#f1f2f4] p-3"><div className="flex flex-wrap gap-2"><select value={kind} onChange={event=>setKind(event.target.value as typeof kind)} aria-label="Tipo de link" className="rounded border bg-white p-1.5 text-xs"><option value="url">URL externa</option><option value="board">Quadro Orbit</option><option value="card">Cartão Orbit</option></select><input value={name} onChange={event=>setName(event.target.value)} maxLength={255} placeholder="Nome (opcional)" className="min-w-32 flex-1 rounded border bg-white p-1.5 text-xs"/></div>{kind==='url'?<input type="url" required value={url} onChange={event=>setUrl(event.target.value)} placeholder="https://..." className="w-full rounded border bg-white p-1.5 text-xs"/>:<div className="flex flex-wrap gap-2"><select value={targetBoard} onChange={event=>{setTargetBoard(event.target.value);setTargetCard('')}} className="min-w-0 flex-1 rounded border bg-white p-1.5 text-xs">{boards.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select>{kind==='card'&&<select value={targetCard} onChange={event=>setTargetCard(event.target.value)} className="min-w-0 flex-1 rounded border bg-white p-1.5 text-xs"><option value="">Selecione o cartão</option>{targetCards.map(item=><option key={item.id} value={item.id}>{item.title}</option>)}</select>}</div>}<button disabled={kind==='url'?!url:kind==='card'?!targetCard:!targetBoard} className="rounded bg-[#0c66e4] px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-50">Anexar link</button></form>
    <div className="space-y-2">{attachments.map((item,index)=><AttachmentRow key={item.id+item.name} item={item} index={index} total={attachments.length} card={card} mutate={mutate}/>)}</div>
    <div className="rounded-lg border border-[#dfe1e6] p-3"><p className="mb-2 text-xs font-semibold">Capa do cartão</p><div className="flex flex-wrap gap-1">{coverColors.map(([color,hex])=><button key={color} type="button" title={color} onClick={()=>void mutate(()=>send('/cards/'+card.id+'/cover','PATCH',{color,attachment_id:null,size:card.cover_size||'normal'}))} className="h-7 w-10 rounded" style={{background:hex,outline:card.cover_color===color&&!card.cover_attachment_id?'2px solid #172b4d':undefined}}/>)}</div><div className="mt-2 flex flex-wrap gap-2"><button type="button" onClick={()=>void mutate(()=>send('/cards/'+card.id+'/cover','PATCH',{color:null,attachment_id:null,size:'normal'}))} className="rounded bg-[#e9eaed] px-2 py-1 text-xs">Remover capa</button><select value={card.cover_size||'normal'} onChange={event=>void mutate(()=>send('/cards/'+card.id+'/cover','PATCH',{color:card.cover_color,attachment_id:card.cover_attachment_id,size:event.target.value}))} className="rounded border bg-white p-1 text-xs"><option value="normal">Capa parcial</option><option value="full">Capa na frente inteira</option></select></div></div>
  </div></section>;
}
