'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {api,send} from '@/lib/api';

type Item={id:string;name:string};
type Credential=Item&{kind:string};
type Server=Item&{host:string;host_fingerprint:string};
type Remote=Item&{repository_id:string;url:string;default_branch:string|null};
type Environment=Item&{slug:string};
type Target=Item&{environment_id:string};
type Pipeline=Item&{enabled:boolean;trigger_type:string;description:string;execution_policy:{bypassEnabled?:boolean}};
type Repository=Item&{branches:string[]};
type Config={credentials:Credential[];servers:Server[];remotes:Remote[];environments:Environment[];targets:Target[];pipelines:Pipeline[]};
type Catalog={stepTypes:Array<{type:string;category:string;schema:{required?:string[];properties:Record<string,{type?:string;enum?:string[]}>}}> ;bypassEnabled:boolean};
type Step={id:string;type:string;name:string;config:Record<string,unknown>;timeout_ms:number;failure_policy:string;max_attempts:number;retry_delay_ms:number;bypass_policy:string;requires:string[]};
type Run={id:string;pipeline_name?:string;pipeline_id:string;status:string;mode:string;trigger_type:string;triggered_by:string;card_id?:string|null;current_step_id?:string|null;started_at:string;finished_at?:string|null;bypass_reason?:string|null};
type RunDetail=Run&{steps:Array<{id:string;step_snapshot:Step;status:string;stdout:string;stderr:string;error:string|null;outputs:Record<string,unknown>;metadata:Record<string,unknown>}>;approvals:Array<{step_id:string;requested_at:string;approved_at:string|null;rejected_at:string|null;comment:string|null}>;audit:Array<{event:string;details:Record<string,unknown>;created_at:string}>};
const field='w-full rounded border border-[#8590a2] bg-white px-2 py-1.5 text-xs';
const button='rounded bg-[#403294] px-3 py-1.5 text-xs font-semibold text-white disabled:opacity-50';
const list=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean);
const configValue=(value:unknown)=>Array.isArray(value)?value.join(', '):value===undefined?'':String(value);

export function DeliveryProjectSettings({projectId}:{projectId:string}){
  const [open,setOpen]=useState(false);
  return <div className="mt-3 max-w-3xl rounded-lg border border-[#dfe1e6] p-3"><button type="button" onClick={()=>setOpen(value=>!value)} className="text-left text-xs font-semibold text-[#403294]">Delivery Pipelines {open?'▴':'▾'}</button>{open&&<Settings projectId={projectId}/>}</div>;
}
function Settings({projectId}:{projectId:string}){
  const [config,setConfig]=useState<Config|null>(null),[repos,setRepos]=useState<Repository[]>([]),[catalog,setCatalog]=useState<Catalog|null>(null),[runs,setRuns]=useState<Run[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState<string|null>(null),[runId,setRunId]=useState<string|null>(null);
  const [credentialName,setCredentialName]=useState(''),[credentialKind,setCredentialKind]=useState('SSH_PRIVATE_KEY'),[credentialValue,setCredentialValue]=useState('');
  const [serverName,setServerName]=useState(''),[serverHost,setServerHost]=useState(''),[serverPort,setServerPort]=useState('22'),[serverUser,setServerUser]=useState(''),[serverCredential,setServerCredential]=useState(''),[serverFingerprint,setServerFingerprint]=useState('');
  const [remoteRepo,setRemoteRepo]=useState(''),[remoteName,setRemoteName]=useState(''),[remoteUrl,setRemoteUrl]=useState(''),[remoteCredential,setRemoteCredential]=useState(''),[remoteBranch,setRemoteBranch]=useState('');
  const [environmentName,setEnvironmentName]=useState(''),[environmentSlug,setEnvironmentSlug]=useState('');
  const [targetName,setTargetName]=useState(''),[targetEnvironment,setTargetEnvironment]=useState(''),[targetExecutor,setTargetExecutor]=useState('ssh'),[targetServer,setTargetServer]=useState(''),[targetRepo,setTargetRepo]=useState(''),[targetRemote,setTargetRemote]=useState(''),[targetBranch,setTargetBranch]=useState(''),[targetDirectory,setTargetDirectory]=useState(''),[targetBuild,setTargetBuild]=useState(''),[targetRestart,setTargetRestart]=useState('');
  const [pipelineName,setPipelineName]=useState(''),[pipelineTrigger,setPipelineTrigger]=useState('manual');
  const load=useCallback(async()=>{const [settings,git,runs,catalog]=await Promise.all([api<Config>(`/delivery/projects/${projectId}`),api<{repositories:Repository[]}>(`/git/projects/${projectId}`),api<Run[]>(`/delivery/projects/${projectId}/runs`),api<Catalog>('/delivery/catalog')]);setConfig(settings);setRepos(git.repositories);setRuns(runs);setCatalog(catalog)},[projectId]);
  useEffect(()=>{let active=true;Promise.all([api<Config>(`/delivery/projects/${projectId}`),api<{repositories:Repository[]}>(`/git/projects/${projectId}`),api<Run[]>(`/delivery/projects/${projectId}/runs`),api<Catalog>('/delivery/catalog')]).then(([settings,git,history,catalog])=>{if(active){setConfig(settings);setRepos(git.repositories);setRuns(history);setCatalog(catalog)}}).catch(reason=>{if(active)setError((reason as Error).message)});return()=>{active=false}},[projectId]);
  async function act(action:()=>Promise<unknown>){setBusy(true);try{await action();await load();setError('')}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  const submit=(event:FormEvent,action:()=>Promise<unknown>)=>{event.preventDefault();void act(action)};
  const filteredRemotes=config?.remotes.filter(item=>item.repository_id===targetRepo)||[];
  return <div className="mt-3 space-y-4 text-xs">
    <p className="text-[#626f86]">Componha Git, comandos, deploys, testes, aprovações e promoções. O bypass exige permissão explícita e motivo.</p>
    {error&&<p role="alert" className="rounded bg-[#ffebe6] p-2 text-[#ae2a19]">{error}</p>}
    {!config||!catalog?<p>Carregando...</p>:<>
      <details><summary className="cursor-pointer font-semibold">Credenciais e servidores</summary><div className="mt-2 space-y-3">
        <div>{config.credentials.map(item=><span key={item.id} className="mr-2">{item.name} ({item.kind})</span>)}</div>
        <form onSubmit={event=>submit(event,async()=>{await send('/delivery/credentials','POST',{name:credentialName,kind:credentialKind,value:credentialValue});setCredentialValue('');setCredentialName('')})} className="grid gap-2 sm:grid-cols-2"><input required className={field} placeholder="Nome da credencial" value={credentialName} onChange={event=>setCredentialName(event.target.value)}/><select className={field} value={credentialKind} onChange={event=>setCredentialKind(event.target.value)}>{['SSH_PRIVATE_KEY','SSH_PASSWORD','GIT_TOKEN','GIT_SSH_KEY'].map(kind=><option key={kind}>{kind}</option>)}</select><textarea required className={`${field} sm:col-span-2`} placeholder="Valor do segredo" value={credentialValue} onChange={event=>setCredentialValue(event.target.value)}/><button disabled={busy} className={button}>Salvar credencial</button></form>
        <div>{config.servers.map(server=><div key={server.id} className="flex justify-between gap-2 rounded bg-[#f7f8fa] p-2"><span>{server.name} · {server.host}</span><button type="button" onClick={()=>void act(async()=>{const test=await send<{connected:boolean;latency:number;error:string|null}>(`/delivery/servers/${server.id}/test`,'POST',{});if(!test.connected)throw new Error(test.error||'Conexão falhou.');window.alert(`Conectado em ${test.latency} ms`)})}>Testar conexão</button></div>)}</div>
        <form onSubmit={event=>submit(event,async()=>{await send('/delivery/servers','POST',{name:serverName,host:serverHost,port:Number(serverPort),username:serverUser,credentialId:serverCredential,fingerprint:serverFingerprint});setServerName('')})} className="grid gap-2 sm:grid-cols-2"><input required className={field} placeholder="Nome do servidor" value={serverName} onChange={event=>setServerName(event.target.value)}/><input required className={field} placeholder="Host" value={serverHost} onChange={event=>setServerHost(event.target.value)}/><input required className={field} placeholder="Usuário SSH" value={serverUser} onChange={event=>setServerUser(event.target.value)}/><input required className={field} type="number" min="1" max="65535" value={serverPort} onChange={event=>setServerPort(event.target.value)}/><select required className={field} value={serverCredential} onChange={event=>setServerCredential(event.target.value)}><option value="">Credencial SSH</option>{config.credentials.filter(item=>item.kind.startsWith('SSH_')).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input required className={field} placeholder="SHA-256 do host (64 caracteres hex)" value={serverFingerprint} onChange={event=>setServerFingerprint(event.target.value)}/><button disabled={busy} className={button}>Adicionar servidor</button></form>
      </div></details>
      <details><summary className="cursor-pointer font-semibold">Git remotes</summary><div className="mt-2 space-y-2"><div>{config.remotes.map(remote=><div key={remote.id}>{remote.name} · {remote.url} · {repos.find(repo=>repo.id===remote.repository_id)?.name}</div>)}</div><form onSubmit={event=>submit(event,async()=>{await send(`/delivery/repositories/${remoteRepo}/remotes`,'POST',{name:remoteName,url:remoteUrl,credentialId:remoteCredential||undefined,defaultBranch:remoteBranch||undefined});setRemoteName('');setRemoteUrl('')})} className="grid gap-2 sm:grid-cols-2"><select required className={field} value={remoteRepo} onChange={event=>setRemoteRepo(event.target.value)}><option value="">Repositório</option>{repos.map(repo=><option key={repo.id} value={repo.id}>{repo.name}</option>)}</select><input required className={field} placeholder="Nome do remote" value={remoteName} onChange={event=>setRemoteName(event.target.value)}/><input required className={field} placeholder="URL HTTPS ou SSH" value={remoteUrl} onChange={event=>setRemoteUrl(event.target.value)}/><select className={field} value={remoteCredential} onChange={event=>setRemoteCredential(event.target.value)}><option value="">Sem credencial Orbit</option>{config.credentials.filter(item=>item.kind.startsWith('GIT_')).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={field} placeholder="Branch padrão opcional" value={remoteBranch} onChange={event=>setRemoteBranch(event.target.value)}/><button disabled={busy} className={button}>Adicionar remote</button></form></div></details>
      <details><summary className="cursor-pointer font-semibold">Ambientes e destinos</summary><div className="mt-2 space-y-3"><div>{config.environments.map(item=><span key={item.id} className="mr-2">{item.name} ({item.slug})</span>)}</div><form onSubmit={event=>submit(event,async()=>{await send(`/delivery/projects/${projectId}/environments`,'POST',{name:environmentName,slug:environmentSlug});setEnvironmentName('');setEnvironmentSlug('')})} className="grid gap-2 sm:grid-cols-2"><input required className={field} placeholder="Nome do ambiente" value={environmentName} onChange={event=>setEnvironmentName(event.target.value)}/><input required className={field} placeholder="slug" value={environmentSlug} onChange={event=>setEnvironmentSlug(event.target.value)}/><button disabled={busy} className={button}>Adicionar ambiente</button></form>
        <div>{config.targets.map(item=><div key={item.id}>{item.name} · {config.environments.find(env=>env.id===item.environment_id)?.name}</div>)}</div>
        <form onSubmit={event=>submit(event,async()=>{await send(`/delivery/projects/${projectId}/targets`,'POST',{name:targetName,environmentId:targetEnvironment,executor:targetExecutor,serverId:targetServer||undefined,repositoryId:targetRepo||undefined,remoteId:targetRemote||undefined,branch:targetBranch||undefined,workingDirectory:targetDirectory,buildCommands:targetBuild.split('\n').map(item=>item.trim()).filter(Boolean),restartCommand:targetRestart||undefined});setTargetName('')})} className="grid gap-2 sm:grid-cols-2"><input required className={field} placeholder="Nome do destino" value={targetName} onChange={event=>setTargetName(event.target.value)}/><select required className={field} value={targetEnvironment} onChange={event=>setTargetEnvironment(event.target.value)}><option value="">Environment</option>{config.environments.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={field} value={targetExecutor} onChange={event=>setTargetExecutor(event.target.value)}><option value="ssh">SSH</option><option value="local">Local</option></select><select className={field} value={targetServer} onChange={event=>setTargetServer(event.target.value)}><option value="">Servidor</option>{config.servers.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={field} value={targetRepo} onChange={event=>{setTargetRepo(event.target.value);setTargetRemote('')}}><option value="">Repositório</option>{repos.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><select className={field} value={targetRemote} onChange={event=>setTargetRemote(event.target.value)}><option value="">Remote</option>{filteredRemotes.map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><input className={field} placeholder="Branch" value={targetBranch} onChange={event=>setTargetBranch(event.target.value)}/><input required className={field} placeholder="Pasta de trabalho" value={targetDirectory} onChange={event=>setTargetDirectory(event.target.value)}/><textarea className={field} placeholder="Comandos de build, um por linha" value={targetBuild} onChange={event=>setTargetBuild(event.target.value)}/><input className={field} placeholder="Comando de restart opcional" value={targetRestart} onChange={event=>setTargetRestart(event.target.value)}/><button disabled={busy} className={button}>Adicionar destino</button></form>
      </div></details>
      <div className="space-y-2"><strong>Pipelines</strong>{config.pipelines.map(pipeline=><div key={pipeline.id} className="rounded border border-[#dfe1e6] p-2"><div className="flex items-center justify-between"><span>{pipeline.name} · {pipeline.trigger_type} · {pipeline.enabled?'ativo':'inativo'}</span><button type="button" onClick={()=>setSelected(pipeline.id===selected?null:pipeline.id)} className="text-[#403294]">{pipeline.id===selected?'Fechar':'Editar e executar'}</button></div>{pipeline.id===selected&&<PipelineEditor projectId={projectId} pipeline={pipeline} catalog={catalog} repos={repos} remotes={config.remotes} environments={config.environments} targets={config.targets} servers={config.servers} busy={busy} act={act} onRun={runId=>{void load();setSelected(pipeline.id);setRunId(runId)}}/>}</div>)}
        <form onSubmit={event=>submit(event,async()=>{await send(`/delivery/projects/${projectId}/pipelines`,'POST',{name:pipelineName,triggerType:pipelineTrigger,enabled:false});setPipelineName('')})} className="flex gap-2"><input required className={field} placeholder="Novo pipeline" value={pipelineName} onChange={event=>setPipelineName(event.target.value)}/><select className={field} value={pipelineTrigger} onChange={event=>setPipelineTrigger(event.target.value)}><option value="manual">Manual</option><option value="card.completed">Card concluído</option></select><button disabled={busy} className={button}>Criar</button></form>
      </div>
      <div className="space-y-2"><strong>Execuções recentes</strong>{runs.map(run=><button type="button" key={run.id} onClick={()=>setRunId(run.id)} className="block w-full rounded bg-[#f7f8fa] p-2 text-left">{run.pipeline_name} · {run.status} · {run.mode} · {new Date(run.started_at).toLocaleString('pt-BR')}</button>)}{runId&&<RunView runId={runId} onChange={()=>void load()}/>}</div>
    </>}
  </div>;
}

function PipelineEditor({pipeline,catalog,repos,remotes,environments,targets,servers,busy,act,onRun}:{projectId:string;pipeline:Pipeline;catalog:Catalog;repos:Repository[];remotes:Remote[];environments:Environment[];targets:Target[];servers:Server[];busy:boolean;act:(action:()=>Promise<unknown>)=>Promise<void>;onRun:(id:string)=>void}){
  const [steps,setSteps]=useState<Step[]>([]),[editing,setEditing]=useState<Step|null>(null),[mode,setMode]=useState<'normal'|'bypass'>('normal'),[reason,setReason]=useState(''),[bypass,setBypass]=useState({approvals:false,tests:false,promotions:false,deployments:false,allWorkflowPolicies:false});
  useEffect(()=>{let active=true;void api<Step[]>(`/delivery/pipelines/${pipeline.id}/steps`).then(items=>{if(active)setSteps(items)});return()=>{active=false}},[pipeline.id]);
  const options={repos,remotes,environments,targets,servers};
  const save=async(next:Step[])=>{await act(async()=>{const result=await send<Step[]>(`/delivery/pipelines/${pipeline.id}/steps`,'PUT',{steps:next.map(step=>({id:step.id,type:step.type,name:step.name,config:step.config,timeoutMs:step.timeout_ms,failurePolicy:step.failure_policy,maxAttempts:step.max_attempts,retryDelayMs:step.retry_delay_ms,bypassPolicy:step.bypass_policy,requires:step.requires}))});setSteps(result)})};
  const create=(type:string):Step=>({id:crypto.randomUUID(),type,name:type,config:{},timeout_ms:60000,failure_policy:'stop',max_attempts:1,retry_delay_ms:0,bypass_policy:'deny',requires:[]});
  const reorder=(index:number,delta:number)=>{const next=[...steps],target=index+delta;if(target<0||target>=next.length)return;[next[index],next[target]]=[next[target],next[index]];void save(next)};
  const run=()=>void act(async()=>{const result=await send<{id:string}>(`/delivery/pipelines/${pipeline.id}/runs`,'POST',{mode,bypassOptions:mode==='bypass'?bypass:{},reason:mode==='bypass'?reason:undefined});onRun(result.id)});
  return <div className="mt-2 space-y-3"><label className="flex items-center gap-2"><input type="checkbox" checked={pipeline.enabled} onChange={event=>void act(()=>send(`/delivery/pipelines/${pipeline.id}`,'PATCH',{enabled:event.target.checked}))}/>Ativo</label><label className="ml-3 inline-flex items-center gap-2"><input type="checkbox" checked={pipeline.execution_policy?.bypassEnabled!==false} onChange={event=>void act(()=>send(`/delivery/pipelines/${pipeline.id}`,'PATCH',{executionPolicy:{...pipeline.execution_policy,bypassEnabled:event.target.checked}}))}/>Permitir modo bypass</label><ol className="space-y-1">{steps.map((step,index)=><li key={step.id} className="flex items-center gap-2 rounded bg-[#f7f8fa] p-2"><span>{index+1}. {step.name} <small>({step.type}, bypass {step.bypass_policy})</small></span><button type="button" onClick={()=>reorder(index,-1)}>↑</button><button type="button" onClick={()=>reorder(index,1)}>↓</button><button type="button" onClick={()=>setEditing(step)}>Editar</button><button type="button" onClick={()=>void save(steps.filter(item=>item.id!==step.id))}>Remover</button></li>)}</ol>
    <select className={field} value="" onChange={event=>{if(event.target.value)setEditing(create(event.target.value))}}><option value="">Adicionar step</option>{catalog.stepTypes.map(item=><option key={item.type} value={item.type}>{item.type}</option>)}</select>
    {editing&&<StepEditor key={editing.id} step={editing} catalog={catalog} options={options} onCancel={()=>setEditing(null)} onSave={step=>{void save(steps.some(item=>item.id===step.id)?steps.map(item=>item.id===step.id?step:item):[...steps,step]);setEditing(null)}}/>}
    <div className="rounded border border-[#dfe1e6] p-2"><strong>Executar</strong><div className="mt-2 grid gap-2 sm:grid-cols-2"><select className={field} value={mode} onChange={event=>setMode(event.target.value as 'normal'|'bypass')}><option value="normal">Normal</option>{catalog.bypassEnabled&&<option value="bypass">Bypass</option>}</select>{mode==='bypass'&&<><input required className={field} placeholder="Motivo do bypass" value={reason} onChange={event=>setReason(event.target.value)}/>{(Object.keys(bypass) as Array<keyof typeof bypass>).map(key=><label key={key} className="flex items-center gap-1"><input type="checkbox" checked={bypass[key]} onChange={event=>setBypass(current=>({...current,[key]:event.target.checked}))}/>{key}</label>)}</>}</div><button type="button" disabled={busy||!pipeline.enabled||mode==='bypass'&&!reason.trim()} onClick={run} className={`${button} mt-2`}>Iniciar execução</button><button type="button" className="ml-2 text-[#403294]" onClick={()=>void act(()=>send('/delivery/bypass-permission','POST',{enabled:!catalog.bypassEnabled}))}>{catalog.bypassEnabled?'Revogar permissão de bypass':'Habilitar permissão de bypass'}</button></div>
  </div>;
}

function StepEditor({step,catalog,options,onCancel,onSave}:{step:Step;catalog:Catalog;options:{repos:Repository[];remotes:Remote[];environments:Environment[];targets:Target[];servers:Server[]};onCancel:()=>void;onSave:(step:Step)=>void}){
  const [draft,setDraft]=useState(step),[required,setRequired]=useState(step.requires.join(', ')),[variables,setVariables]=useState(JSON.stringify(step.config.environmentVariables||{},null,2)),[error,setError]=useState('');
  const schema=catalog.stepTypes.find(item=>item.type===draft.type)?.schema;
  const fields=Object.entries(schema?.properties||{});
  const choices=(key:string)=>key==='repositoryId'?options.repos:key==='remoteId'?options.remotes.filter(item=>!draft.config.repositoryId||item.repository_id===draft.config.repositoryId):key==='environmentId'?options.environments:key==='deployTargetId'?options.targets:key==='serverId'?options.servers:[];
  const update=(key:string,value:unknown)=>setDraft(current=>{const config={...current.config};if(value===''||Array.isArray(value)&&value.length===0)delete config[key];else config[key]=value;return {...current,config}});
  const submit=(event:FormEvent)=>{event.preventDefault();try{const config={...draft.config};if(fields.some(([key])=>key==='environmentVariables')){const parsed=JSON.parse(variables) as unknown;if(!parsed||typeof parsed!=='object'||Array.isArray(parsed)||Object.values(parsed).some(value=>typeof value!=='string'))throw new Error('Variáveis devem ser um objeto JSON de textos.');config.environmentVariables=parsed}onSave({...draft,config,requires:list(required)})}catch(reason){setError((reason as Error).message)}};
  return <form onSubmit={submit} className="grid gap-2 rounded border border-[#c7c0ed] p-2 sm:grid-cols-2"><label>Nome<input required className={field} value={draft.name} onChange={event=>setDraft(current=>({...current,name:event.target.value}))}/></label><label>Tipo<input className={field} value={draft.type} readOnly/></label>{fields.map(([key,definition])=><label key={key}>{key}{key==='environmentVariables'?<textarea className={field} value={variables} onChange={event=>setVariables(event.target.value)}/>:choices(key).length?<select required={schema?.required?.includes(key)} className={field} value={configValue(draft.config[key])} onChange={event=>update(key,event.target.value)}><option value="">Selecione</option>{choices(key).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select>:definition.enum?<select className={field} value={configValue(draft.config[key])} onChange={event=>update(key,event.target.value)}><option value="">Selecione</option>{definition.enum.map(value=><option key={value}>{value}</option>)}</select>:key==='command'||key==='message'?<textarea required={schema?.required?.includes(key)} className={field} placeholder={key} value={configValue(draft.config[key])} onChange={event=>update(key,event.target.value)}/>:<input required={schema?.required?.includes(key)} className={field} placeholder={definition.type==='array'?'Separe por vírgula':key} value={configValue(draft.config[key])} onChange={event=>update(key,definition.type==='array'?list(event.target.value):event.target.value)}/>}</label>)}
    <label>Timeout (ms)<input type="number" min="1000" max="1800000" className={field} value={draft.timeout_ms} onChange={event=>setDraft(current=>({...current,timeout_ms:Number(event.target.value)}))}/></label><label>Falha<select className={field} value={draft.failure_policy} onChange={event=>setDraft(current=>({...current,failure_policy:event.target.value}))}><option value="stop">Parar</option><option value="continue">Continuar</option><option value="retry">Tentar novamente</option></select></label><label>Tentativas<input type="number" min="1" max="5" className={field} value={draft.max_attempts} onChange={event=>setDraft(current=>({...current,max_attempts:Number(event.target.value)}))}/></label><label>Intervalo de retry (ms)<input type="number" min="0" max="60000" className={field} value={draft.retry_delay_ms} onChange={event=>setDraft(current=>({...current,retry_delay_ms:Number(event.target.value)}))}/></label><label>Bypass<select className={field} value={draft.bypass_policy} onChange={event=>setDraft(current=>({...current,bypass_policy:event.target.value}))}><option value="deny">Negar</option><option value="allow">Permitir</option><option value="allow_with_permission">Exigir permissão</option></select></label><label className="sm:col-span-2">Outputs obrigatórios (context.chave ou steps.ID.chave)<input className={field} value={required} onChange={event=>setRequired(event.target.value)}/></label>{error&&<p role="alert" className="text-[#ae2a19] sm:col-span-2">{error}</p>}<div className="flex gap-2"><button className={button}>Salvar step</button><button type="button" onClick={onCancel}>Cancelar</button></div></form>;
}

function RunView({runId,onChange}:{runId:string;onChange:()=>void}){
  const [run,setRun]=useState<RunDetail|null>(null),[error,setError]=useState(''),[comment,setComment]=useState('');
  useEffect(()=>{let active=true;const fetchRun=()=>void api<RunDetail>(`/delivery/runs/${runId}`).then(value=>{if(active)setRun(value)}).catch(reason=>{if(active)setError((reason as Error).message)});fetchRun();const timer=setInterval(fetchRun,3000);return()=>{active=false;clearInterval(timer)}},[runId]);
  async function decision(approve:boolean){try{await send(`/delivery/runs/${runId}/${approve?'approve':'reject'}`,'POST',{comment});setRun(await api<RunDetail>(`/delivery/runs/${runId}`));onChange()}catch(reason){setError((reason as Error).message)}}
  if(!run)return <p>{error||'Carregando execução...'}</p>;
  return <div className="rounded border border-[#dfe1e6] p-3"><div className="font-semibold">{run.pipeline_name||'Pipeline'} · Execução {run.id.slice(0,8)} · {run.status} {run.mode==='bypass'?'⚠ BYPASS MODE':''}</div><p>Modo: {run.mode} · Trigger: {run.trigger_type} · Iniciada por: {run.triggered_by} · Início: {new Date(run.started_at).toLocaleString('pt-BR')}{run.finished_at?` · Duração: ${Math.round((new Date(run.finished_at).getTime()-new Date(run.started_at).getTime())/1000)}s`:''}</p>{run.current_step_id&&<p>Etapa atual: {run.steps.find(item=>item.step_snapshot.id===run.current_step_id)?.step_snapshot.name||run.current_step_id}</p>}{run.card_id&&<p>Card: {run.card_id}</p>}{run.bypass_reason&&<p>Motivo do bypass: {run.bypass_reason}</p>}<ol className="mt-2 space-y-2">{run.steps.map(item=><li key={item.id} className="rounded bg-[#f7f8fa] p-2"><strong>{item.step_snapshot.name} · {item.status}</strong>{item.status==='bypassed'&&<p>Motivo: {String(item.metadata?.reason||run.bypass_reason||'Política de execução')}</p>}{Object.keys(item.outputs||{}).length>0&&<pre className="whitespace-pre-wrap">{JSON.stringify(item.outputs,null,2)}</pre>}{item.stdout&&<pre className="max-h-48 overflow-auto whitespace-pre-wrap">{item.stdout}</pre>}{item.stderr&&<pre className="max-h-48 overflow-auto whitespace-pre-wrap">{item.stderr}</pre>}{item.error&&<p className="text-[#ae2a19]">{item.error}</p>}{item.status==='waiting'&&<div className="mt-2 flex gap-2"><input className={field} placeholder="Comentário" value={comment} onChange={event=>setComment(event.target.value)}/><button type="button" className={button} onClick={()=>void decision(true)}>Aprovar</button><button type="button" onClick={()=>void decision(false)}>Rejeitar</button></div>}</li>)}</ol>{error&&<p role="alert" className="text-[#ae2a19]">{error}</p>}<details className="mt-2"><summary>Auditoria</summary>{run.audit.map((event,index)=><div key={index}>{new Date(event.created_at).toLocaleString('pt-BR')} · {event.event}</div>)}</details></div>;
}
