'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {api,send} from '@/lib/api';

type Repository={id:string;name:string;relative_path:string;remote_name:string;branches:string[]};
type Target={id:string;repository_id:string;name:string;provider:'github_actions'|'gitlab_ci'|'bamboo';base_url:string;external_project:string;pipeline_ref:string;branches:string[];stages:string[];active:boolean;deployment_method:'provider'|'ssh'|'git';git_flow:'pipeline_only'|'commit_push'|'pull_push'};
type Column={id:string;title:string;board_title:string};
type Mapping={list_id:string;target_id:string;stage_key:string};
type Config={repositories:Repository[];targets:Target[];columns:Column[];mappings:Mapping[]};
const list=(value:string)=>value.split(',').map(item=>item.trim()).filter(Boolean);
const field='w-full rounded border border-[#8590a2] bg-white px-2 py-1.5 text-xs';

export function GitProjectSettings({projectId}:{projectId:string}){
  const [open,setOpen]=useState(false);
  return <div className="mt-3 max-w-2xl rounded-lg border border-[#dfe1e6] p-3"><button type="button" onClick={()=>setOpen(value=>!value)} className="text-left text-xs font-semibold text-[#403294]">Git e deploy {open?'▴':'▾'}</button>{open&&<Settings projectId={projectId}/>}</div>;
}
function Settings({projectId}:{projectId:string}){
  const [config,setConfig]=useState<Config|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false);
  const [repoName,setRepoName]=useState(''),[repoPath,setRepoPath]=useState('.'),[repoBranches,setRepoBranches]=useState('main'),[repoRemote,setRepoRemote]=useState('origin');
  const [targetRepo,setTargetRepo]=useState(''),[targetName,setTargetName]=useState(''),[provider,setProvider]=useState<Target['provider']>('github_actions'),[baseUrl,setBaseUrl]=useState('https://api.github.com'),[externalProject,setExternalProject]=useState(''),[pipelineRef,setPipelineRef]=useState(''),[targetBranches,setTargetBranches]=useState('main'),[stages,setStages]=useState(''),[token,setToken]=useState(''),[deploymentMethod,setDeploymentMethod]=useState<Target['deployment_method']>('provider'),[gitFlow,setGitFlow]=useState<Target['git_flow']>('pipeline_only');
  const [mapTarget,setMapTarget]=useState(''),[mapColumn,setMapColumn]=useState(''),[mapStage,setMapStage]=useState('');
  const load=useCallback(async()=>{try{setConfig(await api<Config>(`/git/projects/${projectId}`));setError('')}catch(reason){setError((reason as Error).message)}},[projectId]);
  useEffect(()=>{let active=true;void api<Config>(`/git/projects/${projectId}`).then(value=>{if(active){setConfig(value);setError('')}}).catch(reason=>{if(active)setError((reason as Error).message)});return()=>{active=false}},[projectId]);
  async function act(action:()=>Promise<unknown>){setBusy(true);try{await action();await load()}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  function addRepo(event:FormEvent){event.preventDefault();void act(async()=>{await send(`/git/projects/${projectId}/repositories`,'POST',{name:repoName,relative_path:repoPath,remote_name:repoRemote,branches:list(repoBranches)});setRepoName('')})}
  function addTarget(event:FormEvent){event.preventDefault();if(!targetRepo)return;void act(async()=>{await send(`/git/repositories/${targetRepo}/targets`,'POST',{name:targetName,provider,base_url:baseUrl,external_project:externalProject,pipeline_ref:pipelineRef,branches:list(targetBranches),stages:list(stages),token,deployment_method:deploymentMethod,git_flow:gitFlow});setTargetName('');setToken('')})}
  function addMapping(event:FormEvent){event.preventDefault();if(!mapColumn||!mapTarget||!mapStage)return;void act(()=>send(`/git/columns/${mapColumn}/stages/${mapTarget}`,'PATCH',{stage_key:mapStage}))}
  const selectedTarget=config?.targets.find(target=>target.id===mapTarget);
  return <div className="mt-3 space-y-4 text-xs">
    <p className="text-[#626f86]">Configure repositórios mesmo sem deploy. Branches permitidas valem para todos os comandos Git.</p>
    {error&&<p role="alert" className="rounded bg-[#ffebe6] p-2 text-[#ae2a19]">{error}</p>}
    {!config?<p>Carregando configuração...</p>:<>
      <div><strong>Repositórios</strong>{config.repositories.map(repo=><div key={repo.id} className="mt-1 flex items-start justify-between gap-2 rounded bg-[#f7f8fa] p-2"><div><b>{repo.name}</b> · {repo.relative_path}<div className="text-[#626f86]">{repo.branches.join(', ')} · remote {repo.remote_name}</div></div><button type="button" disabled={busy} onClick={()=>void act(()=>send(`/git/repositories/${repo.id}`,'DELETE'))} className="text-[#ae2a19]">Remover</button></div>)}</div>
      <form onSubmit={addRepo} className="grid gap-2 rounded border border-[#dfe1e6] p-2 sm:grid-cols-2"><strong className="sm:col-span-2">Adicionar repositório</strong><label>Nome<input required value={repoName} onChange={event=>setRepoName(event.target.value)} className={field}/></label><label>Pasta relativa ao projeto<input required value={repoPath} onChange={event=>setRepoPath(event.target.value)} className={field}/></label><label>Branches permitidas, separadas por vírgula<input required value={repoBranches} onChange={event=>setRepoBranches(event.target.value)} className={field}/></label><label>Remote<input required value={repoRemote} onChange={event=>setRepoRemote(event.target.value)} className={field}/></label><button disabled={busy} className="rounded bg-[#403294] px-3 py-1.5 font-semibold text-white sm:col-span-2">Adicionar repositório</button></form>
      <div><strong>Destinos de deploy</strong>{config.targets.map(target=><div key={target.id} className="mt-1 flex items-start justify-between gap-2 rounded bg-[#f7f8fa] p-2"><div><b>{target.name}</b> · {target.provider}<div className="text-[#626f86]">{target.branches.join(', ')} · {target.pipeline_ref} · {target.deployment_method} · {target.git_flow}{target.stages.length?` · etapas: ${target.stages.join(', ')}`:''}</div></div><button type="button" disabled={busy} onClick={()=>void act(()=>send(`/git/targets/${target.id}`,'DELETE'))} className="text-[#ae2a19]">Remover</button></div>)}</div>
      {config.repositories.length>0&&<form onSubmit={addTarget} className="grid gap-2 rounded border border-[#dfe1e6] p-2 sm:grid-cols-2"><strong className="sm:col-span-2">Adicionar pipeline</strong><label>Repositório<select required value={targetRepo} onChange={event=>setTargetRepo(event.target.value)} className={field}><option value="">Selecione</option>{config.repositories.map(repo=><option key={repo.id} value={repo.id}>{repo.name}</option>)}</select></label><label>Nome<input required value={targetName} onChange={event=>setTargetName(event.target.value)} className={field}/></label><label>Provedor<select value={provider} onChange={event=>{const next=event.target.value as Target['provider'];setProvider(next);setBaseUrl(next==='github_actions'?'https://api.github.com':'')}} className={field}><option value="github_actions">GitHub Actions</option><option value="gitlab_ci">GitLab CI/CD</option><option value="bamboo">Bamboo</option></select></label><label>URL da API<input required type="url" value={baseUrl} onChange={event=>setBaseUrl(event.target.value)} className={field}/></label><label>Projeto externo (owner/repo, ID ou chave)<input required value={externalProject} onChange={event=>setExternalProject(event.target.value)} className={field}/></label><label>Workflow ou plano<input required value={pipelineRef} onChange={event=>setPipelineRef(event.target.value)} className={field}/></label><label>Branches do pipeline<input required value={targetBranches} onChange={event=>setTargetBranches(event.target.value)} className={field}/></label><label>Etapas opcionais<input value={stages} onChange={event=>setStages(event.target.value)} placeholder="teste, homologacao, producao" className={field}/></label><label>Método de deploy<select value={deploymentMethod} onChange={event=>setDeploymentMethod(event.target.value as Target['deployment_method'])} className={field}><option value="provider">Definido no pipeline</option><option value="ssh">SSH no pipeline</option><option value="git">Git no pipeline</option></select></label><label>Fluxo Git antes do pipeline<select value={gitFlow} onChange={event=>setGitFlow(event.target.value as Target['git_flow'])} className={field}><option value="pipeline_only">Somente pipeline</option><option value="commit_push">add, commit e push</option><option value="pull_push">pull e push (árvore limpa)</option></select></label><label className="sm:col-span-2">Token do provedor<input required type="password" autoComplete="off" value={token} onChange={event=>setToken(event.target.value)} className={field}/></label><button disabled={busy} className="rounded bg-[#403294] px-3 py-1.5 font-semibold text-white sm:col-span-2">Adicionar pipeline</button></form>}
      {config.targets.some(target=>target.stages.length>0)&&config.columns.length>0&&<div className="space-y-2"><strong>Etapas por coluna (opcional)</strong>{config.mappings.map(mapping=><div key={`${mapping.list_id}:${mapping.target_id}`} className="flex justify-between gap-2 rounded bg-[#f7f8fa] p-2"><span>{config.columns.find(column=>column.id===mapping.list_id)?.title} → {config.targets.find(target=>target.id===mapping.target_id)?.name} / {mapping.stage_key}</span><button type="button" disabled={busy} onClick={()=>void act(()=>send(`/git/columns/${mapping.list_id}/stages/${mapping.target_id}`,'DELETE'))} className="text-[#ae2a19]">Remover</button></div>)}<form onSubmit={addMapping} className="grid gap-2 sm:grid-cols-3"><select required value={mapColumn} onChange={event=>setMapColumn(event.target.value)} aria-label="Coluna" className={field}><option value="">Coluna</option>{config.columns.map(column=><option key={column.id} value={column.id}>{column.board_title} / {column.title}</option>)}</select><select required value={mapTarget} onChange={event=>{setMapTarget(event.target.value);setMapStage('')}} aria-label="Pipeline" className={field}><option value="">Pipeline</option>{config.targets.filter(target=>target.stages.length).map(target=><option key={target.id} value={target.id}>{target.name}</option>)}</select><select required value={mapStage} onChange={event=>setMapStage(event.target.value)} aria-label="Etapa" className={field}><option value="">Etapa</option>{selectedTarget?.stages.map(stage=><option key={stage} value={stage}>{stage}</option>)}</select><button disabled={busy} className="rounded bg-[#403294] px-3 py-1.5 font-semibold text-white sm:col-span-3">Vincular coluna à etapa</button></form></div>}
    </>}
  </div>;
}
