'use client';
import {FormEvent,useCallback,useEffect,useState} from 'react';
import {GitBranch,GitCommitHorizontal,Play,RotateCcw} from 'lucide-react';
import {api,send} from '@/lib/api';

type Repository={id:string;name:string;branches:string[]};
type Target={id:string;repository_id:string;name:string;provider:string;branches:string[];stages:string[];deployment_method:'provider'|'ssh'|'git';git_flow:'pipeline_only'|'commit_push'|'pull_push'};
type Commit={id:string;sha:string;branch:string;title:string;comments:string;files:string[];merge:boolean;url:string|null;repository:string;created_at:string};
type Run={id:string;target_id:string;target_name:string;stage_key:string|null;branch:string;status:string;logs:string;error:string|null;created_at:string};
type History={can_write:boolean;commits:Commit[];repositories:Repository[];targets:Target[];mappings:{target_id:string;stage_key:string}[];runs:Run[]};
const field='rounded border border-[#8590a2] bg-white px-2 py-1.5 text-xs';
export function GitCardPanel({cardId}:{cardId:string}){
  const [history,setHistory]=useState<History|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loadRevision,setLoadRevision]=useState(0);
  const [repoId,setRepoId]=useState(''),[kind,setKind]=useState<'feat'|'fix'|'chore'>('feat'),[files,setFiles]=useState(''),[subject,setSubject]=useState('');
  const [linkSha,setLinkSha]=useState(''),[linkBranch,setLinkBranch]=useState('');
  const [targetId,setTargetId]=useState(''),[deployBranch,setDeployBranch]=useState('');
  const load=useCallback(async()=>{try{const value=await api<History>(`/git/cards/${cardId}`);setHistory(value);setError('')}catch(reason){setError((reason as Error).message)}},[cardId]);
  useEffect(()=>{let active=true;void api<History>(`/git/cards/${cardId}`).then(value=>{if(active){setHistory(value);setError('')}}).catch(reason=>{if(active)setError((reason as Error).message)});return()=>{active=false}},[cardId,loadRevision]);
  useEffect(()=>{const activeRuns=history?.can_write?history.runs.filter(run=>run.status==='queued'||run.status==='running'):[];if(!activeRuns?.length)return;const timer=window.setInterval(()=>{void Promise.all(activeRuns.map(run=>send(`/git/runs/${run.id}/refresh`,'POST').catch(()=>null))).then(()=>load())},15000);return()=>window.clearInterval(timer)},[history,load]);
  async function act(callback:()=>Promise<unknown>){setBusy(true);let failure:Error|null=null;try{await callback()}catch(reason){failure=reason as Error}finally{await load();if(failure)setError(failure.message);setBusy(false)}}
  const selectedRepo=history?.repositories.find(repo=>repo.id===repoId);
  const target=history?.targets.find(item=>item.id===targetId);
  function createCommit(event:FormEvent){event.preventDefault();if(!repoId)return;void act(async()=>{await send(`/git/cards/${cardId}/commits`,'POST',{repository_id:repoId,type:kind,subject:subject||undefined,paths:files.split(/[\n,]/).map(value=>value.trim()).filter(Boolean)});setFiles('');setSubject('')})}
  function linkCommit(event:FormEvent){event.preventDefault();if(!repoId)return;void act(async()=>{await send(`/git/cards/${cardId}/link-commit`,'POST',{repository_id:repoId,sha:linkSha,branch:linkBranch});setLinkSha('')})}
  function operation(name:'add'|'push'|'pull'){if(!repoId)return;void act(()=>send(`/git/cards/${cardId}/operations`,'POST',{repository_id:repoId,operation:name,paths:name==='add'?files.split(/[\n,]/).map(value=>value.trim()).filter(Boolean):undefined}))}
  function deploy(event:FormEvent){event.preventDefault();if(!targetId||!deployBranch)return;void act(()=>send(`/git/cards/${cardId}/deploys`,'POST',{target_id:targetId,branch:deployBranch,paths:target?.git_flow==='commit_push'?files.split(/[\n,]/).map(value=>value.trim()).filter(Boolean):undefined,type:kind,subject:subject||undefined}))}
  return <section aria-label="Git do cartão" className="space-y-3"><div className="flex items-center gap-2"><h3 className="flex flex-1 items-center gap-2 text-sm font-bold"><GitBranch size={17}/> Git e deploy</h3><button type="button" title="Atualizar Git" onClick={()=>setLoadRevision(value=>value+1)} className="rounded p-1 hover:bg-[#f1f2f4]"><RotateCcw size={15}/></button></div>
    {error&&<p role="alert" className="rounded bg-[#ffebe6] p-2 text-xs text-[#ae2a19]">{error}</p>}
    {!history?<p className="text-xs text-[#626f86]">{error?'Associe um projeto ao cartão ou ao quadro para usar o Git.':'Carregando histórico Git...'}</p>:<>
      {history.repositories.length===0?<p className="text-xs text-[#626f86]">Nenhum repositório configurado. Configure Git no projeto para usar versionamento; deploy é opcional.</p>:<div className="space-y-3 rounded border border-[#dfe1e6] p-3"><label className="block text-xs font-semibold">Repositório<select value={repoId} onChange={event=>{setRepoId(event.target.value);setLinkBranch('')}} className={`mt-1 w-full ${field}`}><option value="">Selecione</option>{history.repositories.map(repo=><option key={repo.id} value={repo.id}>{repo.name}</option>)}</select></label>
        {selectedRepo&&history.can_write&&<><form onSubmit={createCommit} className="space-y-2"><strong className="flex items-center gap-1 text-xs"><GitCommitHorizontal size={14}/> Criar commit</strong><div className="flex gap-2"><select value={kind} onChange={event=>setKind(event.target.value as typeof kind)} className={field}><option value="feat">feat</option><option value="fix">fix</option><option value="chore">chore</option></select><input value={subject} onChange={event=>setSubject(event.target.value)} placeholder="Resumo (padrão: título do card)" className={`min-w-0 flex-1 ${field}`}/></div><textarea value={files} onChange={event=>setFiles(event.target.value)} placeholder="Arquivos relativos ao repositório, um por linha" className={`min-h-16 w-full ${field}`}/><div className="flex flex-wrap gap-2"><button disabled={busy||!files.trim()} className="rounded bg-[#403294] px-2 py-1.5 text-xs font-semibold text-white disabled:opacity-50">add + commit</button><button type="button" disabled={busy||!files.trim()} onClick={()=>operation('add')} className="rounded bg-[#e9eaed] px-2 py-1.5 text-xs disabled:opacity-50">Somente add</button><button type="button" disabled={busy} onClick={()=>operation('push')} className="rounded bg-[#e9eaed] px-2 py-1.5 text-xs">push</button><button type="button" disabled={busy} onClick={()=>operation('pull')} className="rounded bg-[#e9eaed] px-2 py-1.5 text-xs">pull</button></div><p className="text-[11px] text-[#626f86]">Operações permitidas somente nas branches configuradas: {selectedRepo.branches.join(', ')}.</p></form><form onSubmit={linkCommit} className="flex flex-wrap gap-2 border-t border-[#dfe1e6] pt-2"><input required pattern="[a-fA-F0-9]{7,40}" value={linkSha} onChange={event=>setLinkSha(event.target.value)} placeholder="SHA existente" className={`min-w-0 flex-1 ${field}`}/><select required value={linkBranch} onChange={event=>setLinkBranch(event.target.value)} className={field}><option value="">Branch</option>{selectedRepo.branches.map(branch=><option key={branch} value={branch}>{branch}</option>)}</select><button disabled={busy} className="rounded bg-[#e9eaed] px-2 py-1.5 text-xs">Vincular commit</button></form></>}
      </div>}
      <div className="space-y-2"><strong className="text-xs">Histórico de versionamento ({history.commits.length})</strong>{history.commits.length===0&&<p className="text-xs text-[#626f86]">Nenhum commit associado.</p>}{history.commits.map(commit=><article key={commit.id} className="rounded border border-[#dfe1e6] p-2 text-xs"><div className="flex flex-wrap items-center gap-2"><code>{commit.url?<a href={commit.url} target="_blank" rel="noopener noreferrer" className="text-[#0c66e4] underline">{commit.sha.slice(0,8)}</a>:commit.sha.slice(0,8)}</code><b>{commit.title}</b>{commit.merge&&<span className="rounded bg-[#eeedfd] px-1.5">Merge</span>}</div><p className="mt-1 text-[#626f86]">{commit.repository} · {commit.branch}</p>{commit.comments&&<p className="mt-1 whitespace-pre-wrap">{commit.comments}</p>}{commit.files.length>0&&<details className="mt-1"><summary className="cursor-pointer">Arquivos modificados ({commit.files.length})</summary><ul className="mt-1 list-inside list-disc break-all">{commit.files.map(file=><li key={file}>{file}</li>)}</ul></details>}</article>)}</div>
      {history.can_write&&history.targets.length>0&&<div className="space-y-2 rounded border border-[#dfe1e6] p-3"><strong className="flex items-center gap-1 text-xs"><Play size={14}/> Executar pipeline</strong><form onSubmit={deploy} className="flex flex-wrap gap-2"><select required value={targetId} onChange={event=>{const next=event.target.value;setTargetId(next);setDeployBranch('');const repository=history.targets.find(item=>item.id===next)?.repository_id;if(repository)setRepoId(repository)}} className={field}><option value="">Pipeline</option>{history.targets.map(item=><option key={item.id} value={item.id}>{item.name} · {item.provider}</option>)}</select><select required value={deployBranch} onChange={event=>setDeployBranch(event.target.value)} className={field}><option value="">Branch</option>{target?.branches.map(branch=><option key={branch} value={branch}>{branch}</option>)}</select><button disabled={busy||(target?.git_flow==='commit_push'&&!files.trim())} className="rounded bg-[#403294] px-2 py-1.5 text-xs font-semibold text-white disabled:opacity-50">Executar</button></form>{target&&<p className="text-[11px] text-[#626f86]">Etapa da coluna: {history.mappings.find(mapping=>mapping.target_id===target.id)?.stage_key||'não vinculada'}. Método: {target.deployment_method}; fluxo Git: {target.git_flow}. A configuração do deploy fica no projeto.</p>}</div>}
      {history.runs.length>0&&<div className="space-y-2"><strong className="text-xs">Execuções de pipeline</strong>{history.runs.map(run=><article key={run.id} className="rounded border border-[#dfe1e6] p-2 text-xs"><div className="flex justify-between gap-2"><b>{run.target_name} · {run.branch} · {run.status}</b>{history.can_write&&<button type="button" disabled={busy} onClick={()=>void act(()=>send(`/git/runs/${run.id}/refresh`,'POST'))} className="text-[#403294]">Atualizar</button>}</div>{run.stage_key&&<p>Etapa: {run.stage_key}</p>}{run.error&&<p role="alert" className="text-[#ae2a19]">{run.error}</p>}{run.logs&&<pre className="mt-1 max-h-32 overflow-auto whitespace-pre-wrap rounded bg-[#f7f8fa] p-2">{run.logs}</pre>}</article>)}</div>}
    </>}
  </section>;
}
