/**
 * Prompt Tab Sub-Component
 * Extracted from ItemDetailPanel.tsx
 * Shows generated prompt, export, check result, and prompt metadata
 * PROMPT #127 - AI model badge
 * PROMPT #241 - Orbit Folder: prompt export
 * PROMPT #242 - Orbit Folder: result check
 * PROMPT #248 - Semantic prompt generation from card + RAG/wiki/git context
 */

'use client';

import React, { useState } from 'react';
import { AIModelBadge } from '@/components/ui/AIModelBadge';
import { IconClipboard, IconPencil, IconExport } from '@/components/icons';
import { BacklogItem } from '@/lib/types';
import { tasksApi } from '@/lib/api';

export interface PromptTabProps {
  item: BacklogItem;
  projectId: string;
  handleExportPrompt: () => void;
  isExportingPrompt: boolean;
  exportResult: { filename: string; orbit_path: string } | null;
  handleCheckResult: () => void;
  isCheckingResult: boolean;
  checkResultMsg: { found: boolean; message: string } | null;
  onPromptGenerated?: (prompt: string) => void;
}

interface PromptSources {
  wiki_pages: string[];
  rules_count: number;
  parent_context: boolean;
  project_context: boolean;
}

export default function PromptTab({
  item,
  projectId,
  handleExportPrompt,
  isExportingPrompt,
  exportResult,
  handleCheckResult,
  isCheckingResult,
  checkResultMsg,
  onPromptGenerated,
}: PromptTabProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [generationError, setGenerationError] = useState<string | null>(null);
  const [sources, setSources] = useState<PromptSources | null>(null);
  const [showForceConfirm, setShowForceConfirm] = useState(false);
  const [generatedPrompt, setGeneratedPrompt] = useState<string | null>(null);
  const [progressMsg, setProgressMsg] = useState<string | null>(null);
  const [progressPercent, setProgressPercent] = useState<number>(0);

  // Use generated prompt from state (fresh generation) or item (persisted)
  const displayPrompt = generatedPrompt || item.generated_prompt;

  const handleGenerate = async (force = false) => {
    setIsGenerating(true);
    setGenerationError(null);
    setShowForceConfirm(false);
    setProgressMsg(null);
    setProgressPercent(0);

    try {
      const result = await tasksApi.generateSemanticPromptWithPolling(
        item.id,
        force,
        (percent, message) => {
          setProgressPercent(percent);
          setProgressMsg(message);
        }
      );

      // REGRA #0: inline response when prompt was human-edited
      if (result?.success === false && result?.message?.includes('editado manualmente')) {
        setShowForceConfirm(true);
      } else if (result?.success && result?.prompt) {
        setGeneratedPrompt(result.prompt);
        setSources(result.sources || null);
        onPromptGenerated?.(result.prompt);
      } else if (result?.prompt) {
        // Job result format: { prompt, sources, ... }
        setGeneratedPrompt(result.prompt);
        setSources(result.sources || null);
        onPromptGenerated?.(result.prompt);
      } else {
        setGenerationError(result?.message || 'Erro desconhecido na geração');
      }
    } catch (err: any) {
      setGenerationError(err.message || 'Falha ao conectar com o servidor');
    } finally {
      setIsGenerating(false);
      setProgressMsg(null);
      setProgressPercent(0);
    }
  };

  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-sm font-semibold text-gray-900 mb-3">Prompt Semântico</h3>

        {displayPrompt ? (
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-semibold text-gray-500 uppercase">Prompt Semântico</span>
              <div className="flex items-center gap-2">
                {/* PROMPT #127 - Show AI model icon if prompt was generated by AI */}
                {item.created_by_ai_model && (
                  <AIModelBadge model={item.created_by_ai_model} usage_type="prompt_generation" promptText={displayPrompt} />
                )}
                {/* Regenerate button */}
                <button
                  onClick={() => {
                    if (item.prompt_edited_by === 'human') {
                      setShowForceConfirm(true);
                    } else {
                      handleGenerate(false);
                    }
                  }}
                  disabled={isGenerating}
                  className="px-2 py-1 text-xs text-purple-600 hover:text-purple-700 hover:bg-purple-50 rounded transition-colors disabled:opacity-50"
                >
                  {isGenerating ? (progressMsg || 'Gerando...') : 'Regenerar'}
                </button>
                <button
                  onClick={() => navigator.clipboard.writeText(displayPrompt || '')}
                  className="px-2 py-1 text-xs text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded transition-colors"
                >
                  <span className="inline-flex items-center gap-1"><IconClipboard className="w-3 h-3" /> Copiar</span>
                </button>
                {/* PROMPT #241 - Export prompt to orbit/prompts/ */}
                <button
                  onClick={handleExportPrompt}
                  disabled={isExportingPrompt}
                  className="px-2 py-1 text-xs text-green-600 hover:text-green-700 hover:bg-green-50 rounded transition-colors disabled:opacity-50"
                >
                  <span className="inline-flex items-center gap-1">
                    <IconExport className="w-3 h-3" />
                    {isExportingPrompt ? 'Exportando...' : 'Exportar'}
                  </span>
                </button>
              </div>
            </div>
            <pre className="text-sm text-gray-900 whitespace-pre-wrap font-mono leading-relaxed">
              {displayPrompt}
            </pre>
            {/* PROMPT #241 - Show export result path */}
            {exportResult && (
              <div className="mt-3 p-2 bg-green-50 border border-green-200 rounded text-xs text-green-700">
                Exportado: <code className="bg-green-100 px-1 rounded">{exportResult.orbit_path}/knowledge/prompts/{exportResult.filename}</code>
              </div>
            )}
            {/* PROMPT #242 - Check result button */}
            <div className="mt-3 flex items-center gap-2">
              <button
                onClick={handleCheckResult}
                disabled={isCheckingResult}
                className="px-3 py-1.5 text-xs text-blue-600 hover:text-blue-700 bg-blue-50 hover:bg-blue-100 border border-blue-200 rounded transition-colors disabled:opacity-50"
              >
                {isCheckingResult ? 'Verificando...' : 'Verificar Resultado'}
              </button>
              {checkResultMsg && (
                <span className={`text-xs ${checkResultMsg.found ? 'text-green-600' : 'text-gray-500'}`}>
                  {checkResultMsg.message}
                </span>
              )}
            </div>
          </div>
        ) : (
          /* Empty state: generation button */
          <div className="text-center py-10 border border-dashed border-gray-300 rounded-lg bg-gray-50">
            <div className="mb-4">
              <svg className="w-12 h-12 mx-auto text-purple-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={1.5}>
                <path strokeLinecap="round" strokeLinejoin="round" d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09zM18.259 8.715L18 9.75l-.259-1.035a3.375 3.375 0 00-2.455-2.456L14.25 6l1.036-.259a3.375 3.375 0 002.455-2.456L18 2.25l.259 1.035a3.375 3.375 0 002.455 2.456L21.75 6l-1.036.259a3.375 3.375 0 00-2.455 2.456z" />
              </svg>
            </div>
            <button
              onClick={() => handleGenerate(false)}
              disabled={isGenerating}
              className="px-6 py-2.5 bg-purple-600 text-white text-sm font-medium rounded-lg hover:bg-purple-700 transition-colors disabled:opacity-50 disabled:cursor-wait"
            >
              {isGenerating ? (
                <span className="inline-flex items-center gap-2">
                  <svg className="animate-spin h-4 w-4" viewBox="0 0 24 24">
                    <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" fill="none" />
                    <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                  </svg>
                  {progressMsg || 'Gerando Prompt...'}
                </span>
              ) : (
                'Gerar Prompt Semântico'
              )}
            </button>
            {isGenerating && progressPercent > 0 && (
              <div className="mt-4 max-w-xs mx-auto">
                <div className="w-full bg-gray-200 rounded-full h-1.5">
                  <div
                    className="bg-purple-600 h-1.5 rounded-full transition-all duration-500"
                    style={{ width: `${progressPercent}%` }}
                  />
                </div>
                <p className="text-xs text-gray-500 mt-1">{Math.round(progressPercent)}%</p>
              </div>
            )}
            {!isGenerating && (
              <p className="text-xs text-gray-400 mt-3 max-w-xs mx-auto">
                Usa wiki, regras de negócio, contexto do projeto e hierarquia do card para gerar um prompt técnico completo
              </p>
            )}
          </div>
        )}

        {/* Force confirmation dialog */}
        {showForceConfirm && (
          <div className="mt-3 p-3 bg-amber-50 border border-amber-200 rounded-lg">
            <p className="text-sm text-amber-800 mb-2">
              Este prompt foi editado manualmente. Deseja sobrescrever com um novo prompt gerado por IA?
            </p>
            <div className="flex gap-2">
              <button
                onClick={() => handleGenerate(true)}
                disabled={isGenerating}
                className="px-3 py-1 text-xs bg-amber-600 text-white rounded hover:bg-amber-700 disabled:opacity-50"
              >
                Sim, regenerar
              </button>
              <button
                onClick={() => setShowForceConfirm(false)}
                className="px-3 py-1 text-xs text-gray-600 bg-white border border-gray-300 rounded hover:bg-gray-50"
              >
                Cancelar
              </button>
            </div>
          </div>
        )}

        {/* Generation error */}
        {generationError && (
          <div className="mt-3 p-2 bg-red-50 border border-red-200 rounded text-xs text-red-700">
            {generationError}
          </div>
        )}
      </div>

      {/* Sources Used Section */}
      {sources && (
        <div className="border-t border-gray-200 pt-4">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Fontes Usadas</h3>
          <div className="flex flex-wrap gap-2">
            {sources.project_context && (
              <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-blue-50 text-blue-700 border border-blue-200">
                Contexto do Projeto
              </span>
            )}
            {sources.parent_context && (
              <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-indigo-50 text-indigo-700 border border-indigo-200">
                Hierarquia Pai
              </span>
            )}
            {sources.rules_count > 0 && (
              <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-green-50 text-green-700 border border-green-200">
                {sources.rules_count} Regras de Negócio
              </span>
            )}
            {sources.wiki_pages.length > 0 && (
              <span className="inline-flex items-center px-2 py-1 rounded-full text-xs font-medium bg-purple-50 text-purple-700 border border-purple-200">
                {sources.wiki_pages.length} Páginas Wiki
              </span>
            )}
          </div>
          {sources.wiki_pages.length > 0 && (
            <div className="mt-2">
              <p className="text-xs text-gray-500">
                Wiki: {sources.wiki_pages.join(', ')}
              </p>
            </div>
          )}
        </div>
      )}

      {/* Prompt Metadata */}
      {displayPrompt && (
        <div className="border-t border-gray-200 pt-6">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Detalhes do Prompt</h3>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <span className="text-xs font-semibold text-gray-500 uppercase">Orçamento de Tokens</span>
              <p className="text-sm text-gray-900 mt-1">
                {item.token_budget ? `${item.token_budget.toLocaleString()} tokens` : 'Não definido'}
              </p>
            </div>
            {item.actual_tokens_used && (
              <div>
                <span className="text-xs font-semibold text-gray-500 uppercase">Tokens Usados</span>
                <p className="text-sm text-gray-900 mt-1">
                  {item.actual_tokens_used.toLocaleString()} tokens
                  {item.token_budget && (
                    <span className="text-xs text-gray-500 ml-2">
                      ({Math.round((item.actual_tokens_used / item.token_budget) * 100)}%)
                    </span>
                  )}
                </p>
              </div>
            )}
            <div>
              <span className="text-xs font-semibold text-gray-500 uppercase">Tipo de Item</span>
              <p className="text-sm text-gray-900 mt-1">{item.item_type}</p>
            </div>
            <div>
              <span className="text-xs font-semibold text-gray-500 uppercase">Modelo de IA Alvo</span>
              <p className="text-sm text-gray-900 mt-1">
                {item.target_ai_model_id || 'Seleção automática'}
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
