/**
 * Prompt Tab Sub-Component
 * Extracted from ItemDetailPanel.tsx
 * Shows generated prompt, export, check result, and prompt metadata
 * PROMPT #127 - AI model badge
 * PROMPT #241 - Orbit Folder: prompt export
 * PROMPT #242 - Orbit Folder: result check
 */

'use client';

import React from 'react';
import { AIModelBadge } from '@/components/ui/AIModelBadge';
import { IconClipboard, IconPencil, IconExport } from '@/components/icons';
import { BacklogItem } from '@/lib/types';

export interface PromptTabProps {
  item: BacklogItem;
  handleExportPrompt: () => void;
  isExportingPrompt: boolean;
  exportResult: { filename: string; orbit_path: string } | null;
  handleCheckResult: () => void;
  isCheckingResult: boolean;
  checkResultMsg: { found: boolean; message: string } | null;
}

export default function PromptTab({
  item,
  handleExportPrompt,
  isExportingPrompt,
  exportResult,
  handleCheckResult,
  isCheckingResult,
  checkResultMsg,
}: PromptTabProps) {
  return (
    <div className="space-y-6">
      <div>
        <h3 className="text-sm font-semibold text-gray-900 mb-3">Prompt Gerado</h3>

        {item.generated_prompt ? (
          <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
            <div className="flex items-center justify-between mb-3">
              <span className="text-xs font-semibold text-gray-500 uppercase">Prompt At\u00f4mico</span>
              <div className="flex items-center gap-2">
                {/* PROMPT #127 - Show AI model icon if prompt was generated by AI */}
                {item.created_by_ai_model && (
                  <AIModelBadge model={item.created_by_ai_model} usage_type="prompt_generation" promptText={item.generated_prompt} />
                )}
                <button
                  onClick={() => navigator.clipboard.writeText(item.generated_prompt || '')}
                  className="px-2 py-1 text-xs text-blue-600 hover:text-blue-700 hover:bg-blue-50 rounded transition-colors"
                >
                  <span className="inline-flex items-center gap-1"><IconClipboard className="w-3 h-3" /> Copiar</span>
                </button>
                {/* PROMPT #241 - Export prompt to orbit/prompts/ */}
                <button
                  onClick={handleExportPrompt}
                  disabled={isExportingPrompt}
                  className="px-2 py-1 text-xs text-green-600 hover:text-green-700 hover:bg-green-50 rounded transition-colors disabled:opacity-50"
                >
                  <span className="inline-flex items-center gap-1">
                    <IconExport className="w-3 h-3" />
                    {isExportingPrompt ? 'Exportando...' : 'Exportar'}
                  </span>
                </button>
              </div>
            </div>
            <pre className="text-sm text-gray-900 whitespace-pre-wrap font-mono leading-relaxed">
              {item.generated_prompt}
            </pre>
            {/* PROMPT #241 - Show export result path */}
            {exportResult && (
              <div className="mt-3 p-2 bg-green-50 border border-green-200 rounded text-xs text-green-700">
                Exportado: <code className="bg-green-100 px-1 rounded">{exportResult.orbit_path}/prompts/{exportResult.filename}</code>
              </div>
            )}
            {/* PROMPT #242 - Check result button */}
            <div className="mt-3 flex items-center gap-2">
              <button
                onClick={handleCheckResult}
                disabled={isCheckingResult}
                className="px-3 py-1.5 text-xs text-blue-600 hover:text-blue-700 bg-blue-50 hover:bg-blue-100 border border-blue-200 rounded transition-colors disabled:opacity-50"
              >
                {isCheckingResult ? 'Verificando...' : 'Verificar Resultado'}
              </button>
              {checkResultMsg && (
                <span className={`text-xs ${checkResultMsg.found ? 'text-green-600' : 'text-gray-500'}`}>
                  {checkResultMsg.message}
                </span>
              )}
            </div>
          </div>
        ) : (
          <div className="text-center py-12 border border-dashed border-gray-300 rounded-lg bg-gray-50">
            <span className="mb-3 block"><IconPencil className="w-10 h-10 mx-auto text-gray-400" /></span>
            <p className="text-sm text-gray-500 mb-2">Nenhum prompt gerado ainda</p>
            <p className="text-xs text-gray-400">
              O prompt sera gerado a partir da entrevista ou pode ser criado manualmente
            </p>
          </div>
        )}
      </div>

      {/* Prompt Metadata */}
      {item.generated_prompt && (
        <div className="border-t border-gray-200 pt-6">
          <h3 className="text-sm font-semibold text-gray-900 mb-3">Detalhes do Prompt</h3>
          <div className="grid grid-cols-2 gap-4">
            <div>
              <span className="text-xs font-semibold text-gray-500 uppercase">Or\u00e7amento de Tokens</span>
              <p className="text-sm text-gray-900 mt-1">
                {item.token_budget ? `${item.token_budget.toLocaleString()} tokens` : 'N\u00e3o definido'}
              </p>
            </div>
            {item.actual_tokens_used && (
              <div>
                <span className="text-xs font-semibold text-gray-500 uppercase">Tokens Usados</span>
                <p className="text-sm text-gray-900 mt-1">
                  {item.actual_tokens_used.toLocaleString()} tokens
                  {item.token_budget && (
                    <span className="text-xs text-gray-500 ml-2">
                      ({Math.round((item.actual_tokens_used / item.token_budget) * 100)}%)
                    </span>
                  )}
                </p>
              </div>
            )}
            <div>
              <span className="text-xs font-semibold text-gray-500 uppercase">Tipo de Item</span>
              <p className="text-sm text-gray-900 mt-1">{item.item_type}</p>
            </div>
            <div>
              <span className="text-xs font-semibold text-gray-500 uppercase">Modelo de IA Alvo</span>
              <p className="text-sm text-gray-900 mt-1">
                {item.target_ai_model_id || 'Sele\u00e7\u00e3o autom\u00e1tica'}
              </p>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
