# =============================================================================
# ORBIT Setup Module
# =============================================================================

cmd_setup() {
    header "ORBIT Setup - Database, Env, Dependencies"

    # -- Start PostgreSQL if not running --------------------------------------
    if ! is_pg_running; then
        info "Starting PostgreSQL..."
        sudo_run service postgresql start
        sleep 2
    fi
    success "PostgreSQL is running"

    # -- Configure Redis for persistence --------------------------------------
    header "Redis Configuration"
    if [[ -f /etc/redis/redis.conf ]]; then
        if ! grep -q "^maxmemory 512mb" /etc/redis/redis.conf 2>/dev/null; then
            info "Configuring Redis (512mb, allkeys-lru, appendonly)..."
            sudo_run bash -c "cat >> /etc/redis/redis.conf << 'REDIS_EOF'

# ORBIT configuration
maxmemory 512mb
maxmemory-policy allkeys-lru
appendonly yes
REDIS_EOF"
        fi
    fi

    # Override systemd: prevent restart loops when manually killing Redis
    info "Applying Redis systemd override (Restart=on-failure, TimeoutStopSec=10)..."
    sudo_run mkdir -p /etc/systemd/system/redis-server.service.d
    sudo_run bash -c "cat > /etc/systemd/system/redis-server.service.d/override.conf << 'SYSD_EOF'
[Service]
Restart=on-failure
TimeoutStopSec=10
SYSD_EOF"
    sudo_run systemctl daemon-reload
    sudo_run service redis-server restart
    sleep 1
    success "Redis configured"

    # -- Create PostgreSQL user & databases -----------------------------------
    header "Database Setup"

    if sudo_run -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='${DB_USER}'" 2>/dev/null | grep -q 1; then
        success "PostgreSQL user '${DB_USER}' exists"
    else
        info "Creating PostgreSQL user '${DB_USER}'..."
        sudo_run -u postgres psql -c "CREATE USER ${DB_USER} WITH PASSWORD '${DB_PASS}' CREATEDB SUPERUSER;" 2>/dev/null
        success "User '${DB_USER}' created"
    fi

    if sudo_run -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME}'" 2>/dev/null | grep -q 1; then
        success "Database '${DB_NAME}' exists"
    else
        info "Creating database '${DB_NAME}'..."
        sudo_run -u postgres psql -c "CREATE DATABASE ${DB_NAME} OWNER ${DB_USER};" 2>/dev/null
        success "Database '${DB_NAME}' created"
    fi

    if sudo_run -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${DB_NAME_LEGACY}'" 2>/dev/null | grep -q 1; then
        success "Database '${DB_NAME_LEGACY}' exists"
    else
        info "Creating database '${DB_NAME_LEGACY}'..."
        sudo_run -u postgres psql -c "CREATE DATABASE ${DB_NAME_LEGACY} OWNER ${DB_USER};" 2>/dev/null
        success "Database '${DB_NAME_LEGACY}' created"
    fi

    info "Enabling pgvector extension..."
    sudo_run -u postgres psql -d "${DB_NAME}" -c "CREATE EXTENSION IF NOT EXISTS vector;" 2>/dev/null
    success "pgvector extension enabled on '${DB_NAME}'"

    # -- Generate .env files --------------------------------------------------
    header "Environment Files"
    local win_ip
    win_ip=$(get_windows_ip)

    if [[ -f "${ORBIT_ROOT}/.env" ]]; then
        warn ".env already exists - skipping (delete to regenerate)"
    else
        info "Generating ${ORBIT_ROOT}/.env ..."
        cat > "${ORBIT_ROOT}/.env" << ENV_EOF
# =============================================================================
# ORBIT - Native WSL2 Configuration
# Generated by: orbit setup ($(date +%Y-%m-%d))
# =============================================================================

# Database
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=${DB_NAME}

# Backend
SECRET_KEY=dev-secret-key-change-in-production
ENVIRONMENT=development
DEBUG=True
LOG_LEVEL=INFO

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379

# Ollama (Windows host - auto-detected)
OLLAMA_HOST=http://${win_ip}:11434
OLLAMA_TIMEOUT=600

# Frontend
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_APP_NAME=Orbit

# Feature Flags
PROMPTER_USE_TEMPLATES=true
PROMPTER_USE_STRUCTURED_TEMPLATES=true
PROMPTER_USE_CACHE=true
PROMPTER_USE_BATCHING=true

# Continuous RAG
RAG_SCAN_INTERVAL_SECONDS=300
ENV_EOF
        success ".env created (OLLAMA_HOST → ${win_ip})"
    fi

    if [[ -f "${FRONTEND_DIR}/.env.local" ]]; then
        warn "frontend/.env.local already exists - skipping"
    else
        info "Generating frontend/.env.local ..."
        cat > "${FRONTEND_DIR}/.env.local" << FENV_EOF
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_APP_NAME=Orbit
NODE_ENV=development
FENV_EOF
        success "frontend/.env.local created"
    fi

    if [[ -f "${BACKEND_DIR}/.env" ]]; then
        warn "backend/.env already exists - skipping"
    else
        info "Symlinking backend/.env → root .env ..."
        ln -sf "${ORBIT_ROOT}/.env" "${BACKEND_DIR}/.env"
        success "backend/.env linked"
    fi

    # -- Install backend dependencies ----------------------------------------
    header "Backend Dependencies"
    info "Running poetry install..."
    cd "${BACKEND_DIR}"
    poetry install --no-interaction 2>&1 | tail -3
    success "Backend dependencies installed"

    # -- Install frontend dependencies ---------------------------------------
    header "Frontend Dependencies"
    info "Running npm install..."
    cd "${FRONTEND_DIR}"
    npm install --silent 2>&1 | tail -3
    success "Frontend dependencies installed"

    # -- Run database migrations ---------------------------------------------
    header "Database Migrations"
    info "Running alembic upgrade head..."
    cd "${BACKEND_DIR}"
    poetry run alembic upgrade head 2>&1 | tail -5
    success "Migrations applied"

    # -- Done ----------------------------------------------------------------
    echo ""
    success "Setup complete! Run ${BOLD}orbit start${NC} to launch all services."
}
