'use client';

import { useCallback, useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Bold, ChevronLeft, ClipboardPaste, Code, Heading1, Italic, Link, List, ListOrdered, Plus, Redo2, Trash2, Underline, Undo2 } from 'lucide-react';
import { api, getToken, Notebook, send, User } from '@/lib/api';
import { AppHeader, WorkspaceSidebar } from '@/components/ui';

function safeClipboardHtml(html:string) {
  const document = new DOMParser().parseFromString(html, 'text/html');
  document.querySelectorAll('script,iframe,object,embed,form,input,button,meta,link').forEach(node => node.remove());
  document.querySelectorAll('*').forEach(node => {
    [...node.attributes].forEach(attribute => {
      const name=attribute.name.toLowerCase(); const value=attribute.value.trim().toLowerCase();
      if(name.startsWith('on') || ((name==='href'||name==='src') && /^(javascript|vbscript):/.test(value))) node.removeAttribute(attribute.name);
      if(name==='style') node.setAttribute('style',attribute.value.replace(/expression\s*\(|url\s*\(\s*['"]?\s*javascript:|behavior\s*:|-moz-binding\s*:/gi,''));
    });
  });
  return document.body.innerHTML;
}

export default function NotebooksPage() {
  const router=useRouter();
  const editor=useRef<HTMLDivElement>(null);
  const [user,setUser]=useState<User|null>(null),[notebooks,setNotebooks]=useState<Notebook[]>([]),[selected,setSelected]=useState<Notebook|null>(null);
  const [boards,setBoards]=useState<import('@/lib/api').Board[]>([]);
  const [title,setTitle]=useState(''),[savedTitle,setSavedTitle]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[loaded,setLoaded]=useState(false);
  const selectNotebook=useCallback((item:Notebook)=>{setSelected(item);setTitle(item.title);setSavedTitle(item.title);},[]);
  const load=useCallback(async()=>{try{const [account,items,allBoards]=await Promise.all([api<User>('/auth/me'),api<Notebook[]>('/notebooks'),api('/boards')]);setUser(account);setNotebooks(items);setBoards(allBoards as import('@/lib/api').Board[]);if(items.length)setSelected(current=>{const item=items.find(candidate=>candidate.id===current?.id)||items[0];setTitle(item.title);setSavedTitle(item.title);return item;});setError('');}catch(err){setError((err as Error).message)}finally{setLoaded(true)}},[]);
  useEffect(()=>{const timer=window.setTimeout(()=>{if(!getToken()){router.replace('/');return;} void load();},0);return()=>window.clearTimeout(timer);},[load,router]);
  const save=useCallback(async(content?:string,titleOverride?:string)=>{if(!selected)return;const nextContent=content??editor.current?.innerHTML??'';const nextTitle=(titleOverride??title).trim()||'Sem título';setSaving(true);try{const updated=await send<Notebook>(`/notebooks/${selected.id}`,'PATCH',{title:nextTitle,content_html:nextContent});setNotebooks(items=>items.map(item=>item.id===updated.id?updated:item).sort((a,b)=>b.updated_at.localeCompare(a.updated_at)));setSelected(updated);setSavedTitle(updated.title);setError('');}catch(err){setError((err as Error).message)}finally{setSaving(false)}},[selected,title]);
  useEffect(()=>{if(!selected)return;const timer=window.setTimeout(()=>{const content=editor.current?.innerHTML??'';if(content!==selected.content_html||title!==savedTitle)void save(content);},900);return()=>window.clearTimeout(timer);},[selected,title,savedTitle,save]);
  async function create(){try{const item=await send<Notebook>('/notebooks','POST',{title:'Nova anotação'});setNotebooks(items=>[item,...items]);selectNotebook(item);setError('');}catch(err){setError((err as Error).message)}}
  async function remove(){if(!selected||!window.confirm(`Excluir “${selected.title}”?`))return;try{await send(`/notebooks/${selected.id}`,'DELETE');const remaining=notebooks.filter(item=>item.id!==selected.id);setNotebooks(remaining);if(remaining[0])selectNotebook(remaining[0]);else setSelected(null);}catch(err){setError((err as Error).message)}}
  function command(name:string,argument?:string){editor.current?.focus();document.execCommand(name,false,argument);editor.current?.dispatchEvent(new Event('input',{bubbles:true}));}
  function paste(event:React.ClipboardEvent<HTMLDivElement>){const html=event.clipboardData.getData('text/html');if(!html)return;event.preventDefault();document.execCommand('insertHTML',false,safeClipboardHtml(html));editor.current?.dispatchEvent(new Event('input',{bubbles:true}));}
  if(!loaded)return <div className="grid min-h-screen place-items-center text-sm text-[#626f86]">Carregando cadernos...</div>;
  return <div className="flex min-h-screen flex-col bg-[#f7f8fa]"><AppHeader user={user} boards={boards}/><div className="flex min-h-0 flex-1"><WorkspaceSidebar boards={boards} onCreate={()=>router.push('/boards?create=1')} onChoose={id=>router.push(`/board/${id}`)}/><main className="flex min-w-0 flex-1 flex-col p-3 sm:p-5"><div className="mx-auto flex w-full max-w-[1450px] min-h-0 flex-1 overflow-hidden rounded-xl border border-[#dfe1e6] bg-white shadow-sm">
    <aside className="flex w-56 shrink-0 flex-col border-r border-[#dfe1e6] bg-[#f7f8fa] sm:w-64"><div className="flex items-center justify-between border-b border-[#dfe1e6] px-3 py-3"><strong className="text-sm">Cadernos</strong><button onClick={()=>void create()} title="Nova anotação" className="rounded p-1.5 text-[#0c66e4] hover:bg-[#d8e8ff]"><Plus size={18}/></button></div><div className="scrollbar-thin min-h-0 flex-1 overflow-y-auto p-2">{notebooks.map(item=><button key={item.id} onClick={()=>selectNotebook(item)} className={`mb-1 w-full rounded px-3 py-2 text-left text-sm ${selected?.id===item.id?'bg-[#e9f2ff] font-semibold text-[#0c66e4]':'hover:bg-[#f1f2f4]'}`}><span className="block truncate">{item.title}</span><span className="mt-0.5 block text-[11px] font-normal text-[#626f86]">{new Date(item.updated_at).toLocaleDateString('pt-BR')}</span></button>)}{notebooks.length===0&&<div className="px-3 py-8 text-center text-xs text-[#626f86]">Crie sua primeira folha.</div>}</div></aside>
    <section className="flex min-w-0 flex-1 flex-col">{selected?<><div className="flex items-center gap-2 border-b border-[#dfe1e6] px-3 py-2"><button onClick={()=>router.back()} className="rounded p-1.5 hover:bg-[#f1f2f4] lg:hidden"><ChevronLeft size={18}/></button><input value={title} onChange={event=>setTitle(event.target.value)} maxLength={160} aria-label="Título da anotação" className="min-w-0 flex-1 bg-transparent px-2 py-1 text-lg font-bold outline-none"/><span className="hidden text-xs text-[#626f86] sm:inline">{saving?'Salvando...':'Salvo automaticamente'}</span><button onClick={()=>void remove()} title="Excluir anotação" className="rounded p-2 text-[#ae2a19] hover:bg-[#ffebe6]"><Trash2 size={17}/></button></div><div className="flex flex-wrap items-center gap-0.5 border-b border-[#dfe1e6] bg-[#f7f8fa] px-2 py-1"><button onClick={()=>command('undo')} title="Desfazer" className="notebook-tool"><Undo2 size={16}/></button><button onClick={()=>command('redo')} title="Refazer" className="notebook-tool"><Redo2 size={16}/></button><i className="mx-1 h-5 border-l border-[#dfe1e6]"/><button onClick={()=>command('formatBlock','h1')} title="Título" className="notebook-tool"><Heading1 size={17}/></button><button onClick={()=>command('bold')} title="Negrito" className="notebook-tool"><Bold size={16}/></button><button onClick={()=>command('italic')} title="Itálico" className="notebook-tool"><Italic size={16}/></button><button onClick={()=>command('underline')} title="Sublinhado" className="notebook-tool"><Underline size={16}/></button><button onClick={()=>command('insertUnorderedList')} title="Lista" className="notebook-tool"><List size={17}/></button><button onClick={()=>command('insertOrderedList')} title="Lista numerada" className="notebook-tool"><ListOrdered size={17}/></button><button onClick={()=>{const url=window.prompt('Endereço do link');if(url)command('createLink',url)}} title="Link" className="notebook-tool"><Link size={16}/></button><button onClick={()=>command('formatBlock','pre')} title="Código" className="notebook-tool"><Code size={16}/></button><span className="ml-auto hidden items-center gap-1 text-[11px] text-[#626f86] md:flex"><ClipboardPaste size={14}/> Cole conteúdo de Word, PDF ou páginas mantendo o visual</span></div><div className="notebook-paper scrollbar-thin min-h-0 flex-1 overflow-y-auto p-5 sm:p-9"><div key={selected.id} ref={editor} contentEditable suppressContentEditableWarning onPaste={paste} onInput={()=>undefined} dangerouslySetInnerHTML={{__html:selected.content_html}} data-placeholder="Comece a escrever ou cole aqui seu conteúdo formatado..." className="notebook-editor mx-auto min-h-[calc(100vh-250px)] max-w-4xl outline-none"/></div></>:<div className="grid flex-1 place-items-center text-sm text-[#626f86]"><button onClick={()=>void create()} className="rounded bg-[#0c66e4] px-4 py-2 font-semibold text-white">Criar anotação</button></div>}</section>
  </div>{error&&<p role="alert" className="mx-auto mt-3 w-full max-w-[1450px] rounded bg-[#ffebe6] px-3 py-2 text-sm text-[#ae2a19]">{error}</p>}</main></div></div>;
}
