'use client';

import { FormEvent, useCallback, useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { AtSign, Banknote, BriefcaseBusiness, ChevronDown, ChevronUp, Clipboard, Cloud, Code2, Copy, CreditCard, Database, Eye, EyeOff, FileKey2, Fingerprint, Folder, Globe, KeyRound, Landmark, Laptop, LockKeyhole, Mail, Monitor, Network, Pencil, Plus, Rocket, Search, Shield, ShieldCheck, Smartphone, Terminal, Trash2, UserRound, Vault, WalletCards, Wifi, Wrench } from 'lucide-react';
import type { LucideIcon } from 'lucide-react';
import { api, Board, cardUrl, getToken, send, User, VaultItem, VaultItemDetail } from '@/lib/api';
import { AppHeader, Modal, WorkspaceSidebar } from '@/components/ui';

const builtInCategories = [
  {id:'site',label:'Sites e apps',icon:UserRound,fields:['URL','Usuário','Senha']},
  {id:'api',label:'Tokens e APIs',icon:KeyRound,fields:['Endpoint','Token','Ambiente']},
  {id:'ssh',label:'Chaves públicas e privadas',icon:FileKey2,fields:['Chave pública','Chave privada','Passphrase']},
  {id:'bank_test',label:'Dados bancários de teste',icon:Landmark,fields:['Titular de teste','Número de teste','Validade de teste']},
  {id:'license',label:'Licenças e softwares',icon:Clipboard,fields:['Produto','Chave de licença','E-mail de teste']},
  {id:'custom',label:'Outro tipo',icon:LockKeyhole,fields:['Valor']},
] satisfies Array<{id:string;label:string;icon:LucideIcon;fields:string[]}>;
type Category = string;
type VaultCategory = {id:string;label:string;icon:string;position:number};
type CategoryEntry = {id:string;label:string;icon:LucideIcon;fields:string[]};
const vaultCategoryIcons:Record<string,LucideIcon>={AtSign,Banknote,BriefcaseBusiness,Cloud,Code2,CreditCard,Database,Fingerprint,Folder,Globe,KeyRound,Laptop,LockKeyhole,Mail,Monitor,Network,Rocket,Shield,Smartphone,Terminal,UserRound,WalletCards,Wifi,Wrench};
const categoryFor=(id:string,custom:VaultCategory[]=[]):CategoryEntry=>builtInCategories.find(category=>category.id===id)||{id,label:custom.find(category=>category.id===id)?.label||id,icon:vaultCategoryIcons[custom.find(category=>category.id===id)?.icon||'LockKeyhole']||LockKeyhole,fields:['Valor']};
const initialFields=(category:string,custom:VaultCategory[]=[])=>Object.fromEntries(categoryFor(category,custom).fields.map(field=>[field,'']));

export default function VaultPage() {
  const router=useRouter();
  const [user,setUser]=useState<User|null>(null),[boards,setBoards]=useState<Board[]>([]),[items,setItems]=useState<VaultItem[]>([]),[selected,setSelected]=useState<VaultItemDetail|null>(null);
  const [query,setQuery]=useState(''),[category,setCategory]=useState('all'),[editor,setEditor]=useState(false),[editing,setEditing]=useState(false),[reveal,setReveal]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const [title,setTitle]=useState(''),[kind,setKind]=useState<Category>('site'),[notes,setNotes]=useState(''),[fields,setFields]=useState<Record<string,string>>(initialFields('site'));
  const [customCategories,setCustomCategories]=useState<VaultCategory[]>([]),[newCategory,setNewCategory]=useState(''),[newCategoryIcon,setNewCategoryIcon]=useState('LockKeyhole'),[addingCategory,setAddingCategory]=useState(false);
  const categoryEntries:CategoryEntry[]=useMemo(()=>[...builtInCategories,...customCategories.map(category=>({...category,icon:vaultCategoryIcons[category.icon]||LockKeyhole,fields:['Valor']}))],[customCategories]);
  const orderedCategoryEntries=useMemo(()=>{const order=user?.preferences?.vaultCategoryOrder||[];return [...categoryEntries].sort((left,right)=>{const a=order.indexOf(left.id),b=order.indexOf(right.id);return (a<0?Number.MAX_SAFE_INTEGER:a)-(b<0?Number.MAX_SAFE_INTEGER:b)||categoryEntries.findIndex(entry=>entry.id===left.id)-categoryEntries.findIndex(entry=>entry.id===right.id);});},[categoryEntries,user?.preferences?.vaultCategoryOrder]);
  const categoryInfo=(id:string)=>categoryFor(id,customCategories);
  const load=useCallback(async()=>{try{const [account,allBoards,vault,custom]=await Promise.all([api<User>('/auth/me'),api<Board[]>('/boards'),api<VaultItem[]>('/vault'),api<VaultCategory[]>('/vault/categories')]);setUser(account);setBoards(allBoards);setItems(vault);setCustomCategories(custom);setError('');}catch(reason){setError((reason as Error).message)}},[]);
  useEffect(()=>{if(!getToken()){router.replace('/');return;}const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer);},[load,router]);
  const visible=useMemo(()=>items.filter(item=>(category==='all'||item.category===category)&&`${item.title} ${item.notes} ${categoryFor(item.category,customCategories).label}`.toLowerCase().includes(query.toLowerCase())),[items,category,query,customCategories]);
  function openNew(){setEditing(false);setTitle('');setKind('site');setNotes('');setFields(initialFields('site'));setEditor(true);setError('');}
  async function openItem(item:VaultItem){try{setSelected(await api<VaultItemDetail>(`/vault/${item.id}`));setReveal(false);setError('');}catch(reason){setError((reason as Error).message)}}
  function edit(){if(!selected)return;setEditing(true);setTitle(selected.title);setKind(selected.category as Category);setNotes(selected.notes);setFields(selected.fields);setEditor(true);}
  function changeKind(next:Category){setKind(next);setFields(current=>{const defaults=initialFields(next,customCategories);return {...defaults,...Object.fromEntries(Object.entries(current).filter(([key])=>key in defaults))};});}
  async function createCategory(event:FormEvent){event.preventDefault();if(!newCategory.trim())return;try{const created=await send<VaultCategory>('/vault/categories','POST',{name:newCategory,icon:newCategoryIcon});setCustomCategories(current=>[...current,created]);setNewCategory('');setNewCategoryIcon('LockKeyhole');setAddingCategory(false);setCategory(created.id);setKind(created.id);setFields(initialFields(created.id,[...customCategories,created]));setEditor(true);setError('');}catch(reason){setError((reason as Error).message)}}
  async function moveCategory(id:string,direction:-1|1){const index=orderedCategoryEntries.findIndex(category=>category.id===id),target=index+direction;if(index<0||target<0||target>=orderedCategoryEntries.length)return;const order=orderedCategoryEntries.map(category=>category.id);[order[index],order[target]]=[order[target],order[index]];const previous=user;setUser(current=>current?{...current,preferences:{...current.preferences!,vaultCategoryOrder:order}}:current);try{const account=await send<User>('/account/preferences','PATCH',{vaultCategoryOrder:order});setUser(account);}catch(reason){setUser(previous);setError((reason as Error).message)}}
  function addField(){setFields(current=>({...current,[`Campo ${Object.keys(current).length+1}`]:''}));}
  async function save(event:FormEvent){event.preventDefault();setBusy(true);try{const body={title,category:kind,notes,fields};const saved=editing&&selected?await send<VaultItem>(`/vault/${selected.id}`,'PATCH',body):await send<VaultItem>('/vault','POST',body);setEditor(false);await load();await openItem(saved);}catch(reason){setError((reason as Error).message)}finally{setBusy(false)}}
  async function remove(){if(!selected||!window.confirm(`Excluir “${selected.title}”?`))return;try{await send(`/vault/${selected.id}`,'DELETE');setSelected(null);await load();}catch(reason){setError((reason as Error).message)}}
  async function copy(value:string){try{await navigator.clipboard.writeText(value)}catch{setError('Não foi possível copiar este campo.')}}
  const SelectedIcon=selected?categoryInfo(selected.category).icon:Vault;
  return <div className="flex min-h-screen flex-col bg-[#f7f8fa]"><AppHeader user={user} boards={boards}/><div className="flex min-h-0 flex-1"><WorkspaceSidebar boards={boards} onCreate={()=>router.push('/boards?create=1')} onChoose={id=>router.push(`/board/${id}`)}/><main className="mx-auto w-full max-w-[1450px] px-4 py-6 sm:px-7">
    <div className="mb-6 flex flex-wrap items-start justify-between gap-4"><div><div className="flex items-center gap-2.5"><span className="grid h-10 w-10 place-items-center rounded-xl bg-[#403294] text-white shadow-sm"><Vault size={21}/></span><div><h1 className="text-2xl font-bold tracking-tight">Cofre local</h1><p className="mt-0.5 text-sm text-[#626f86]">Dados de teste organizados, cifrados e separados dos seus quadros.</p></div></div></div><button onClick={openNew} className="flex items-center gap-2 rounded bg-[#403294] px-4 py-2 text-sm font-semibold text-white hover:bg-[#2f2673]"><Plus size={17}/> Novo item</button></div>
    {error&&<p role="alert" className="mb-4 rounded bg-[#ffebe6] p-3 text-sm text-[#ae2a19]">{error}</p>}
    <div className={`grid gap-5 ${selected ? "lg:grid-cols-[310px_minmax(0,1fr)_minmax(330px,.9fr)]" : "lg:grid-cols-[310px_minmax(0,1fr)]"}`}><section className="rounded-xl border border-[#dfe1e6] bg-white p-3 shadow-sm"><div className="relative mb-3"><Search className="absolute left-3 top-2.5 text-[#626f86]" size={16}/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Buscar no cofre" className="w-full rounded border border-[#8590a2] py-2 pl-9 pr-3 text-sm"/></div><p className="mb-2 px-2 text-[11px] font-bold uppercase tracking-wide text-[#626f86]">Categorias</p>
      <button onClick={()=>setCategory('all')} className={`mb-1 flex w-full items-center justify-between rounded px-2.5 py-2 text-left text-sm ${category==='all'?'bg-[#eeedfd] font-semibold text-[#403294]':'hover:bg-[#f1f2f4]'}`}><span>Todos os itens</span><span className="text-xs">{items.length}</span></button>
      {orderedCategoryEntries.map((entry,index)=>{const Icon=entry.icon;return <div key={entry.id} className={`mb-1 flex items-center rounded pr-1 ${category===entry.id?'bg-[#eeedfd] font-semibold text-[#403294]':'hover:bg-[#f1f2f4]'}`}><button onClick={()=>setCategory(entry.id)} className="flex min-w-0 flex-1 items-center gap-2.5 px-2.5 py-2 text-left text-sm"><Icon size={16}/><span className="min-w-0 flex-1 truncate">{entry.label}</span><span className="text-xs">{items.filter(item=>item.category===entry.id).length}</span></button><div className="flex shrink-0"><button type="button" disabled={index===0} onClick={()=>void moveCategory(entry.id,-1)} aria-label={`Mover ${entry.label} para cima`} title="Mover para cima" className="rounded p-1 hover:bg-black/5 disabled:opacity-30"><ChevronUp size={14}/></button><button type="button" disabled={index===orderedCategoryEntries.length-1} onClick={()=>void moveCategory(entry.id,1)} aria-label={`Mover ${entry.label} para baixo`} title="Mover para baixo" className="rounded p-1 hover:bg-black/5 disabled:opacity-30"><ChevronDown size={14}/></button></div></div>})}
      {addingCategory?<form onSubmit={createCategory} className="mt-3 space-y-2 rounded-lg border border-[#dfe1e6] p-2"><input autoFocus value={newCategory} onChange={event=>setNewCategory(event.target.value)} maxLength={48} placeholder="Nome da categoria" className="w-full min-w-0 rounded border border-[#8590a2] px-2 py-1.5 text-xs"/><p className="text-[10px] font-semibold text-[#626f86]">Ícone</p><div className="grid grid-cols-6 gap-1">{Object.entries(vaultCategoryIcons).map(([name,Icon])=><button key={name} type="button" onClick={()=>setNewCategoryIcon(name)} aria-label={`Ícone ${name}`} title={name} className={`grid h-8 place-items-center rounded ${newCategoryIcon===name?'bg-[#403294] text-white':'text-[#626f86] hover:bg-[#f1f2f4]'}`}><Icon size={16}/></button>)}</div><div className="flex justify-end gap-1"><button type="button" onClick={()=>setAddingCategory(false)} className="rounded px-2 py-1.5 text-xs">Cancelar</button><button disabled={!newCategory.trim()} className="rounded bg-[#403294] px-2 py-1.5 text-xs font-semibold text-white disabled:opacity-50">Adicionar</button></div></form>:<button onClick={()=>setAddingCategory(true)} className="mt-2 flex w-full items-center gap-2 rounded px-2.5 py-2 text-left text-xs font-semibold text-[#403294] hover:bg-[#eeedfd]"><Plus size={14}/> Nova categoria</button>}</section>
      <section className="min-h-[480px] overflow-hidden rounded-xl border border-[#dfe1e6] bg-white shadow-sm"><div className="flex items-center justify-between border-b border-[#dfe1e6] px-4 py-3"><div><h2 className="font-bold">Itens protegidos</h2><p className="text-xs text-[#626f86]">Os valores secretos não aparecem nesta lista.</p></div><ShieldCheck className="text-[#22a06b]" size={20}/></div><div className="divide-y divide-[#f1f2f4]">{visible.map(item=>{const Icon=categoryInfo(item.category).icon;return <button key={item.id} onClick={()=>void openItem(item)} className={`flex w-full items-center gap-3 px-4 py-3.5 text-left hover:bg-[#f7f8fa] ${selected?.id===item.id?'bg-[#eeedfd]':''}`}><span className="grid h-9 w-9 place-items-center rounded-lg bg-[#f1f2f4] text-[#403294]"><Icon size={18}/></span><span className="min-w-0 flex-1"><strong className="block truncate text-sm">{item.title}</strong><span className="mt-0.5 block truncate text-xs text-[#626f86]">{categoryInfo(item.category).label}{item.notes?` · ${item.notes}`:''}</span></span><span className="text-[11px] text-[#626f86]">{new Date(item.updated_at).toLocaleDateString('pt-BR')}</span></button>})}{visible.length===0&&<div className="px-7 py-16 text-center"><LockKeyhole className="mx-auto mb-3 text-[#626f86]" size={28}/><p className="font-semibold">Nenhum item por aqui</p><p className="mt-1 text-sm text-[#626f86]">Adicione uma credencial de teste ou ajuste os filtros.</p></div>}</div></section>
      {selected&&<section className="min-h-[480px] rounded-xl border border-[#dfe1e6] bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><span className="grid h-10 w-10 place-items-center rounded-lg bg-[#eeedfd] text-[#403294]"><SelectedIcon size={20}/></span><div className="min-w-0 flex-1"><h2 className="truncate font-bold">{selected.title}</h2><p className="text-xs text-[#626f86]">{categoryInfo(selected.category).label}</p></div>{selected.card_id&&selected.board_id&&<button onClick={()=>router.push(cardUrl(selected.board_id!,selected.card_id,selected.url_token))} title="Abrir cartão" className="rounded p-2 text-[#403294] hover:bg-[#eeedfd]"><CreditCard size={16}/></button>}<button onClick={edit} title="Editar" className="rounded p-2 hover:bg-[#f1f2f4]"><Pencil size={16}/></button><button onClick={()=>void remove()} title="Excluir" className="rounded p-2 text-[#ae2a19] hover:bg-[#ffebe6]"><Trash2 size={16}/></button></div>{selected.notes&&<p className="mt-4 rounded bg-[#f7f8fa] p-3 text-sm text-[#44546f]">{selected.notes}</p>}<div className="mt-5"><button onClick={()=>setReveal(value=>!value)} className="mb-3 flex items-center gap-2 text-sm font-semibold text-[#403294]">{reveal?<EyeOff size={16}/>:<Eye size={16}/>} {reveal?'Ocultar valores':'Mostrar valores'}</button><div className="space-y-3">{Object.entries(selected.fields).map(([label,field])=><div key={label}><p className="mb-1 text-[11px] font-bold uppercase tracking-wide text-[#626f86]">{label}</p><div className="flex gap-2"><code className="min-w-0 flex-1 break-all rounded bg-[#f1f2f4] px-3 py-2 text-xs text-[#172b4d]">{reveal?field:'••••••••••••••••'}</code><button onClick={()=>void copy(field)} title={`Copiar ${label}`} className="rounded border border-[#dfe1e6] p-2 hover:bg-[#f1f2f4]"><Copy size={15}/></button></div></div>)}</div></div></section>}</div>
  </main></div>{editor&&<VaultEditor categories={categoryEntries} title={title} kind={kind} notes={notes} fields={fields} editing={editing} busy={busy} onClose={()=>setEditor(false)} onTitle={setTitle} onKind={changeKind} onNotes={setNotes} onFields={setFields} onAddField={addField} onSave={save}/>}</div>;
}

function VaultEditor({categories,title,kind,notes,fields,editing,busy,onClose,onTitle,onKind,onNotes,onFields,onAddField,onSave}:{categories:CategoryEntry[];title:string;kind:Category;notes:string;fields:Record<string,string>;editing:boolean;busy:boolean;onClose:()=>void;onTitle:(value:string)=>void;onKind:(value:Category)=>void;onNotes:(value:string)=>void;onFields:(value:Record<string,string>)=>void;onAddField:()=>void;onSave:(event:FormEvent)=>void}) {
  return <Modal wide onClose={onClose}><form onSubmit={onSave} className="p-6"><h2 className="text-xl font-bold">{editing?'Editar item':'Novo item no cofre'}</h2><p className="mt-1 text-sm text-[#626f86]">Use apenas dados fictícios e locais de testes.</p><label className="mt-5 block text-xs font-bold">Nome do item<input required maxLength={160} autoFocus value={title} onChange={event=>onTitle(event.target.value)} className="mt-1.5 w-full rounded border border-[#8590a2] px-3 py-2 text-sm" placeholder="Ex.: Conta demo do Figma"/></label><label className="mt-4 block text-xs font-bold">Categoria<select value={kind} onChange={event=>onKind(event.target.value as Category)} className="mt-1.5 w-full rounded border border-[#8590a2] px-3 py-2 text-sm">{categories.map(category=><option key={category.id} value={category.id}>{category.label}</option>)}</select></label><label className="mt-4 block text-xs font-bold">Observação (não secreta)<textarea value={notes} onChange={event=>onNotes(event.target.value)} maxLength={4000} className="mt-1.5 min-h-20 w-full rounded border border-[#8590a2] px-3 py-2 text-sm" placeholder="Ex.: Usar somente no ambiente sandbox."/></label><div className="mt-5 border-t border-[#dfe1e6] pt-4"><div className="mb-3 flex items-center justify-between"><p className="text-xs font-bold">Campos protegidos</p><button type="button" onClick={onAddField} className="text-xs font-semibold text-[#403294]">+ Adicionar campo</button></div><div className="space-y-3">{Object.entries(fields).map(([label,value])=><div key={label} className="grid gap-2 sm:grid-cols-[150px_1fr]"><input value={label} maxLength={80} onChange={event=>{const next={...fields};delete next[label];next[event.target.value]=value;onFields(next)}} className="rounded border border-[#8590a2] px-2.5 py-2 text-sm"/><textarea value={value} onChange={event=>onFields({...fields,[label]:event.target.value})} className="min-h-10 rounded border border-[#8590a2] px-2.5 py-2 font-mono text-xs"/></div>)}</div></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={onClose} className="rounded bg-[#f1f2f4] px-4 py-2 text-sm font-semibold">Cancelar</button><button disabled={busy||!title.trim()} className="rounded bg-[#403294] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50">{busy?'Salvando...':'Salvar no cofre'}</button></div></form></Modal>;
}
